// Independent natural-country urn acceptance. No provider/scenery/birth overrides.
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const dir=path.join(__dirname,'reports'),tag=process.env.URN_TAG||new Date().toISOString().replace(/[:.]/g,'-'),prefix='native-urns-'+tag;
fs.mkdirSync(dir,{recursive:true});app.setPath('userData',path.join(dir,prefix+'-profile'));app.disableHardwareAcceleration();
const candidates=[[-13710,-36030],[-46560,24180],[-57330,-51660],[-46290,-58200],[55770,-35370],[55380,-31140],[-57570,-46890],[-58380,-62670],[-46230,-46140],[-56970,39330]];
app.whenReady().then(async()=>{
 const root=path.resolve(__dirname,'..',process.env.URN_DIST||'dist-preview'),report={seed:713,run:prefix,methodology:'Unchanged default native-country selection; controlled initial placement at naturally generated sites and safe approach points. Actual native input walks and attacks break original urns. Player invulnerability is explicitly enabled to isolate ownership from hero death; other bodies/collision/effects stay active. Native grantXp matches source level. No urn/spawn/reward rule, provider, RNG or scenery substitution. Actual World.kill may be used only in a labelled death-receipt case after natural birth. Active Continue uses native transient action boundary, not exact combat resumption.',consoleErrors:[],sites:[],pops:[],screenshots:[]};
 report.harnessSha256=crypto.createHash('sha256').update(fs.readFileSync(__filename)).digest('hex');fs.copyFileSync(__filename,path.join(dir,prefix+'.cjs'));
 const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const url='http://127.0.0.1:'+server.address().port,win=new BrowserWindow({show:false,width:1280,height:850,webPreferences:{offscreen:true,backgroundThrottling:false}});
 win.webContents.on('console-message',e=>{if(e.level==='error')report.consoleErrors.push(e.message);else if(e.message.startsWith('URN_'))console.log(e.message);});
 const save=()=>fs.writeFileSync(path.join(dir,prefix+'.json'),JSON.stringify(report,null,2));
 const run=async(fn,...args)=>{const r=await win.webContents.executeJavaScript('(async()=>{try{return{ok:true,value:await('+fn+')('+args.map(a=>JSON.stringify(a)).join(',')+')}}catch(e){return{ok:false,error:e.stack||String(e)}}})()');if(!r.ok)throw Error(r.error);return r.value;};
 const boot=async()=>{await win.loadURL(url);await run(async()=>{window.requestAnimationFrame=()=>0;Object.defineProperty(navigator,'getGamepads',{value:()=>[]});for(let i=0;i<100&&!window.__game;i++)await new Promise(r=>setTimeout(r,100));if(!window.__game)throw Error('Game unavailable');await new Promise(r=>setTimeout(r,300));});};
 const shot=async name=>{await run(()=>__game.renderer.render(__game.world()));win.webContents.invalidate();await new Promise(r=>setTimeout(r,80));const file=path.join(dir,prefix+'-'+name+'.png');fs.writeFileSync(file,(await win.webContents.capturePage()).toPNG());report.screenshots.push(file);return file;};
 const install=owner=>{
  const w=__game.world();window.__urnOwner=owner;window.__urnEvents=[];window.__urnWords=[];
  window.__urnReceipt=()=>{const b=w.massRuntime?.nativeFeatures.snapshot(w.time).born.find(b=>b.placement.id===window.__urnOwner);if(!b)throw Error('Missing actual native owner '+window.__urnOwner);return{owner:b.placement.id,source:b.descriptor.source,hash:b.descriptor.hash,level:b.descriptor.zone.level,changes:b.changes.doodads,brittles:b.changes.native?.brittles,mouths:w.caveEntrances.filter(e=>e.massOwner===b.placement.id).map(e=>({kind:e.kind,pos:{...e.pos},seed:e.seed})),pos:{...w.player.pos},charId:w.meta.charId,time:w.time,xp:w.meta.xp,drops:JSON.parse(JSON.stringify(w.drops))};};
  window.__urnBodies=()=>{const r=window.__urnReceipt();return r.brittles.slots.flatMap(s=>s.births.filter(b=>!b.dead).map(b=>({receipt:b,actor:w.actors.find(a=>a.id===b.actorId)})));};
  if(window.__urnWrappedWorld===w){w.popBrittle=window.__urnOriginalPop;w.text=window.__urnOriginalText;}
  const pop=w.popBrittle;window.__urnWrappedWorld=w;window.__urnOriginalPop=pop;window.__urnOriginalText=w.text;w.popBrittle=function(d,...args){const ours=w.massNativeBrittleOwners.get(window.__urnOwner)?.has(d),before={gone:!!d.gone,actors:new Set(w.actors),drops:new Set(w.drops),orbs:new Set(w.orbs)};const r=pop.call(this,d,...args);if(ours&&!before.gone&&d.gone)window.__urnEvents.push({at:w.time,pos:{...d.pos},kind:d.kind,actors:w.actors.filter(a=>!before.actors.has(a)).map(a=>({id:a.id,monster:a.defId,level:a.level,life:a.life,pos:{...a.pos},emerging:!!w.emergeOf(a),fromZoneGen:!!a.fromZoneGen})),drops:JSON.parse(JSON.stringify(w.drops.filter(d=>!before.drops.has(d)))),orbs:JSON.parse(JSON.stringify(w.orbs.filter(d=>!before.orbs.has(d)))),dissolves:w.dissolves.length});return r;};
  const text=w.text;w.text=function(at,msg,...args){if(/urn|skeleton|wake|loot!|level up/i.test(String(msg)))window.__urnWords.push(String(msg));return text.call(this,at,msg,...args);};
  window.__urnStep=async frames=>{for(let n=0;n<frames;n++){__game.step(1,1000/30);if(w.player.dead)throw Error('Course hero died');if(__game.crash().fatal)throw Error(__game.crash().fatal);if(n%15===0)await new Promise(r=>setTimeout(r,0));}};
  window.__urnWalk=async(target,stop=5,limit=900)=>{const before={...w.player.pos};let frames=0;__game.devInput(()=>{const dx=target.x-w.player.pos.x,dy=target.y-w.player.pos.y,d=Math.hypot(dx,dy);return{dx:d>stop?dx/d:0,dy:d>stop?dy/d:0,aim:target,held:[],edge:[]};});try{for(;frames<limit;frames++){if(Math.hypot(target.x-w.player.pos.x,target.y-w.player.pos.y)<=stop)return{before,after:{...w.player.pos},frames};await window.__urnStep(1);}}finally{__game.devInput(null);}throw Error('Natural walking blocked '+JSON.stringify({target,before,after:w.player.pos}));};
  window.__urnApproach=(target,near,far)=>{for(let i=0;i<32;i++){const a=i*Math.PI/16,inner={x:target.x+Math.cos(a)*near,y:target.y+Math.sin(a)*near},outer={x:target.x+Math.cos(a)*far,y:target.y+Math.sin(a)*far};let clear=true;for(let j=0;j<=32;j++){const p={x:inner.x+(outer.x-inner.x)*j/32,y:inner.y+(outer.y-inner.y)*j/32};if(w.walk&&!w.walk.isWalkable(p.x,p.y)||w.pointInSolid(p.x,p.y,w.player.radius+1)){clear=false;break;}}if(clear)return{inner,outer};}return null;};
 };
 const resume=async(owner,label)=>{const before=await run(async()=>{const r=window.__urnReceipt();__game.save();await __game.flushRunSave();return r;});await boot();await run(async charId=>{for(let i=0;i<100&&!document.querySelector('#sm-continue:not([disabled])');i++)await new Promise(r=>setTimeout(r,100));const b=document.querySelector('#sm-continue:not([disabled])');if(!b)throw Error('Continue unavailable');b.click();for(let i=0;i<200&&(!__game.world().massRuntime||__game.world().meta.charId!==charId);i++)await new Promise(r=>setTimeout(r,50));if(!__game.world().massRuntime)throw Error('Surface Continue failed');__game.ui.hideAll();__game.world().player.invulnerable=true;},before.charId);await run(install,owner);const after=await run(()=>window.__urnReceipt());const durable=r=>r.brittles.slots.map(s=>({index:s.index,popped:s.popped,birthCount:s.birthCount,definitionHash:s.definitionHash,births:s.births.map(({actorId:_,state:__,...birth})=>birth)}));assert.deepEqual(durable(after),durable(before),label+' exact receipt');assert.deepEqual(after.changes,before.changes);assert.equal(after.hash,before.hash);assert.equal(after.xp,before.xp);assert.deepEqual(after.pos,before.pos);return{before,after};};
 const timer=setTimeout(()=>{save();console.error('Urn browser timeout '+prefix);app.exit(1);},1200000);
 try{
  await boot();report.bundle=await run(()=>Array.from(document.scripts).map(s=>s.src).filter(Boolean));const main=report.bundle.find(s=>/\/assets\/index-/.test(s));if(main){const file=path.join(root,new URL(main).pathname);report.bundleSha256=crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}if(process.env.URN_EXPECT_BUNDLE)assert.ok(main?.endsWith('/'+process.env.URN_EXPECT_BUNDLE));
  await run(()=>{__game.devStartRun('warrior');__game.ui.hideAll();const w=__game.world();w.startWorldMass(713);w.player.invulnerable=true;__game.step(1);document.querySelectorAll('button').forEach(b=>{if(b.textContent.trim()==='Walk on')b.click();});__game.ui.hideAll();});
  let activeOwner=null,firstMouth=null,wakeChecked=false,lootChecked=false;
  for(const origin of candidates){
   const site=await run(async([x,y])=>{const w=__game.world(),m=w.massRuntime,row=m.nativeCountry.near(m.walk.at(x+900,y+900),2700).find(p=>p.request.source.kind==='composition'&&['family_plot','buried_village','caravan_graveyard'].includes(p.request.source.id));if(!row)return{origin:[x,y],missing:true};w.landPartyAt({x:x+900,y:y+900});m.update(w,true);for(let n=0;n<120&&!w.massNativeBrittleOwners.has(row.id);n++){__game.step(1,1000/30);if(n%15===0)await new Promise(r=>setTimeout(r,0));}const pieces=[...(w.massNativeBrittleOwners.get(row.id)??[])];const source=w.caveEntrances.find(e=>e.massOwner===row.id)?.parent;const level=source?.level??w.levelAt(pieces[0]?.pos??w.player.pos);while(w.player.level<level)w.grantXp(1000);return{origin:[x,y],owner:row.id,source:row.request.source,seed:row.request.seed,level,urns:pieces.map(d=>({pos:{...d.pos},radius:d.radius})),refusals:m.nativeFeatures.refusals(row.id)};},origin);report.sites.push(site);save();if(!site.urns?.length)continue;activeOwner=site.owner;await run(install,activeOwner);if(!firstMouth){const r=await run(()=>window.__urnReceipt());if(r.mouths.length)firstMouth={owner:activeOwner,mouth:r.mouths[0],origin};}
   for(let ix=0;ix<site.urns.length;ix++){
    const mode=report.pops.length===0?'touch':'hit';const prepared=await run((pos,mode)=>{const w=__game.world(),d=[...(w.massNativeBrittleOwners.get(window.__urnOwner)??[])].find(d=>!d.gone&&Math.hypot(d.pos.x-pos.x,d.pos.y-pos.y)<1);if(!d)return null;window.__urnTarget=d;const approach=window.__urnApproach(d.pos,mode==='hit'?52:0,130);if(!approach)return null;w.landPartyAt(approach.outer);w.massRuntime.update(w,true);return{mode,pos:{...d.pos},approach,before:window.__urnReceipt()};},site.urns[ix].pos,mode);if(!prepared)continue;await shot('before-'+report.pops.length);
    const pop=await run(async prepared=>{const w=__game.world(),target=window.__urnTarget;let frames=0;__game.devInput(()=>{const q=prepared.mode==='hit'?prepared.approach.inner:target.pos,dx=q.x-w.player.pos.x,dy=q.y-w.player.pos.y,d=Math.hypot(dx,dy);return{dx:d>3?dx/d:0,dy:d>3?dy/d:0,aim:target.pos,held:[prepared.mode==='hit'&&d<6,false,false],edge:[]};});try{for(;frames<600&&!target.gone;frames++){await window.__urnStep(1);if(w.inCave)throw Error('Unexpected cave traversal during native break');}}finally{__game.devInput(null);}if(!target.gone)throw Error('Native '+prepared.mode+' did not break original urn');return{owner:window.__urnOwner,mode:prepared.mode,frames,before:prepared.before,after:window.__urnReceipt(),events:[...window.__urnEvents],words:[...window.__urnWords]};},prepared);report.pops.push(pop);assert.deepEqual(pop.words,[]);await shot('popped-'+report.pops.length);save();
    if(!lootChecked){
     const loot=await run(()=>{const w=__game.world(),e=window.__urnEvents.at(-1);if(!e)return null;const d=w.drops.find(d=>e.drops.some(p=>p.pos.x===d.pos.x&&p.pos.y===d.pos.y)&&['gear','skill','support'].includes(d.item.kind));if(!d)return null;const item=d.item,inst=item.inst,gem=item.gem;const payload=item.kind==='gear'?{kind:'gear',item:item.item}:item.kind==='skill'?{kind:'skill',skillId:inst.def.id,level:inst.level,rarity:inst.rarity,sockets:inst.sockets,treeNodes:inst.treeNodes}: {kind:'support',supportId:gem.def.id,level:gem.level,rolled:gem.rolled};return{pos:{...d.pos},payload:JSON.parse(JSON.stringify(payload)),raw:JSON.parse(JSON.stringify(d)),inventory:JSON.parse(JSON.stringify(w.meta.items))};});
     if(loot){
      report.loot={before:loot};await shot('uncollected-loot');report.loot.ownerContinue=await resume(activeOwner,'uncollected native loot');
      report.loot.afterContinue=await run(pos=>{const w=__game.world(),d=w.drops.find(d=>d.pos.x===pos.x&&d.pos.y===pos.y);if(!d)throw Error('Uncollected actual urn loot vanished on Continue');return{drop:JSON.parse(JSON.stringify(d)),inventory:JSON.parse(JSON.stringify(w.meta.items))};},loot.pos);
      assert.deepEqual(report.loot.afterContinue.drop,loot.raw,'Uncollected native item is exact');assert.deepEqual(report.loot.afterContinue.inventory,loot.inventory);await shot('uncollected-continue');
      report.loot.pickup=await run(async pos=>{const w=__game.world(),before=JSON.stringify(w.meta.items),approach=window.__urnApproach(pos,0,130);if(!approach)throw Error('Native urn loot has no body-clear walking approach');const beforeApproach={...w.player.pos};w.landPartyAt(approach.outer);const walked=await window.__urnWalk(pos,4);await window.__urnStep(2);if(w.drops.some(d=>d.pos.x===pos.x&&d.pos.y===pos.y))throw Error('Actual walking did not collect native urn loot');if(JSON.stringify(w.meta.items)===before)throw Error('Native pickup did not change inventory');return{approach:{before:beforeApproach,placed:{...approach.outer},method:'Controlled body-clear approach placement, then ordinary walking pickup'},walked,inventory:JSON.parse(JSON.stringify(w.meta.items)),remaining:w.drops.filter(d=>d.pos.x===pos.x&&d.pos.y===pos.y).length};},loot.pos);
      report.loot.pickedContinue=await resume(activeOwner,'picked native loot');report.loot.afterPickedContinue=await run(pos=>({inventory:JSON.parse(JSON.stringify(__game.world().meta.items)),remaining:__game.world().drops.filter(d=>d.pos.x===pos.x&&d.pos.y===pos.y).length}),loot.pos);assert.deepEqual(report.loot.afterPickedContinue.inventory,report.loot.pickup.inventory);assert.equal(report.loot.afterPickedContinue.remaining,0);await shot('picked-continue');lootChecked=true;
     }
    }
    if(!wakeChecked&&pop.after.brittles.slots.some(s=>s.births.some(b=>!b.dead))){
     report.activeContinue=await resume(activeOwner,'active wake');await shot('active-continue');
     const wounded=await run(async()=>{const w=__game.world(),body=window.__urnBodies().find(b=>b.actor&&!b.actor.dead);if(!body)throw Error('Natural wake not restored');const a=body.actor,before=a.life;let frames=0;__game.devInput(()=>({dx:0,dy:0,aim:a.pos,held:[true,false,false],edge:[]}));try{for(;frames<300&&a.life===before&&!a.dead;frames++)await window.__urnStep(1);}finally{__game.devInput(null);}return{key:body.receipt.key,before,after:a.life,dead:a.dead,frames,receipt:window.__urnReceipt()};});report.wounded=wounded;if(wounded.dead||wounded.after===wounded.before)throw Error('Natural attack did not leave a wounded survivor');report.woundedContinue=await resume(activeOwner,'wounded wake');await shot('wounded-continue');
     report.death=await run(()=>{const w=__game.world(),births=window.__urnBodies();for(const b of births)if(b.actor&&!b.actor.dead)w.kill(b.actor,false,w.player);return{method:'Explicit native World.kill on naturally born wake, to verify native death/reward receipt without a combat balance claim',keys:births.map(b=>b.receipt.key),receipt:window.__urnReceipt()};});report.deadContinue=await resume(activeOwner,'dead wake');assert.ok(report.deadContinue.after.brittles.slots.every(s=>s.births.every(b=>b.dead)));await shot('dead-continue');wakeChecked=true;
    }
   }
   if(wakeChecked&&lootChecked&&report.pops.some(p=>p.mode==='hit')&&report.pops.some(p=>p.mode==='touch'))break;
  }
  assert.ok(wakeChecked,'No genuine natural wake found within bounded source survey');assert.ok(lootChecked,'No uncollected genuine urn loot found within bounded source survey');assert.ok(report.pops.some(p=>p.mode==='hit')&&report.pops.some(p=>p.mode==='touch'));assert.ok(firstMouth,'No unchanged source with native sidegate');
  report.gate=await run(async target=>{const w=__game.world(),m=w.massRuntime;w.landPartyAt({x:target.origin[0]+900,y:target.origin[1]+900});m.update(w,true);const e=w.caveEntrances.find(e=>e.massOwner===target.owner&&e.kind===target.mouth.kind);if(!e)throw Error('Original sidegate missing');window.__urnSurfaceHero=w.player;window.__urnGate=e;return{owner:target.owner,pos:{...e.pos},kind:e.kind,seed:e.seed};},firstMouth);await run(install,firstMouth.owner);const beforeGate=await run(()=>window.__urnReceipt());
  report.entry=await run(async()=>{const w=__game.world(),e=window.__urnGate,a=window.__urnApproach(e.pos,0,130);if(!a)throw Error('Native sidegate has no real approach');w.landPartyAt(a.outer);__game.devInput(()=>{const dx=e.pos.x-w.player.pos.x,dy=e.pos.y-w.player.pos.y,d=Math.hypot(dx,dy);return{dx:d>7?dx/d:0,dy:d>7?dy/d:0,aim:e.pos,held:[],edge:[]};});let frames=0;try{for(;frames<600&&!w.inCave;frames++)await window.__urnStep(1);}finally{__game.devInput(null);}if(!w.inCave)throw Error('Native sidegate did not admit after walking/idle');return{frames,zone:w.zone.id,sceneName:w.zone.name,texts:w.texts.map(t=>t.text),pos:{...w.player.pos},returnPos:{...w.caveReturn.pos},sameHero:w.player===window.__urnSurfaceHero,charId:w.meta.charId};});assert.equal(report.entry.sameHero,true);assert.ok(!report.entry.texts.some(t=>t===report.entry.sceneName||/the niches shed their dust|it CRAWLS/i.test(t)),'No duplicate entry title or native local swarm narration');assert.deepEqual(report.entry.returnPos,report.gate.pos);await shot('native-interior');
  await run(async()=>{__game.save();await __game.flushRunSave();});await boot();report.caveContinue=await run(async expected=>{for(let n=0;n<100&&!document.querySelector('#sm-continue:not([disabled])');n++)await new Promise(r=>setTimeout(r,100));document.querySelector('#sm-continue:not([disabled])').click();for(let n=0;n<200&&!__game.world().inCave;n++)await new Promise(r=>setTimeout(r,50));const w=__game.world();__game.ui.hideAll();w.player.invulnerable=true;window.__urnSurfaceHero=w.player;return{zone:w.zone.id,sceneName:w.zone.name,texts:w.texts.map(t=>t.text),pos:{...w.player.pos},returnPos:w.caveReturn?.pos,charId:w.meta.charId,inCave:w.inCave,expected};},report.entry.zone);assert.equal(report.caveContinue.inCave,true);assert.ok(!report.caveContinue.texts.some(t=>t===report.caveContinue.sceneName||/the niches shed their dust|it CRAWLS/i.test(t)),'Continue does not replay cave entry narration');assert.equal(report.caveContinue.zone,report.entry.zone);assert.deepEqual(report.caveContinue.pos,report.entry.pos);assert.deepEqual(report.caveContinue.returnPos,report.entry.returnPos);await shot('interior-continue');
  report.returned=await run(async()=>{const w=__game.world(),exit=w.exits.find(e=>e.to==='worldmass_expedition');if(!exit)throw Error('No native surface exit');const clear=p=>(!w.walk||w.walk.isWalkable(p.x,p.y))&&!w.pointInSolid(p.x,p.y,w.player.radius);let start;for(const r of [130,100,80])for(let i=0;i<32&&!start;i++){const a=i*Math.PI/16,p={x:exit.pos.x+Math.cos(a)*r,y:exit.pos.y+Math.sin(a)*r};if(Array.from({length:30},(_,n)=>({x:p.x+(exit.pos.x-p.x)*n/29,y:p.y+(exit.pos.y-p.y)*n/29})).every(clear))start=p;}if(!start)throw Error('No physical return approach');w.landPartyAt(start);__game.devInput(()=>{const dx=exit.pos.x-w.player.pos.x,dy=exit.pos.y-w.player.pos.y,d=Math.hypot(dx,dy);return{dx:d>7?dx/d:0,dy:d>7?dy/d:0,aim:exit.pos,held:[],edge:[]};});let frames=0;try{for(;frames<600&&w.inCave;frames++){__game.step(1,1000/30);if(frames%15===0)await new Promise(r=>setTimeout(r,0));}}finally{__game.devInput(null);}return{inCave:w.inCave,pos:{...w.player.pos},sameHero:w.player===window.__urnSurfaceHero,frames};});assert.equal(report.returned.inCave,false);assert.equal(report.returned.sameHero,true);assert.deepEqual(report.returned.pos,report.gate.pos);await run(install,firstMouth.owner);report.gateRoundtrip=await run(()=>window.__urnReceipt());assert.deepEqual(report.gateRoundtrip.changes,beforeGate.changes);assert.deepEqual(report.gateRoundtrip.brittles.slots.map(s=>({index:s.index,popped:s.popped,births:s.births.map(b=>({key:b.key,dead:b.dead,life:b.life}))})),beforeGate.brittles.slots.map(s=>({index:s.index,popped:s.popped,births:s.births.map(b=>({key:b.key,dead:b.dead,life:b.life}))})));await shot('surface-return');
  assert.deepEqual(report.consoleErrors,[]);report.acceptance={unchangedNaturalProviders:true,physicalTouchAndHit:true,nativeWake:true,exactActiveAndWoundedContinue:true,nativeDeathNoReplay:true,actualSidegateAndInteriorContinue:true,noCaveEntryNarration:true,exactSurfaceReceipts:true,uncollectedLootExactContinue:true,actualPickupAndSavedAbsence:true,quietStreamingRetirementNotClaimed:true};save();fs.copyFileSync(path.join(dir,prefix+'.json'),path.join(dir,'native-urns-ui.json'));console.log('URN_PASS '+path.join(dir,prefix+'.json'));clearTimeout(timer);win.destroy();server.close();app.exit(0);
 }catch(error){report.error=String(error.stack||error);try{report.failure=await run(()=>({receipt:window.__urnReceipt?.(),crash:__game.crash(),inCave:__game.world().inCave}));}catch{}try{await shot('failure');}catch{}save();console.error(error);console.error('URN_REPORT '+path.join(dir,prefix+'.json'));clearTimeout(timer);app.exit(1);}
});
