import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { updateAI } from '../src/engine/ai';
import { makeSkillInstance } from '../src/engine/skills';
import { SKILLS } from '../src/data/skills';
import { mod } from '../src/engine/stats';
import { MONSTERS } from '../src/data/monsters';
import { WorldMassRuntime } from '../src/worldmass/runtime';
import { massAdventure } from '../src/worldmass/preset';
import { canonical } from '../src/worldmass/random';
import { serializeCharacter } from '../src/meta/character';

const restore=seedGlobalRandom(4197),hit=makeSkillInstance(SKILLS.heavy_strike,1);
const w=makeSimWorld('warrior',4197);w.startWorldMass(42);
const town=w.massRuntime!.settlement!,p=w.player;
const smith=w.actors.find(a=>a.defId&&MONSTERS[a.defId].npcRole==='vendor')!;
p.pos={...smith.pos};p.tier=smith.tier;p.invulnerable=false;
p.sheet.setSource('qa-no-regen',[mod('lifeRegen','override',0),mod('blockChance','override',0),mod('evasion','override',0)]);
const enemy=w.createMonster('skeleton_warrior',1,'enemy');enemy.pos={x:p.pos.x+30,y:p.pos.y};enemy.tier=p.tier;
enemy.sheet.setSource('qa-hit',[mod('accuracy','override',100000),mod('lifeRegen','override',0)]);enemy.fillResources();enemy.life*=.6;w.actors.push(enemy);
assert.ok(w.nearSmith());assert.ok(w.isSafeAt(p.pos));
const before=p.life,foeLife=enemy.life;
for(let i=0;i<12;i++){w.challengeHit(enemy,hit,p,1);w.challengeHit(p,p.skills[0]!,enemy,1);}
assert.equal(p.life,before);assert.equal(enemy.life,foeLife);
assert.equal(w.hostileTo(enemy,p),false);assert.equal(w.hostileTo(p,enemy),false);
console.log('PASS native Brandt ground denies both incoming hits and protected outgoing damage without invulnerability');
enemy.aiTargetId=p.id;enemy.aiAnchor={...enemy.pos};
assert.ok(w.useSkill(enemy,hit,{...p.pos}));
updateAI(enemy,w,1/60);
assert.equal(enemy.casting,null);assert.equal(enemy.aiTargetId,undefined);
assert.ok(enemy.aiAnchor&&!town.contains(enemy.aiAnchor.x,enemy.aiAnchor.y));
assert.equal(enemy.life,foeLife,'retreat never heals or replaces a pursuer');
assert.ok(w.sanctuaryBlocksCombat(enemy,p));
console.log('PASS continued intruder cancels its cast and targets a physical exit without healing');
const outside={x:-400,y:town.zone.size.h/2};p.pos={...outside};enemy.pos={x:outside.x+30,y:outside.y};
enemy.aiAnchor={...enemy.pos};
assert.equal(w.hostileTo(p,enemy),false,'walking after a returning foe cannot farm an unresponsive target');
// Finish the existing physical retreat, then normal wilderness combat resumes.
const home=w.sanctuaryRetreat(enemy)!;enemy.pos={...home};w.sanctuaryRetreat(enemy);
p.pos={x:enemy.pos.x-25,y:enemy.pos.y};
assert.ok(w.hostileTo(enemy,p));const fieldLife=p.life;
for(let i=0;i<20&&p.life===fieldLife;i++)w.challengeHit(enemy,hit,p,1);
assert.ok(p.life<fieldLife,'same real hit damages normally outside');
assert.ok(w.sanctuaryBlocksCombat(p,enemy,smith.pos),'shot authored in town cannot pay damage after the caster steps outside');
console.log('PASS wilderness damage resumes; an old shot authored in town stays blocked');
const delayed=makeSkillInstance(SKILLS.doomsayers_word,1),delayedLife=p.life,delayedFoeLife=enemy.life;
w.challengeHit(enemy,delayed,p,1);w.challengeHit(p,delayed,enemy,1);
assert.equal(w.pendingFuses.length,2,'real native delayed hits bank outside the town');
p.pos={...smith.pos};
for(let i=0;i<80;i++)w.update(.05);
assert.equal(w.pendingFuses.length,0);assert.equal(p.life,delayedLife);assert.equal(enemy.life,delayedFoeLife);
assert.ok(!p.statuses.some(s=>s.id==='decay')&&!enemy.statuses.some(s=>s.id==='decay'));
console.log('PASS already-banked native hits expire harmlessly after either side enters sanctuary');
const minion=w.createMonster('skeleton_warrior',1,'player');minion.owner=p;minion.pos={...enemy.pos};
p.pos={...smith.pos};
assert.equal(w.hostileTo(minion,enemy),false);
assert.ok(w.sanctuaryBlocksCombat(enemy,minion),'refuge cannot attack through outside owned minions');
assert.equal(w.sanctuaryBlocksCombat(p,smith),false,'native resident interaction preserved');
const resident=town.snapshot(w).bodies.find(a=>a.team==='enemy');
if(resident){const a=w.actors.find(a=>a.defId===resident.monster&&town.isResident(a))!;assert.equal(w.sanctuaryBlocksCombat(p,a),false);}
console.log('PASS owned attack proxies cannot exploit refuge; native residents retain their rules');

const cfg=JSON.parse(canonical(massAdventure()));cfg.settlement.sanctuary=false;
const open=makeSimWorld('warrior',442);new WorldMassRuntime(42,'open-town',cfg).attach(open);
const e=open.createMonster('skeleton_warrior',1,'enemy');e.pos={...open.player.pos};
assert.equal(open.isSafeAt(open.player.pos),false);assert.ok(open.hostileTo(open.player,e));
assert.equal(open.sanctuaryBlocksCombat(open.player,e),false);
const ordinary=makeSimWorld('warrior',443),oe=ordinary.createMonster('skeleton_warrior',1,'enemy');
assert.ok(ordinary.hostileTo(ordinary.player,oe),'ordinary native arena and town training behavior unchanged');
console.log('PASS configurable open combat and non-worldmass behavior remain native');
const saved=serializeCharacter(w),again=makeSimWorld('warrior',444);
assert.ok(again.adoptWorldState(saved.world));again.startWorldMass(saved.world!.worldmass!.state.run.seed,saved.world!.worldmass!);
const intruder=again.createMonster('skeleton_warrior',1,'enemy');intruder.pos={...again.player.pos};
assert.ok(again.isSafeAt(again.player.pos));assert.ok(again.sanctuaryBlocksCombat(intruder,again.player));
assert.ok(again.sanctuaryRetreat(intruder));
console.log('PASS existing expedition Continue inherits native sanctuary safety and ejects old intruders');
restore();
