/** Whole native event births; shared retained fixtures also exercise registry dispatch. */
import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {makeSimWorld} from '../src/sim/arena';import {withSeededRandom} from '../src/core/rng';
import {massDormancyPins} from '../src/worldmass/dormancy';
import {archive,originalNames,originalValues,fixtures,run} from './nativeRuntimeFixture';
const lane=process.argv.find(a=>a.startsWith('--runtime-birth-lane='))?.slice('--runtime-birth-lane='.length);
if(lane){assert(['archive','current','local'].includes(lane));const digest=createHash('sha256');let count=0,bytes=0,bodies=0,draws=0,partialErrors=0;digest.update('[');bytes++;
const append=(out:any)=>{const text=(count?',':'')+JSON.stringify(out);digest.update(text);bytes+=Buffer.byteLength(text);count++;bodies+=out.bodies;draws+=out.drawCount;if(out.error)partialErrors++;};
const methods=["placeAscentGeyser","spawnWarband","spawnEpicenter","materializeCrusade","spawnHellCourt","spawnHellMarshal","materializeWorldBossFight","materializeContagion","materializeDeepwinter","materializeInfestation","materializeBrood","materializeSwarmWake","materializeCandle","materializeStarfall","materializeMycelia","placeHoldfast","materializeUnsealing","placeHuntContent","placeFractureContent","placeFractureRiftContent","placeRitualSite","placeAmalgamation","placeAmalgamMiniboss","materializeObserver","springVendettaAmbush","placeCaravanReturn"];
for(const f of fixtures)for(const method of [...methods,'ventGeyser']){
 const variants=method==='materializeInfestation'?['farmland']:method==='materializeCandle'?['candle']:method==='materializeUnsealing'?['tomb','canopic']:method==='placeAmalgamation'?['native','amalgam-boss']:['native'];
 const noFactory=['placeAscentGeyser','placeFractureContent','placeFractureRiftContent','ventGeyser'].includes(method);
 for(const mechanism of variants)for(const kind of noFactory?['repeat','terrain-failure']:['repeat','factory-failure']){const out=run(f,lane,{method,kind,mechanism});if(kind==='repeat')assert.equal(out.error,undefined,method);else assert(out.error,method+' reached partial failure');if(!noFactory)assert(out.bodies>0,method+' actual native body');append(out);}
}
digest.update(']');bytes++;console.log('NATIVE_RUNTIME_BIRTH_COLD='+JSON.stringify({count,bytes,bodies,draws,partialErrors,sha256:digest.digest('hex')}));
}else{
 const norm=(s:string)=>ts.transpileModule(s,{compilerOptions:{target:99,module:99,removeComments:true}}).outputText;
 const core=ts.createSourceFile('core.ts',fs.readFileSync(new URL('../src/engine/nativeSceneRuntimeBirth.ts',import.meta.url),'utf8'),99,true);
 for(const r of archive.methods){const original=ts.createSourceFile('old.ts','class Old{'+r.source+'}',99,true),m=(original.statements[0] as ts.ClassDeclaration).members[0] as ts.MethodDeclaration,f=core.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='birth'+r.name[0].toUpperCase()+r.name.slice(1)) as ts.FunctionDeclaration;assert(f?.body);const restored=f.body.getText(core).replaceAll('nativeHost.','this.').replace(/\(0,\s*sources\.(\w+)\)/g,'$1').replace(/\bsources\.(\w+)/g,'$1');assert.equal(norm(restored),norm(m.body!.getText(original)),r.name+' complete original body');assert.equal(norm(f.parameters.slice(2).map(p=>p.getText(core)).join(',')),norm(m.parameters.map(p=>p.getText(original)).join(',')),r.name+' original parameters/defaults');}
 withSeededRandom(997,()=>{const w:any=makeSimWorld('warrior',997),keys=Object.keys(w),host=w.nativeRuntimeBirthHost(),src=w.nativeRuntimeBirthSources();assert.equal(w.nativeRuntimeBirthHost(),host);assert.equal(w.nativeRuntimeBirthSources(),src);assert(Object.isFrozen(host)&&Object.isFrozen(src));assert.deepEqual(Object.keys(w),keys);for(const key of ['nativeRuntimeBirthView','nativeRuntimeBirthSourceView'])assert.equal(Object.getOwnPropertyDescriptor(w,key)?.enumerable,false);
  for(let i=0;i<originalNames.length;i++)assert.equal(src[originalNames[i]],originalValues[i],originalNames[i]+' exact lexical source');
  const own=new Map([['birth-sentinel',w.createMonster('zombie',10,'enemy')]]);assert.equal(massDormancyPins(w,own).size,0);
  for(const key of ["sim","inCave","player","clampPos","arena","zoneEntry","clearTransitSpot","ventGeyser","ledger","materializedHosts","zone","warbandEntryPoint","createMonster","weightedPick","promoteRarity","actors","warbandDestination","warbandMarches","flashes","text","compassFrom","materializedEpicenters","farPoint","notice","materializedCrusades","crusadeWorksAt","materializedHellWar","materializedWorldBoss","wbBoss","doodads","wbBossKey","materializedContagion","infectActorWith","spawnPatientZero","freezeStandingWater","snowCover","snowFloor","fogEnsure","materializedDeepwinter","tracks","materializedInfestation","materializedBroods","materializedSwarmWake","materializedCandle","materializedStarfall","materializedMycelia","exits","materializedHoldfasts","holdfastSite","materializedUnsealing","findUnsealingSpot","unsealingSite","markDoodadsChanged","spawnHuntBeast","huntFootprint","materializedFractures","fractureRng","manifest","walk","fractureRun","beginFissure","bearingOf","fractureRifts","materializedRituals","ritualSite","materializedAmalgam","amalgamSite","riseAmalgamation","materializedAmalgamMobs","materializedObservers","materializedWrits","spawnEventActor","clampNear","hasNpcRole","grounds","caveEntrances","zoneMap","contagionLeans","graftPart","dwIceArr","dwIceLen","dwIceRev","doodadsRev","fog","currentZoneSeed","materializedHunts","huntBeast","fracturePoint","actorById"]){const descriptor=Object.getOwnPropertyDescriptor(w,key),old=w[key];try{if(typeof old==='function'){const tape:any[]=[];Object.defineProperty(w,key,{configurable:true,value:function(...args:any[]){tape.push([this===w,args]);return 18;}});const selected=host[key];Object.defineProperty(w,key,{configurable:true,value:()=>{throw Error('incorrect late World capability selection');}});assert.equal(selected('receipt',undefined),18);assert.deepEqual(tape,[[true,['receipt',undefined]]]);}else{const value={key};Object.defineProperty(w,key,{configurable:true,writable:true,value});assert.equal(host[key],value);if(["huntFootprint","huntBeast","fractureRng","fractureRun","ritualSite","holdfastSite","unsealingSite","amalgamSite","dwIceArr","dwIceLen","dwIceRev","snowCover","snowFloor","wbBoss","wbBossKey","fog"].includes(key)){const write={key,write:true};host[key]=write;assert.equal(w[key],write);}}}finally{if(descriptor)Object.defineProperty(w,key,descriptor);else delete w[key];}}
 });
 const receipts:any[]=[];for(const mode of ['archive','current','local']){const child=spawnSync(process.execPath,['node_modules/tsx/dist/cli.mjs',fileURLToPath(import.meta.url),'--runtime-birth-lane='+mode],{encoding:'utf8',maxBuffer:4*1024*1024,timeout:180000});assert.equal(child.status,0,mode+' '+String(child.error??'')+' '+child.stderr.slice(-3000)+' '+child.stdout.slice(-1500));const line=child.stdout.split(/\r?\n/).find(s=>s.startsWith('NATIVE_RUNTIME_BIRTH_COLD='));assert(line);receipts.push(JSON.parse(line.slice('NATIVE_RUNTIME_BIRTH_COLD='.length)));}
 assert.deepEqual(receipts[1],receipts[0],'current World complete original output');assert.deepEqual(receipts[2],receipts[0],'local complete original output');console.log('PASS native runtime births',receipts[0]);
}
