import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { TUTORIAL_FACTIONS } from '../src/data/commanders';
import { ORACLE_RESCUED, ORACLE_RESCUE } from '../src/data/oracle';
import { FEATURE, deserializeAccount, serializeAccount } from '../src/meta/account';
import { allUnlockables, isUnlockVisible } from '../src/meta/unlocks';
import { QUESTS } from '../src/quests/defs';
import { revengeCommanderId } from '../src/quests/revenge';
import { serializeCharacter, applySavedCharacter } from '../src/meta/character';
import { powerProgressionOpen, odysseyMilestoneKey } from '../src/data/powerProgression';
import { ODYSSEY_TUTORIAL_RELEASE } from '../src/data/odyssey';
import { forgeItem } from '../src/engine/itemgen';
import { RELIQUARY_LESSON } from '../src/quests/reliquary';
import { World } from '../src/engine/world';

let passed = 0;
const pass = (s: string) => { passed++; console.log('PASS ' + s); };
const fresh = (faction = 'goblin') => {
  const w = makeSimWorld('warrior', 8017);
  w.account.ledger = { [`tutorial_faction:${faction}`]: 1 };
  w.loadZone('lastlight'); w.odyssey.update(); w.player.invulnerable = true;
  return w;
};
const bodies = (w: World) => w.actors.filter(a => a.defId === ORACLE_RESCUE.npc && !a.dead);
for (const f of TUTORIAL_FACTIONS) {
  const w = fresh(f.id), id = revengeCommanderId(f.id), q = QUESTS[id];
  assert(!bodies(w).length);
  assert(!w.account.features.has(FEATURE.RELIQUARY));
  assert(w.activeQuests.some(a => a.questId === id));
  w.loadZone(`quest_${id}`); w.questRescues.update();
  assert.equal(bodies(w).length, 1); assert.equal(bodies(w)[0].look, ORACLE_RESCUE.captiveLook);
  const boss = w.actors.find(a => a.defId === f.commander)!; assert(boss);
  w.questRescues.free(q); assert(!w.account.ledger[ORACLE_RESCUED]);
  w.loadZone('lastlight'); w.loadZone(`quest_${id}`); w.questRescues.update();
  assert.equal(bodies(w).length, 1, 'zone re-entry must not clone the captive');
  for (const a of [...w.actors]) if (a.team === 'enemy' && !a.dead && !a.invulnerable) w.kill(a, false, w.player);
  w.update(1 / 60); w.questRescues.update();
  assert(w.completedObjectives.has(w.zone.id));
  assert.equal(w.account.ledger[ORACLE_RESCUED], 1);
  assert(ORACLE_RESCUE.features.every(flag => w.account.features.has(flag)));
  assert.equal(bodies(w)[0].look, ORACLE_RESCUE.freeLook);
  assert(!powerProgressionOpen(w.account.ledger, 'vocations'));
  assert(!powerProgressionOpen(w.account.ledger, 'awakening'));
  assert(!w.claimQuestReward(id, 'hearth'), 'field body never pays a home reward');
  const relic = forgeItem({ ilvl: 1, baseId: 'relic_charm', rarity: 'magic', affixes: [{ id: 'relic_life' }], quality: 1 })!;
  const n = w.drops.length; w.dropGearAt(w.player.pos, relic); assert.equal(w.drops.length, n + 1);
  const save = JSON.parse(JSON.stringify(serializeCharacter(w)));
  const restored = makeSimWorld('warrior', 8017);
  Object.assign(restored.account, deserializeAccount(serializeAccount(w.account))!);
  assert(applySavedCharacter(restored, save)); assert(restored.adoptWorldState(save.world));
  restored.resumeSpawn('exact', save.world.player); restored.questRescues.update();
  assert.equal(bodies(restored).length, 1);
  restored.loadZone('lastlight');
  const oracle = bodies(restored)[0]; assert(oracle); assert.equal(bodies(restored).length, 1);
  restored.player.pos = { x: oracle.pos.x + 15, y: oracle.pos.y };
  assert(restored.nearOracle());
  assert.equal(restored.questRewardOffers().find(r => r.questId === id)?.choices.length, 3);
  restored.meta.items.length = 0;
  assert(restored.claimQuestReward(id, 'hearth')); assert(!restored.claimQuestReward(id, 'hearth'));
  const reward = restored.meta.items.find(i => i.baseId === 'relic_charm')!; assert(reward);
  restored.containerPlace(restored.localSeat, 'reliquary', reward.uid);
  assert.equal(restored.account.ledger[RELIQUARY_LESSON], 1);
  const next = makeSimWorld('warrior', 8199); Object.assign(next.account, deserializeAccount(serializeAccount(restored.account))!);
  next.loadZone('lastlight'); next.odyssey.update();
  assert.equal(bodies(next).length, 1);
  assert(!next.activeQuests.some(a => a.questId.startsWith('revenge_')));
  pass(`${f.id}: captivity, actual objective kill, immediate services, save, home reward, seat and next life`);
}

const old = fresh(); old.account.ledger.revenge_taken = 1; old.questRescues.reconcile();
assert.equal(old.account.ledger[ORACLE_RESCUED], 1); assert(old.account.features.has(FEATURE.RELIQUARY));
const pending = fresh(); pending.account.ledger[ODYSSEY_TUTORIAL_RELEASE] = 1;
pending.activeQuests = pending.activeQuests.filter(a => !a.questId.startsWith('revenge_'));
pending.odyssey.update(); assert(pending.activeQuests.some(a => a.questId === revengeCommanderId('goblin')));
const unearned = fresh(); unearned.account.ledger.crafts_unlocked = 500;
unearned.account.ledger[odysseyMilestoneKey(2)] = 1; unearned.questRescues.reconcile();
assert(!unearned.account.ledger[ORACLE_RESCUED]);
assert(!isUnlockVisible(unearned.account, allUnlockables().find(r => r.id === 'feat_oracle_stone')!));
unearned.account.features.add(FEATURE.ORACLE_STONE); unearned.loadZone('lastlight');
assert(!bodies(unearned).length, 'legacy stone ownership never invents a rescued person');
const sealed = fresh(); sealed.metaProgressionActive = () => false;
sealed.account.ledger.revenge_taken = 1; sealed.questRescues.reconcile(); assert(!sealed.account.ledger[ORACLE_RESCUED]);
pass('legacy victory migrates, initialized campaigns gain missing lead, and unrelated progress never synthesizes rescue');
console.log(`${passed} Oracle rescue scenarios passed`);
