import assert from 'node:assert/strict';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import ts from 'typescript';
import * as mathSource from '../src/core/math';
import * as skillSource from '../src/engine/skills';
import {MONSTERS} from '../src/data/monsters';
import {lightwellOf} from '../src/engine/lightwells';
import * as throngSource from '../src/engine/throng';
import * as geyserSource from '../src/engine/geysers';
import {substituteThrongKind} from '../src/engine/fieldgrants';
import {LITE_CFG,resolveLiteKind} from '../src/engine/lite';
import {makeSimWorld} from '../src/sim/arena';
import {World,NAV_CFG} from '../src/engine/world';
import {Actor,resetActorIdCounter} from '../src/engine/actor';
import {Rng,withSeededRandom} from '../src/core/rng';
import {GridWalkField} from '../src/world/gridWalk';
import {captureNativeActorState,massDormancyPins} from '../src/worldmass/dormancy';
import {NativeAreaSceneGeometry} from '../src/worldmass/nativeAreaSceneGeometry';
import {NativeAreaScenePopulation} from '../src/worldmass/nativeAreaScenePopulation';
import {scenePartyScaleCount,applyScenePartyScale} from '../src/engine/nativeScenePopulation';
import {hullOf} from '../src/world/shape';
import {clearSeaMemo} from '../src/world/seas';
import {TILESETS} from '../src/data/tilesets';
import {SKILLS} from '../src/data/skills';
import {makeSkillInstance} from '../src/engine/skills';
import {throngPocketKey} from '../src/engine/throng';
import {LIGHTWELLS} from '../src/engine/lightwells';
import {rollGeyserField,anchorVent} from '../src/engine/geysers';
import {radianceCondHeld} from '../src/world/radiance';
import {skyOf} from '../src/data/zones';
import {NativeAreaSceneEcology,freshSceneEcologyState} from '../src/worldmass/nativeAreaSceneEcology';
// Complete original leaf sources pinned at native World commit67060b28; no runtime Git or ignored inputs.
const archiveBytes=gunzipSync(Buffer.from('H4sIAAAAAAAACu1dfXPcttH/P59i7elYvJqm9eK3UJY1iqPGmtiWR1LjtnrUFHfE6VjxQBbA6XSRNdMP0U/YT9Jn8UICIO90it2mmZ4nEx0JYAEsFruLxQ/g9VcA96clL7LjEdl8+ux+CvcpeZY9yYZP6frGs0H/ydZ6tp5tbtHBc0K2nj55srk1fPFki9DN50+fbH39fIv2s40XhJAtQjZeDPtP6P0YiY6pHJWZuJ/C9VcAAPf7ZSlPRrxk5/W7OhtWW/H8kkgKTb6oKnORwg90sHl61kvhsswzuP4/hgUHJRMSCBuMSi5gBxidwjtSvRSS5+w8hmvImZApHF/kRXHAhCRsQLdBVHSQgiZ/XNHBNlxQWlGewt5AlhxuXkW9bV3DsOQQ6WoEJRLKIchRLhJ8ED3bDi+frjRWtcCNLmFrEocswqIJwYoSge0SPYcOQD6EyPQoGRERIbEko8Mkz3o97LHM2YRuw+PHMMy5adeaMFyAac6ET0y11zShnPAB1TR1A3uJKMc04rDzCnhykbMMdnZ2YK0qBxdUrvlNA8vqRFDpNiz2Oh3X7Gy6CjeWo/jvxv40P8wfbO29uor8J9oDTuWEs47BUCOaIXdPkySxhS7oTES9s0SUXEZu49tDY1sJN7BT9+ucysiQ7t3b9gtLco4yppJfl0zSK3lCzjUze0FeeiU5gR1VHcrcuzLrzjjLaZG9mxSwY5qTiBGlUjVkTQ/aHzHLWqzqjzXlkApn50b6j9h5FOkhH0w4p0z+qWT0mNIM/gwnb44O33/34+vffZcIUsge/NmKJvbpmBRN53vw6tUrWG8qKqgELRSwA+veayWGR+U0hX1s3EC+PHGk7aiconigaKW1XMHNK/gEE5bRYc5o1ib3hiCvh6QQdLtjjvFyWk/FuaLdmla8nGoRv+eKeDOnmty6lpFqBJYajHAU1dSoGw2fPiHjE0avZNSDl07Gbb/ee5ZDPbiuuaUpb7vdHRGx3cwN2wqGOdl5kjOpelBRjmN6un4Wg/u8ceZOMcUsNWhqvKCCl8C2oXr4MDbj+PBhMLkVN8c5M4r3g8oVcVSkqINjO+lUtZZKjK3WDE/G2F7KMYeVazvLYvClv60DNKscToV86Jdsglx6R+QoGZOraD3Wv3k5YVk0b/robohgAvVu45Wq7Uvxy/aqYZod9S/BOfXnRhlc0DY2m6EtXRnJlZFcGcmVkVwZyZWRXBnJwEhWhJMxlZQLtex01phNHjmrKKbikrN5W+QM326tP93crF+OSiHvp3D6la3/vjJ+dSmk5k5BNyHQQW5SyLj7JulM/b3ROQPKC9fVbT0QGP64Zfh79YNVVadn/gL8nJOhFI4mP2nVYodGmypTIikoO5cj2FXmSY2x0GViSJJEZzqDFNyk7WW8nV+0Rb5oLcXjtsy1WN4hgFsvNloC6EtGS34WCkdrmhoOsfMUbaaesXaa1DM3BetJ8ruat1hXoF+kwCbjPs7lEREpRoAKSlgM9bRvKrLTvyni+aZxl0er6uqMH40o4WiwlarKmaTY/uOqlJHWUEpZOW6Bbm7CKRmMuhKqkktSvC4o4VbIdEXDkl94LsiX8EGsnnuo9Xw+nhSR8UEewkYM61df063nz7/ufx36K7pRg2KC7HVtxoZnM7DVtV01uWu7ap83znrw23pcasPx+DEcMgoZHeQiL5kyInJEYToqC1rr+ZIBgeP9D3tHeyf7OMiUjBN4T3M5orwmJDlhYjyRRCIlVnLIpQDSFxS9jgFhMC4vqSJv+q8GVkDJlY8tErfb45JXoyPPJZwzGCHn//Kba8P8m/Q317qqm1TR+0vP561eKoCY9IXM5UQaNfR9zrLIsWauDYsh6uE6w7bPeE6xHWYhicT0liXHhHiO4x13+Ng9b/WGhl1owy7gpRWKbRCeQbdLSeSaEgtO2DmtfYwPB/Bb2Az97szP/KxryogBkZLysOgFnal52aik7+lMj9NPJaNqUVX7D1aaRENF+ZXooH765LrBrwuSj2mmVo4XdNbr8G4Dt+XNRFxEOJoxXNJB1LgZSsSSKzv7BqWICDvHuZDFJnFmE0XO6sQe6sPKdinFnsZAhsOc5XKWNjqvWRIutcpfqbKVKlupspUq+3WpMt9h/je6m/8ZT3PpBeSTFy8WLCBd9b3kchElqb3kNDLSva5EceheVQZ5llw5KPHSw9zBzqo0AxpDWUmxm7qis2vzbYOUxa5l+TbInHLn0cpWnR9urHOvQ9OfgE2Kws51NXPeHb4/Ptk/Oj6tG3Vm46Yqs6frRhNxYY3ogFMi6TtdytV0rolppnFBL2nRi2GNMjqerVmJR4pmxn7MC1QjqvuJ7Qrs7jbsagzOyZt9ON57t//o+OTw6I/wdu9jCkQ3b0oJF8pCCFnyGeQSG59RJmiGVijKpajpjJUsrQn459//AQRQWNcEXOYDmY9jRcTqbQLjUtL/z4nuxbYZGwGC0qyxXiMK58qg9oCwTFskrFOOiNTNWRNQThkMi7LkicuCXJln3Xn1sLtbB0pVjooIkV9SZD+vlZhKmTBJ+DmVpF90JefsclIwyucks/KbcsLkzE9C2dCNqaWw5w5WralNo5tsLQJSFipkWoc+PUL7V1XOqdirnTOZjyk81ESlLDwWlKKWvoKMqw+liFBVV6VIrtQcSma9WOflJMsnIm5qRcWHzgNPtZzUSlfRU9sMIqkmYhRhchAEwVe3xFdWs2k1m1az6WfPJt/V+Q9ayLZT4trKDudkc6sdXHScEHciL3RB8rH3bMfAfaf52O2FIBDsbS7p7XAxzBVldJgCukbf0qHvQHaG/qqyLKx0FLmknuIaEM5zmuEIlFOGMmD5m9FhM2bbUBU5FTYVbk7PYAdOz8I1Sa7XJDm8VNUmE0Gzbci9VYnSriqVFPklPc3P0N/Xb1QbTvOzDhffLDHcnuDCTJyqgugHn+ZnZ95a4qJn+6flt+6jV1dsu3qRqB+x7avKpX5jG33PHnQqp7gBricKp4wkU6Pa9dPIm0p1k13WeSkH2dU7UiUDjEVErbLvyNWRs+dav/+GErkn55U65BnlYl7qH6q9waCL6PcISJhX6gMvUel/M8nOvW3gJoOxAl0d/WbCeTntTvs4ouz1hH7LyZwMr8uiZLNjStm8th3Rc8peF+Xgoqthb4g44WRcKY3v7io3XM6ZyXFcYURhBw6Y1jTexFGgjh0UnUSO6Ji6U6um9QNluNvndQUFEwvvJmJK+Nhux7SW7cFW/pxox9uDk30n8BTs1bc3yvWejqrY28Q0rsMP++9P4Hh/7wQiVDXHmPGonCqUC6xdUibFWg89CiSnjbcy5XsnaOM9cqgk1wSc05mgHFRRyAUyjHJOM6iI2sot5Xcqh0B8CjX5shJYKT1yuOzMYEZlD0omSxVMQocB+00zKAijylexWhJZf6zapjwYlvnUKorz8P3hyZuD99/BiHLcsCqVo/Lh8MAEtZSPI1RV9IoMJIgRqWji7+lzyx4FlzEsguu2EGgdxMtpb9tB77R2+Q3WwMUTRA7yYHcXNtw9YKvj7XzzAAL6bQMQMM8+QMAM/evD998enBwcvt//Fj4c/v4okIDpiDIceQblRD4qh49G5YQrMRAyLwqPHC+LQrNNBw4V25Tjh6J1rFJsi9Wom0HUXF8THrFM6QLCMdcABQfHc0SLDAOFrJQx0EvKZ6pSGJGqokz0YuhPkCsTLoCVHr1+meVUoCRtq+Hm9JyXUzkCMaW0Ak5yQbWbLPMMQ5+UqSfsr0doUI6pSOBACnSGcmzagFQq2qnbPCW5BCK1y03GFBiR6Kj20REmfJa0hp4qR99Rdix7Q4tMDaYaAGfYNA5nwpWK8vEx3UAGw3EFZQgADHcIrNcKB+u2QXX/ZUdA3a0mhLEgvqsWUfXgy2ctoUf73x0dfjx5Y1c1HDX9oz4lyvvj5XTNihVwOqboqAjVmYCW7udDJTEodflPFIiW1wGpIOJUlMWlWhThPjYrDYpLj+o///6PgF6HBMMwv8JHJfijsshEL3FLqaFBA/Vow+tpV3CXhWFdl5k6uIvsXBzbdctkXokn4fC1gruNrsPgbCdMCrwY+kF2Fbpph0M11vVioIu6LfoS1udWgvmQcTvIup7mYeB17DMx4TRS0CRD0sR2Y2DdvaJFFiAq1Zgq86EMj1YVRnWoeW23Rny10PChjyxYGG7uz+ocnTHnTvaWFWVulw8ryvZk1L9Cel2dU26qqMiURTUzFJFdbGJqm9i8nNUvZzGs438+0dCZPTVkz7SrvB7joLzagXXYxV+pGid8bkkwNPrLWWC3xnpO2ba3eVpdnCWLSc4phOuQhw9buW/8F96j8+D81BxXLXjwQCk0wlg5YQMa9KCZ6Mp1UHMdf710UMXGM9QpqAE4YVn0aGM9ho11d6xvgBaCqsrRe3jwAJRI2yYoE7a4OZ0OeO2wtGzPHNhu3Sm9ooABbk2ZBZjty6Bjh4orEKTJeTpoFnF2W0nBc3ecgMQ3swNtFdUiLthBMvk/fbK7bhklWYdGcTIbALbGQAvYedX0Vewm2snHoIwJQSlXD9m1hnwVToZGw6lM2ES1qOzatFpGYerC/qp2oZp0zUI0gMde1NEfjB6qGcdaBDSUBjPsUYGkDjX25JnRY06+LmX25FlAfEk9dpv2cpvnqzC3QY4G27CbW2ozUjnFqLXuBEBYBVRWAZVVQGUVUFkFVBxqq4DKKqCyCqiE1a8CKquAyiqgsgqorAIq6t8qoLIKqKwCKv/LARUfGzQfybIsvnhjfXN9AYQHOeGicGol60FzMLTQlUtHD8IUjBqE73TEIHyrIwXhWxUhaFdXFK2cXlSglajVbaslOhgQvnbVUJjWhADClGbpH6Y0y/4We/zlfphsF29Lor1dr919Pw843sz2bn5pX6Y1UGqyuG9bJ5trLdkN4XLq7QRxOVrIiwP26gigUeEq6NfWXiaQhSdHPA2G+guzBzhCg87LsysvxpLRIR4csshWRenMy2GOwGDGXTB++1vTBqz5NhTrHz78ePx67+1+D1IXJat7pIjvBu6OPY6cNq67VcqOXQvKKEOqsmy3cpioXt1OL0F7sAYE2TYDidSi+y5nOlj1sg5WeQa+O/wVeEgLImC6cTmL5uUx7Qya0zTY9xO6REVYUYmR+wFs0wrG/FD3Sg5XcviLyGHLQ2iUZdsp0LqzA9n79Ytnt7gF3QY+hPZ2OgzzvIDljeJcG2Is0UIgsOPeXTVntmb2Z68+7WUlxTD7Sq8iHzyAWf3rCl7aZQB6QW8mRZFMdZZ2wsiO+oMHEN1TiVNSXNTH9fAhycVHUlwgpj66imFmzi3OVzT/XY3zpa+LvW0hNNzuck43FuHL67a70oLNnC8enhNzq5CE4ZsU3Ah0HcxxjgpimMJC8wekckTK91IaJa1cxPYeYh3DUDFFM+kfP4Y9LyyO69RmPQx9BNyPqMAFhxdJLsgUg9JMBY9rWrkEhqFqIOKCZmqxrGpTAe1pLkflRGJUU98JY8LPg3JSZKYczwWtqZEhHqsOwvG4+ZHA/lVV5INc71EJHZ/H+9W8E8rcMAK7Y37vaFUMu1qpa1bt7sL1TX0MPNX95zbJy1ezBrAMpI5lde3uPVW6NraPNj1L2hXRqyMhbka9U6Q7EO6/+BTbBD+owAY2IwwRJvWPmRIpN/6la9xtwqWXZo/Jhky9Ljs9bkSm0vzZqeMyrqjh5tsj7Arujuk4tj4ExUroq3VSCnaPDMblRI7gQG+mjAm/UDspNTUhcf9qVk7wZBNKDobIc72voePfmDZV0kWvJOXjnBFJbZRajZPqb8/hXUGY1Au2qLroYhj2Srf0e8fJMANd3XaObTVLV7N0NUv/62ZpcBXAZ9jl5R3ijWfPFl3kNtfNnRNlauSpldJwa74bU0d05sZK6p1aPKKq+YOv3Lsi236uGj4sUM+y4OAmpiViws+pv1BVPqMacI2uOMYsUW83UVH/3V29HdxThRoadS3uZrGtGInh6g4xBl5nbvOHf52d8GV6/qDdxXt+tnAN53TSlcGwuYtPXNagluWOXtbZo86TlgaF1QKqLINiMlcO2eK6d8KzHwh5MUEKxPcN9f+VOm5AT949uUvgFX8GKsp9bmxBGy7VBkthF1qbVXfC5+giU8KkG73wmRAvi9lpyD5+DN/mQuZsYCwsnmvHI+wKV8VlTgoQo8lwWFCINDwGwQsWHhPr8/IWQdNAE8zeDO4DIKjENHNMqij6MYZcXR2UB/CyAPaJfQ0Rn5bwX/H2RwRemP6ux7ouKyaPYAMeuRXUVxiP0T1QeU/zs+36V/3yr/XLv+JLOa7CkM/PwNgsQNjcteeXDTtPbePPWt20ABw8C39pN7X0j1mbKXfF0XRjTpZGnNwdb3Ib2iR0zPzSt+BNPgNtshzW5MsiTbpwJu3ufGHQyJ0hI/8WwMiXgossQnYshor8DKDI8jCRW1Eh3j3RS4BDviA05HOBIXeChdzl0wcr12Pleqxcj5XrsXI9Vq6H0+eV67FyPUIufIbr4Ud5lsboPV+/DaPXhQozfkgYYPxM4NiXAojdJWLaApO1EHnzN3ydcOrt+71epLoJH3dtY2stt+vg0NrxrP5FDZZxwv9qA8GJd7uOYv+i0w3MUvi2LDOCU/RaX/+GdlFtwcegQTApbGzF5j7b/gWeH9FFTtfw3doZ3Li+bKbSjPzWNkEl4a6ALipej9BQZe0zjQYliZoAUUZL7aP9z3Ij+IzM3QRreSXxdFG01/TQu9+31bN5WNhb4BRqG2NJMIXaQtPs0983eWthssf6U2Lh1k0ni4w0NBs5sfnwGGKd7BvjSdXQCyeKbq8Cflu3K7jyz0vaacwAyljj39TeNDakdZ08rm42nz71LpcfkKrXa243x01b850YtX/bnhj4us7+t0lO5TFyTRWxjx3FbJLTxGJ8ZGaGKty86CjeJDYXsVtu2k1Lt5R7TKsuYUekfpHlQk54n2a/ZzIvUvSPyGCg/qI3oX70cy5HInUcJ+0lpHrRob46hUs9+2zsbDgj7QawmtBVuKO4lLpaycD/lAz4SvozdNNnqKW2rm8ksEvjP7sNo2l9qU4FTqQkgxH6fh8pHp5YqMGDzOH+nTpjpY1IEB9wIklZ/aVBY42COziyZEqLYu4RIg16LvLzkcR8eBIg8aHDymnI6HDO0So8FKUCagHI+hp0zcadmOLg2LwxjMmV+5hnKTx8qBGRtCiO6d/gZtvpu1pBNeuces2BFPoTLmR3fRumoo071uB88NPk6N3ityyGrK8G8dc2iD9rTbnxdH0hnqXDXTTduMWD7NQ0LtSgU8t4gIsUvmsejyjJgm813B5uH86/aH6aY/xniF/sUPQ/5iwrp9HQnIHAm6iDb9qom8iHGuzh30I+zRs42rUKpqYNFQyC5iyReLpiPdW/12OQG2n9fljyAVq1e/cM+d/hixgwlq5PXdRGTYXpsCWdx0OcXgbNMQYTW2AqX2/qNYmmOnolFUf2ECEYqQ+0NCxJ5Lppy21u02pcfvFxuU0jdE+vlo54uvliY9G3ZzriS+oi925noz7+16kAmjPUeeaA5u318w1Gyz/00Jy/FskQTzYR3JUhSa4PO+e3gsV+Np3g+53ZfERhqw9tT27z+cYiT67z6vuvDG/vqznTeG8mWJaaHyngroK9HM1U3Yr7OY5euIGIMVdbTB3uSfXf+tyxne/48h2pTo9P9o5OfvzT4fv9pj7/G0Np8MJsYh5Tab43j1+Nr4uiSKX6r9cYwxUrPMJIS9jVQn8X4D6nJCtZMVOxCFOj9q7LwqmuCUs6h06FXgrgz5C8Pvucmh8p4Ccv1H1qY3JB9/BdNI877UrNcaogcNKkmGa/I9VL+ykILXWvgh6ow1UBmfqyNjejOXcdZNVvndrs2qW7NnNMOzxhpd52ELlu1k3bzbppG/S3Rg4y5xsVE71ItHf8hRXrk+BBvc0Fcj579RIn4CxeC7UsU/3T5GF0q3UBnVfUrMNS79ENMHSJrQ2/haOjX6cQmSioi+ntouNFygNiblqDOO2i4pxyD2g0Kc5M7uahcyA+IBLckucWco4FBoU6Ls/zpkFwajCcEfMv1nOp1HsrQXH73kefdyoIdUgtdR7westpI+ejRsZxS3OiFkbN+byGh+p0W6r/poBn8X6H6t96yDva5bC5rYWuPWxhfetFpazvn9Y/bbw97JtdEjiMsYsdNYa1jVIuG2EOTPi+PWBs4M5C1keOsWzyQpf+6uarfwGOr+PXeYwAAA==','base64'));
assert.equal(createHash('sha256').update(archiveBytes).digest('hex'),'343d43a2b42a6360d55b9ffea2be480df6c94434e0f3995363b2708249a614a0');
const archive: {methods:Record<string,{parameters:string;type:string;body:string}>}=JSON.parse(archiveBytes.toString('utf8'));
const scope={Actor,Rng,MONSTERS,lightwellOf,substituteThrongKind,LITE_CFG,resolveLiteKind,XP_SCALE:.8,rand:mathSource.rand,vec:mathSource.vec,
 instanceMods:skillSource.instanceMods,instanceThrongSources:skillSource.instanceThrongSources,skillContextTags:skillSource.skillContextTags,
 THRONG_CFG:throngSource.THRONG_CFG,throngPocketKey:throngSource.throngPocketKey,throngSkillSalt:throngSource.throngSkillSalt,throngSpecsOn:throngSource.throngSpecsOn,
 fieldSurgeWindow:geyserSource.fieldSurgeWindow,nextSurgeAfter:geyserSource.nextSurgeAfter};
const originals=Object.fromEntries(Object.entries(archive.methods).map(([name,row])=>{
 const js=ts.transpileModule('function original('+row.parameters+'):'+row.type+' '+row.body+'; original;', {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
 return [name, new Function(...Object.keys(scope),js.replace(/original;\s*$/,'return original;'))(...Object.values(scope))];
}));
const fixtures = JSON.parse(gunzipSync(Buffer.from('H4sIAAAAAAAACu29bW/byJIv/lUWylsP/11VXV3dfnORmZ2z9wB7/vc8LLAvBoFBS3SsjSx5JTmenEG++8WvSUok9WjHTjJ7h4ASmSL7oaq6qroeun75bbRcPI4ufxutqmoyukyJLkaz8rqajS5HN4tltVqPLkbrcvm+WuOpX0eXP6hejD6NLim4zxejj+VyWs7Xo0t3Mbqbztf/yM2wD9GRkaOL0XQyuhy9r+ZXkRxpGF2MVouH5bj63+XqFp1MbmRsUgUfJjc2cTS+kUhu4vy1S+VEbEI6TjdGIVST65Io3IR4YxbGnsvSeHQxuplWs8mP08Vd1R30snz81+p+fTu6dIUQp0SO2aKIJ/H5559m07tyXWFe6+ruvlqW64dlhefZ2FGUJFGETf3F6G4xXbW/GkvwjhTj9OrlYvQ4nU3m1WqFX51zGp1nilFMg6jh9XI5XU8xQHcxuq3KZT0uJ8R6Mapm1cdyPV3Mcc8zUXCSRCVY8uliNJ5+nI5Hl/T5YnRTjnuTvB7OusHH/1/m29fLabn8YTUvl7NqAshP/5mn+zi69OwwlNGlaJTPF6PVbXmPV5bVGO3Myk+Lh/V/fMr3JtPVejkdr1eji9Hi+r+q8Xr6Efcfy48V7r2vFmg1D+YYzMdHAD4EcQ+oRwC4A70OvD5fjGaLcTnL83qYzq/++6Fcrqslxlz9Ol2vRpe//DZaL0aXo1m5Ws+m72/XGUoTvFGNPl80v/6v7d3H0cWoBL0XQS9G6+msWmFptBjYvDJeLlar5aKcrLottu/Gz+8uRuPF3f1iNcXQ/76YzTCadxej1Xr5MAYcOvdm5XxyVy4/dG5dz6r5ZHR5U85W1cWonM+rX6saVLNFOfnLanRJ3gphn9orAqbl7EOD1Kt/W04n/1nOPvwJywdYXGKp/jYaL2b5bXcB3oCv7C5G42o2G12Kuxh9mM4nGAQam+X3Fg9zNPBYrqvl6N1nzGw2A5Us5iu0OFksJgDEpfDF6H4xXY0u9WI0Lu/u6xFfL6vyQ3k9ayYwvx/XX96Xy+V0lRvBCMqPFdjLql4KzTB+y/evqvl6Wc6xOAjDHn8YXQqeWlb//TBdVnfVPGN7NF7M19Wv68ubxfvRRTOwy34Lm9u35fJjtVpflXfX1fJ6Mev8lHu4GK3G1bxafmow/M/FPC+H1RpEfjFaV8tlOZ2P3oE1rlbT+fs/VZnifyrvy+vpbLqeVjuDencxmpdYX39drNb/vigzSsrxerFc5blV8+ru09vmb3fRga2vQfRzM4/68c5y/S2DrLNs6/8v/Wd8/XS/mIKPNwTVzKztCBS3XTH3i1UjDDyRq6WBJSr088VwNWE9bB9P9cMsHIukbnNJ+yLkBJEfvLbphWMIhW8f7iyx/vNsUj+fXK/h4AYPRr/3OfOjzyDjh/l48bFaVpP/vF3MqrfLqvx7tbpfzFfTLvbuy/GHHme8rAGLtTwv71e3i3Ur61LF40g+RnaT8STeBM9J0+SaQ3VTOh2XYt5dl5PrikOgm5ubOKboYzXWMAmVjD6D187BN6tMF6A4/L8rY+e1APhTtZxfL8sP1b/8fbG4AV+vPkK2k9uyxub162U5nVSTq/9aPCznFWh6u6ZGWIgfy7zaFyV0g8yCR1jNy3U5+8si87d5VTZiaCsxQC+5/W0TYIG/uIIdiYgFn5iiSZQLV5hSSFGdEoXAIbxrZRaejxf4B7zvYTqbVEuQwOIhDwOEv6HdyTJLjV82BN+s1vHiART+i12QvoMGMJk+4Dl2FxLeZY58u5jm+bbt3pfL8g7U8hmEk+eRqW46f7+diLfkxCSlwInEJX/hCnVRUkpmIpQiUXciwheukN48bpble/CoV5jK6mH+oZpfjWcQr9WyN6mLETC8ulks77JQflg2vPZuulwuls0woHe042upZbfVWqvDA3flPYTdr/ezxTIL5qvdp3/N3OlT/vdxdEmadRECBwFJ5QU6X2Qp/4sr9AKifnC9y312nkihd9m7i9EjyBG/77wNHIGplc0Dw5fz759ruQfIbsTdGf9tJOLul3MbeXexK1+/5peDg6iF/O7/T2z9RCN/dP/9UMA36X345Y+B7BvId0Ef39ka+X9xiX5Pg/hK8vHdd6YpbPTDVjNulEMziy5ydGKcEkP1Y+xPOEqEmcg5OaXkvqJyeL1cQDF7X66r28XDqjpDO+StdrhePuxVDve0ekw73PP409XDPSjt43wfVfyhHr4883+dQe3t53sewEti/jtl+N+NGvTHQIYD+S7o43tdmt98AGczhTPZxHfKH74bhfCb6AYbhXB1/7DsWj05Rvj9nGmU6NEae6dJnDoLPpoE/zSzJ9Sw17Z63szK+YeOVpsohChOTYOy52y6DS4QOU8kLIG+I9MtPGjT+Ye64Zvl4q5njt76Emqr7nKRHYZ3cN3ACzkBoVB0gEXzcufp/Har8+9/VbuvDvptiKN5cTJdZY/Dp87b1H27eXxfpy2G2vfgtPs4LaGbusKnC1dQwCI5NJL2/QPNSbc5rJnoe621z583NKDkfrl4vyzv9vhmP1bLVfbn0kUTl9ANKDjixH6YT6rlY/lptdmbnO/x3nGl7/h2L0br2+ouN9ewp8vfRvflrFrDp/3L6A0xexdHF6M3dC0lITbhDQd1dI1voubY45u3OBYHB9H1tMxBA+FiVM7ub0t8R3zFeJGZy2+jZVWOb0eXUTHe6c16dPmDK0R7XtjaNDGpqvur9o/r7N5cPZZ39/j/fjmdv7+6XyxmtXt2VpW40+mAFB6h3IErxMN1PocD71/L5YfskA8XI7gn4eYv66VEF/xuO46GT9xNM6Aeq+z9u+QNA1lOP1bLq/xz9q3dzBbYQo7euBsq3Tiz/PzgG1L2JHkSy5pVvOGxLzlmH9tqXY4zUb1h9cyuc/Pnyfv8g1ShFAC6HI/ztnT0JpWTKsAvdvdQ9zHha1IwlttydZeH4V10fmPqwTOlVL5q5cvl6I0vpWTOZF1OmhuTPKz1sqqHdK0Y0uc2fqL13p+OpTjmnK0djNkzX3NBvYhb7ioX4IhruM+3aFguFmvET1xdPyyXs5pT7cFJ+9TtdP6++q/ysfMU7T41XtzfT7OD/MhD69vFcn5Tzo93eL0s765n1XWZufuR5h5BXlUOXjny1Lwar8vl1XVV6wM7D64+zT6W86tVeT+AhYANVatqXtsmwLyIEWYzqf4P0Kefe53NytXtFZy697VVsO2o30rNEf321fXj9P1VjsI53HX9ktR9/3me7SwYDvvOcFKnTcD5Cit73cUI704IgmDTArluE9Pxh2p9tVqXsw+9Ce1phWKnlbht5HE6m10trh6nq/vDEMkNdCcStg28ny0WdwO07AfoLmzc/jE16H4sl5NqPyG+Xy4+VlcQ4acRGbb9ymDYp0FXN6F7m5hMl9XV42J2c4oq9o9gUs2v7sr1cjE/NYMD3Vfzq8fbanZ/AvEH8Ha3WMyvbhePs9MQTNv+OwtqVd5fz6pqchp8Xcxv38/y6RpoeB4GF8vrq8eq/PhcCnicThaPZ2KgZSoDEKyXVTlf7yHUvW24vW2AL+0wl70NxO37HeaUYwSvrvNu5nw8dhvAqx+m86v3i+VpXB4YRNvG9A4K1UmMdGGxr5nldP1Qzqanp3QAMZuGoB88icD3jSaHK65uyw9nTIz2jicrh3u4zUngdNp4rJbVgNvsf72z3DrrvcK+7aqm2JNNdLAcB6T6uCyn69tTLM96EIXC+KSAzTaO7MXDNnsdBLd9aN7poP+U+X1PMbZA2RdSR1UnLUTMnCUfRF0ItfsjhiIwk0bniKOy7QvW+1hNEd+7id3b2TIdjwr+nsN3s+r813YrP8Lm+P1y8VjbbrCnjS1t/IgdWbmsg/LmD7PZxZ5/mjDGv1SzydHHPl+MymU1L/dtHXd3juh5lqfaxkshdO5TG41IbhAjuSXlfSGUpyIl94dE7gY+DiMc3213JZ2Q3B1TSzfsMhTmggseYe6cQAO5RwsFm5cUSMyEsEdpLTLic/B8cIklkw52S5nglWO04GDzCk6CYYCHerYUCvbM5IIJhdh2rK6IkWJIHBKl0O/XsQPBKsWoWOS5XylCiimx+SCc1GI41q8PIHxzKjGJRiJtsCBSiHgnwauKqnZ65lhw8AlR/4BGbHsOBUVOPngLYlHd0Y6NtXCmzCTsAiGnoMa+FCl5cmpBKLoBpBXe4+TMoo+UQtOxFhrRNVzOlIidHu3ZcaFmohxSjImbGUfxBXFCEgRua+z2LEVSYhdFgwWLaQNrURXMIWlSF+hYvymlgsmESL0LFK2lZiuCanIxRtLAXUCnQp1LTGxknqTt1heRlIm94xC9xKPdkhMrFLNyot6l2svMSX2BQTgv4iVIF9DsMVBHKfqorIodWe6YCokaHUJ4g8TgjtMWMaVCPIsTs5gscN21N1eQuWQUEfQbe11LoUqR2UuMElyKm649hhujSy6B6I7iOPlQJI0qLhjF5GtYiyNfhECaKLogIl2qFi5cXvXmHCRSu465SOSEJbFECjVpdeKplQuMh5xRVKZ63cbAhfNYIjE59SxN9D7E7SDyfgvzY/MRTUWdHUMiUUOs+Sc5X3Bi8YgcTqrSJx4S8yxGwUfVzXS8SYgBMEzeh8BH+02+SJDQSV3yRloLaa9UcDKOlljMSW+ZMhWKGGcfSJXVOdugkNWCEpEo0oDs6JTJEeg2eI5MlgLXHEIDF8EF9s5b4GCDniMGE9WbqCH3omHF0ZmYJkPwtRwHNUctfArRRacpxnrCCsJJWOjCIcbYW6VWpGCegnfJO3ExbOabH42ckpoPZPH4aklaGHgAIViGfU1KiaxgSw68Mln03J+vF3WWgsWYxG35gxAFjlGSkdNahB5cKpoKTwp2Giwo14s0JcBSOTIL2O1goQRHmiJJILYNE47mknrSpMmbHV2fJOILCzFFc+pC5jAAswXElscUyUg0dbvlUDDQSJJ8BP1ukUs+IuuMzKKqO07QEgsCS4toBFygXknMVvgULZKTKIm133NwKsoQj6QbzkBFsOAEL6gnb3IUvxwlYXKWhMmZc9LwJNZCKK9E79i89XuOSkGTQA4Yxc2cA1aveqfMEpSOU7QlKTgmB42AKTZsWLwVLpH4QKLsnfVpGuTsOHiNUZP3W1Gr5kKQFBKwfZS0OHpovC46MzXntBHywcfCG3Sd4MX6yoVw4cWphkgEnksbmnbJJ++wnEzMjkoeER8KS1EDeVPPoQG180WyGIwo+NTTppgLM/EQbC5FF9RvRLxjcWQhKpFFOd6veVekCMp1IXlrtBowu4LVB/PJs4sc+nzaU5CkCihxTFtO7ZwDE/UUlKPJUQVSzKciWPTmlJJqbKbspXBQQc0HI8/WnzOS5YImC5mPb8V8ouCcI3GUhF06vqQIO7nggrGZT9QoGGJgmeqjEov4gTrlYgTReVV0siEuigxSVxJjFT7KQySaK8wZGKYLSo2MJ/WFBqdsPpLrg1oL54IqxDlTpI1kCoWLyslFA29xemIhKxVgN4hydE4aovZMhSRTpkAQQN35UiGByHMQCuzIOuojGdTQRBrS8U6TFV6jd0iwVRealZS4cDEF8cIpxr5sCFlnVKjkIchmHYVoDDwlz4GOywaOkQvzyXmNLqZGGHKSVETxURPEu8T+VDk6NuCWg9qGmqkw8d4xB8fBOB1fR9EJeCU0BUup0arYixUxOqfBXOIh23DEJqrYQIqPm+kmzxzEMpNzdHS6QhYKkohMZ6zFhqRYFbBnZixE0tDblICmEmH1MkOj3S4i5xhSI0Qx5nRcYWVLvghmqkESWE3Tswf8TSUk8kJp0LOoqFkImqLfYDgUhDwz0mSmxGTZ9ZxzUH9pdshaBEeRGMqxOWppCVs+NS9RwG7aHbYjKpKas+g9S5MKH6HlJSOo5M7H2DwsHMB4vZlpCBpqAEbyhefgjLyo98narfq5ynPD1Ov1G6MnM+8aMWYuIh4lScA2gzWHRtSJtjlruJNpi7/rVFt86+Ta/vKul2z7iyAkJQVJDi0sVqt/VGV7GsDZU2zSDf9eIUYnO84Pu//bMwX25CQeTSzcE1xSzbM392mYHgaT7Mv92x+e3e3uXFI5lqq3Da3e+XEn4Pz0iM5H1rEA8c6Ydn4dBj2dwsjZ+8VDGGlDS050dO5q2e0o5+nP55ts9qdHEGVb7TPZDUn0hZ2koW4gznmxSf1BcZBU0JlcDeYXWKVOUdGRWKPDUU9fAqxzqak7sDMCqgZDehKXZteonmrYdLwcBA9Ea30J+DZ2anEuFcZPFTRPDAbrD/XsBXqEkRFHWEOw9SSHU1QwKKzfZkVk0QavwkuddHEx+nCdLfmjt/+jr59/fPu3n1+jzR9fuNHdC3387TXafIV2+9dr9PHjduwvjc/u9Rq4/bk79tejm1eBzWDsr0M3r9d2b+yvQTevidNXppvXXUuvSTevz8NejW6+hux4pTX76rw3X19C84N5n/t5wdE/m2aeM+4voaMn9XPunH/c+bsH4xdaUy+H2+F4DsP4Zeil6eeMMZ/E7VHYHp7Ts6/OuI7T49eml/P6O80btnM8fL0cvZxHT98XvTyJN+zM69B8X5lensEfdmB5aP28Gr0cx/Ph9bwLy0N4ei16OU4fR347haezeMFwzk+hl2Nw3T/Gff2d/Bwd+Zn08qy2nzjOp8L9CbB9Ci4Pwf7JnxeHy5njfgHYH75eHhYv2s+59PIisDh8/R7ppb5+r/TyPPy+dHtfj17Ob+9g+ztzfM7IXxq3w/EchvHL0cv3o++eew3HdZwevyN62RnXCRr/juhlZ1y/G3rZN+9jfOt7pZfdezvtfpf0cv7nXFh8NXo5+3M+LA7CZmdOzxj6M2D+9ejlOD4OzfnZ8HgxejmFk0Nzfv76ec7a2Tu2Uzg5skaet+6fM+7nzfUUPl7uOkZ7z1lvp/DxgkM/hsMvgP++63n0cug6zSve//mnzWffGLe/fxlfevJ1FIf47af9Y9t8Or+fgPlL08tRHOK3P+8f2+azFyfP6OvJ1x/08ge9POX6n0wvL8fTvzq9PFMXeHJfT75OyL3nfp7YV+86l6YOwehLxn2w73PGfv562A+jLxv3Uf/pWfu4c0Z+YI6vAvMzaP0ove17dv98XhzmJ2nh9Ny71945fiHMj/OrE2M5mwftm+NrwfxcPnzWwPfCYTv3F4R3ByZH5/UEWbvbX4feXnB95usk73mKvNrtrwu/l6SVt0fp5Ym08nYPHHpj+PHp+u7Rzg7j5Wnrs/POoTZ+frq+e/Q6BNenrs98DeAwaONvT9Z3j/e2H65P4+X9sQ7a3rT/dejlObTydgiHId6+Cn95Dq28HcBht/+vwV9OzvlZY3g6zP82GM9z3t0736e282x6eca49+kiO22d1/YX0ctZMDieO7C592R4HiK88+j6WTA42M8T2zo0qHOeeQaOd+jlIDyfSneH4XnW/J5Ca3v6OautF8qT+3J62T/Gw22dSw+nrhegl512TrR1Lj2cul6AXtprZ35nrYHnD/1cejkHx2fT2tekl7NwfD6tfT162TfHE20dpbWvSC/75niire+FXvbN8Xhb53+efT2jry+jlzPbOuN6DpxeTN99MXr5Uhz/QS/nXv+v0cv+PoewfM3xf8G499HpcCyH6OMLx/+lY9439uH9g+N7LvyPrpfD4zu9xr60rSPjP+f5J87pb4faP7utU/RzPu7PmlPn7y+ml3PhenRO5+N4//UCbT2Fjp6L433XS7V18L3+9UU4fsW2Dua2bq7vjF6ecn2P9HLm9d3Sy8nrtejl/M+zr2f09T9R3/2611fG8R/XH9cf1x/XH9cf1x/XH9e3v0a5LOLsQ1Nk++rfltPJf5azD3+aVrPJKFegXC4eceZvXRwxofDXrLyuUNh7snic49z5dbl8X7UH2//QnoLN0X3unEmPYobT+fofuRlypNFbQK2huipwNb/C4cO5kvhq8bAcV/+7XN3i2OPJjYxNquDD5MYmjsY3OKZ44vy1S+VEbEI6TjdGIVST65Io3IR4YxbGnsvSUHb8BpP5sSlT3w56WT5uajYyik85QzUfVbZcmqd8/Olg2UZVSkzmPTslQ7G7bhFHr6jAIGRePEVFhbZOTceCHYpsKMrSoUYZHSjySIMKjxIjMWqRkZI3I9kUfHQFe+9IOeaKJKh6hjrx5bg73evB9PuVLde31b+8X1af/mW9WNYFPP9ZNSUcxTCB21yaBO0Oajj2arTflavV9KZfoB3VXMe50O/ecpl7QH+4XKYOIR0GoD0XlqkHvM+7VVL3lTOdb6ud/q99RU77BVJrQO97Y3X8jXxw/t39YjXFcP++mM3qcXVuopH1Yl5drcr5eP2AOs7j21wJ7tIVlA8g7z9993B3Vy1XV6ho0X9499mP5Ri1lT+Vy0nvUZcwtNV6+TAG/LcD29xCudhyPb5dLx5zEYbtuxzrKprzyV25/LB9tb2T69J+qPpDy6e+d5/AjO8WD/N1fRR/51E/eHQ1nX+4xbHpO3PtPPSxnM1ybYzOIzp45j0WCeA2XQ66DIMnr8vlcvF4lQHQnzsP25wvZrOru8Vi3X8OILqeVfNtQdpyPq9+repKsLNFOflLPmpdC2LT1FzxGAPfObK9rrOGI9vBeM44sX28LHNlhvLuvj6N/r5clvfVeoRSr+PFbLYp8NCpjcpYmHWtGN6UUXH9KiquLaLiejVUqFdCRToEt8r1zG8Xs1l95Pznzah/G10DUsur+8Wqrqzc1NcYY8j1ELrlEtHspConKMpc1aWjJ4vFMr+JkhxX5XJ8m5/Kf91/mmFh6MXo/bx8vLqbTlB0PD+8LFe5oujF6Lb8dHVd4qB+agd5tapQpiWXpRp/QHHW+tvV6n6KxYIS2suH62u8lC5Gq3EejTnMuZxPpvP3V3mV5xmsMNb11QwL+JIw+WX13w/TZYWKIhlz48V8Xf26vrxZAGE1Li67gNne7EBnc3NYUbK5vYXT9hZgtflrC7D+rRpq23sd0G1vZvht/rwtlx+r1fpqvFzc1zPv/NSAd3unA+PNzaYgUuevBtjbezXAN3/XUN/+2Yd85/4W/NubD8uP1aduD8vLyWOVFxD+wNS2pL2lXeC6mtd1OyAT/rmYV/nubLG+bJnnag0Z2KP/i9G6Wi7B/FACe5prM/ypytLxp/K+vJ7Opuu6jPN+YuiDrB0NqhmVkNV/XazW/74oM7sox1kTuLSAmszV3ae37Q296K7zVK+tnxu6qZdsR/pvSlU1WsC+KtwNMNoefnnXlcadYo8xSaGbKs07crpfUVVyaUfooWoo5rG9qH0XOic7HbzIPlBWNOr6xb7/dDjYDUPudh5lO9LwdgL5WZ9GuVT7wzzXc6km/wnh9XZZlX+vVveL+Wraxe19Of6w6ipZlw1wIZ7n5f3qdrFulOdIOr6uxkqTZDJJZK68GVdOTCxVwSyOJ96uy3TDpDekSt5N6LoK0Y0l3lAJfL0Hdsp1lenin5kf/bZHaZ/XmuRPkJT/8tdy1ZLsrPqIzQKqbp+vVQ611aGSdAGN9S43Nik//XsuZ39JBTjqHH/8a5a0rogbSYYdzLjmz0Wo2en8fdYNC6cXo9V9Nf5Qy6XCQ8jNqjVU0F9GbyjQ2EGpfcPCY8Jc36B8KI3ztxsfOeCbn6iKAxKup+WqVVfL2f1tWZfxhrwsV3mftKxKSJgIoNxOb9ajyx9cIT0xXNexul68ryXtrCqXKE60fTnXXJnll1slFqu9loYfVrnOO73bttkg7W66WtfUdjPLQm/0hojUjTfKwugNlUzEuftlXRzqTShD6atMdat1Oc4Vad74sTcpOzd/nrzPP1hprBF67nhcV7x6M47XMeDZWuiO3kipJVe5KAy0kNEbmUgpNPq8Lbe+rbF+Dd3vflprdFAB8/T4XacY3nj56X6dS2r1nqHuM30pdOAhiI1V5+dwQSjg1hbM+4XihcTuC60MaV+QC+112ki59md/EXpvD0VO+xwN5ld+7P8q3V9vFsu7en/Tb+Ci8wvA+IBqX1frLEW2le2P7N/2cPCNDvZbDxcwBGRl5rfRuBzfVlf1c1kklHfXD6vbzR2+GH2spvPN35SH+X6xXkMvyYhsf3KFgbRrptfpMVzEdy1LyRDfdN9S+k2FDprCQ1XNI+RidL+sVlVWA+utGcrh3pST6v+A4uLnTYW0yXRZXT0uZjfd1ze/3i0WaP1xlpdp+zv1m6+rOqW6/T/PR5d+23y9C7hfDpuQwRPXD+vxbe8J3teJbjuRbSfXy4e8HI6+Gva++lgur8v55Gp8O61umh3X0WmC+bbt6LadzACvVuty9uE0qCAl9rSBTcjV+HaxbMv7HZhPRmfYj85/Lu6up0dggXfZdd4lt3159aGaVevFPCu6/RF0BgmyfSyXNXM5Os+4lyRuq1+vHqvy42k47X//ulxNZ9PVh1Nv216ENxaFar6ezqvZSUzRXkzdLcYf1rfLh9XtCSz5DqRDZ1XMytXqw3R+Vd6fhoLfO4+7cvXfD9XVbfmQCzkebWE/6a9vq6uH+aRartYPk0/PW96NFWV1W28HziVY6+CjKtezarW6eljdnoZFf/2/e7JFq1WGn2rXatXic61bvffY9vWn/Yd86g542zik111535qdKRUpSAzRazRVaQoMEpsVHjXLzSehJLRvC/Kxms6qrd1ltWOkPmEu7dgonmMQ+8MYttcY1rFLfk8m0O/ajl3rc38tl+VdVpdqle4v5WrVEGejza0XXZbiO5rk9ezhpqvzcNEtOX2zmHX1KVeEeh2il5+weS2xA/gFFHvhCg7vsKudVMv/mNZFZiEksWQ2N3/aQFfadv4x/Wf1d+ivyV2Id2Bmqw+fRpejxX0WreBsP0KxK5f1lnj+MJsBEutPjf6/c6PzvTEv/KWaTbbv3lXr5eJ+MZuuru6y4fTA7Z07GFy5rOblvo3t7r4Wo55lLGdWAzY9Xy8/7Zo4GnvClonvWkBO2zkOGDT2WS72mSjebXdiHeNu3ygTWnefsevWjefCaUoelUmdEvPFcLOUi4z/QEWEhyyYd4FZQ+K+0YS8uqb92C3UTlZENQ8fG2siOdA+F+aCWPLRm6TAXofNx6b55Fy/7L05j3KzLEqBox4ef/IhsRMj4pjMBh1Ebjvwrj9+l8zIhyQMjrHtoLFh5vZd4UlZvY8+JvbmgxyYADvpTUALFy2lpCEklgi7/572ubDkJLIzciwhyXD4m+aJtA8fdixiqkngljwAfymInKkL5FV9LSb2AIcp9gYvhXB0kTwwLBGifM/gqaCUq9lLChQg4AfNqzXNSxrQpjcfgySNzpKEeAA2xGosrE4c+d3Ra3SF0+jEsZInCQ2hJleQeDET00xx2559EcWjArIk8hap3/PGktzg3mmwKMmxqvkQbEi8wSB3YkwUk08h+Lb8NBfiiT0nz0lTdwCGX5w4M6wcx/7IALSIMQaOPkQTizu0gfmzGJtLIcVk2q4kLgKxSy4IC6UB3ThN7KMGpybJhQOgd5GwvL1TIC8NuzZB16LRaUycfDvzlAoFS/LeRSKl7oqLhbkIoAtWkvn9K46KaMlT4OC8SnI+DYEeYsHBEpEaO5ekmTW6duwSOXXkY7dnDMr74JMG9qxpb8daBDRI7MBONMXhlBVk6xTEHjk2bJedT0WQ5B1TYhdDn9pSiGBLzIH5AKxdoVFjwqRNEEgw7DgELYKZ+KCWTFzTMTE0xCDOOwsCpbOHZeeDM/MJ4RGqR6gsFGA9khJ7NjMbdq9GRVDPTASCcqHp3nORUApcJYn3Xvr8w0efBGuNEqcjvXOhwg48LFhyMepwjVlk4DXkYuBqxNvuLXDwqtaYsDu9qwbv2AULKhlTR/r33pygTrdFTskN+XtIsVCfQub+4rSdfkqFpcBJYtKQqIt3oYKiOImanDdNZMfBHziBSXsCI9vpP/giavAB2EkqDUNlKwJWulkS78z3eQxbcEFUKIjRMfD7QogsiCdLIhIGi01b4RmGDFyJ1GPxR/V0SLngIjoKyjEml8i7OJicD4d0lxg9xFqCVDHdv3B+oCJ4B4pEoXVNngdcitvRm/Z4YCxCoEDRU3TBsZdDukvwHFQMegUpDTSjcKB1LtSH5ImTcgh0SHFxBUNqMDPhQcfD0W/ajzRQvIR8EAng8BzTAeC4glyCzgXJaWbBH2o/OR2waQmRPUCqzGKHJxCAVDIfvUIYDOQzx72aF0uR2CiS0zx+lUNyIJCpjxY8JYtxiNxN62kAHiULBqUwaEoH9DopHEXlxBqYY+ShaA/aanV95BpET3DYa2Yzx0HYeIvOx+DFJeNIfgAbobb9nlbNrlCnquzZSeJwSK2WgpN68dAwEMc2ULwy1TUyYsCWfYreC3SPg0pdCppD6wKBLjUOWUIqNHg1JifC1CpdalDXvFDwiuXVl7+R1EuIlDREti3JdqMbmu5ZJELpF29ofoh1KbxjsZB8smitkQlSIoUYnVcNIJn+tInBS5LGoIfnTRZiFBUlImgqA17loHK7hBA/Ie9s27GLDEXVianF4VLipFGZmCPH/T37QiACiQMnizyEt7fcSgiSEF3YqDvRIP+UIDHUx8D9fgMgZDH6CD50GNxakMWIVa7kfPI8ZNBWQOiEhI3exqSXyBVqFDyzhwLaVz1iDDDzxeA8dleHO4fyrGaU1DmHtTiQPuJjQVCrlc2bRmm7l1AkhtaTkoKg+3N3GkkZ+ACRH6E1X5iIkNMAfkdGQ4xzEYFtTWIWYqN5OI7YeyVR7OpYYp/7uBSzHPcQj4n3YjwUrDFi46IGZXXA2jSGgr2ysvPBxFPbMfRJSc6lgF7iQOcJnjz6DVHJ+NgSs7wSFTvfpF6HW37nauakOxaFJC55kRgCp4MmBS7YWQqgKGfs3QCs1PI+VddnrYFEFFoIc0qHWndFpJBSMJ8MsnkodVKz59S+uSIUSqzqzdSrxf0yh4sYorMQxKUIAA13nL6FTH+7DCtBDCxOxWfuc0gkJ4MoUCAqeueHkPGN6SfQEDIixj6oOvbmDklkKjRmYUwUPeQH7wdNGMpjpRR8ZAoheNu/OwJWLZl57F0Dhd1dQjN0G8p6T+aYRJJp4gOq1g9UCLR4DmJQ6DQMsdrQjPWsRHA5eAkq5EKIyeuh5rlw5oLLDD4kojAk+dC2Hwa6nNOEzTJHDinQgfZh+1WiII7UYHNL+wEf+zauWKi6GIOIo+TtAFq5AGGpD0aizlSGVhYnTesyoBowCmIKkaCkH9RyKSRz3oEPRj9UVEj1QOsxEPbbPvnkEMu6HzDBoicLWTbb7qa63WDE/v4iFOqckSYNLlGMh1qP0TGT1cqw7UCGmtYTD2yLUYWTGKfkg6ODgDcfvFNLJD7tMgMEAkdg3TNsJI188BLAyMhJ3jUYDdgQBYVtTWLUIHG/VVALohTZCwbI3g17diEWMVqIKSW22HANZV9ITCLqHJs67i/EkLBTZOiuQeMhc2c2jUXRlFm429mOssQCu1pLCRbXKA0r9wUDUkLBpSxRunOG4VegjzOo7EDPHIP3gTnEbOZIO8iEhpnUREMQsmYjHpQKykYq9slC39hGhYcn0mGzER25I7oIF6aC3TSxOoXFbzhxi4UGilHB0Uys6d4VSUg4cTSNffMPF8nIYy5RoKQdQjaDewXvHJPTHSMq9A0hsaDBeYeAT/QbUqEcIiwiBsvxwPoTBXbfAN1O6FC/Lhno2vnEKjtmJy+ukBC9cy6iF9/wdy4U4FawfBrMV4My7GwRCu9+3QdKnycSj82xoxTdENLiuWAvEUaX6LVRf0xSkZI4H5MgeycNlD6X9+kGUxh1IL1H6VRSF6FCJA47u2KimIpsVyF23pq+gxWR87bGRxd8j8i0EBdgLQ2sEn3Yr1rAou5CEPFqzjnRIZp99EWAtVZMYmCkFeSeISTIWYzBKPRVbVeYKKzPUI+jc/vVDi1iVhpCVNggZah0sIWCEgeNKUVnTA27pyJJhE0McoelL3Yleq+JIoUYjQ8ZNmGK9TCnBpaAPdMQ08kVwWUOFgj7vrprihAuKYZkKXoebG08RextApiE2n4i4wIGQmzQfSJR2bFfE8UikQV2DEN1Y7+O6gtNgYNpUkysP2mDsSioJA/z1JFdlRTiYkqIzLXoou4wcPYwJAgngvSKoWYm2FYJwTWhsDb3lxbDas9wGVDieLjvUHAIDoYndt4lGsxcTFq7ycCwYVAYTb0JYXdzSCZG2PEcdtJesSUdhmM3ipTvK2qxiIYEOjiTgvEhix4XMFURDCzB+9qq3GteG1nnZaCAm1dm7+AWMDqgL0BBNiYIZ3ievIXBWhAfmtGngdfICbi+T+oIesZBg6E5hok+wZzKw+1saExWuqPswDsqEfoaazigjrjCSEwCvIR5q74z+AazRgNth5nh4JSQYrCDfkjj4Ik8/EhuSLCiYW/bCj0NWFVOTuPBkQfoOzF4i3CUDK3M0K7q1v2AaMQHH8V5LxzEHbC2UeabsI9rME9DHVOMXGER7DcKtU46hu8sQREyxezAm3rLjZWDh6tH6IDv1hXYwQfTiLgmGFqHHTsrLDqYhrB7iM3C0AJyAAZulxyR9SktOniXkvhI5A6sE18QlnZwMBFK8MMZq49FSBKdQP/30tJ0IY6x9xRvbD0LnRUG1YNiioFZDuxgtUhOhJhh9IWdYYe3aGGUklen8HmFpuNYOArMUK5oYCIL2JnBvkNGlA4ZTACWAI4uDiCXHfKEjc8nIDRxakSYmhUOxozs3x/4z32RoM3B+hXJnN/vgqZCfJSEPYxIMBpGR3DQNlrEDzemybsYTWGF0nTAIkDQ7LwE2DoVu7vBmt64GYltYIvBNpYsBpLsqj3UvmEC2ElkcxMN+CkAWrcvbrDxrfmMRAFVdOhwYIcWUVJo2dgiuzBYAmy2aX/I8zhokBB8TD2L8HDjTlADzGEOTnToBEihbV8G8BFKFliUo3p3aPMLkwwM6DCkC+zih+EzFJfRjJx6Dsm8pgOsSQpSDeZgWXG8Y9uFv7FtfrhDjQhoiwb6Vd1PnT9k1p5gngB98o44c62Lx/e9GKEILopzyaIgrucg30bsjoSYDPYJjTtiYdNB35ZHVjC5QBGaHzHtNyk57AsJZm/YcZGwPwR+i1y1gf9OLMcTJS/MtJ9lSN77GVtM2MvyUOHm1C7dgTEv+9dcwF5CNR4yDlCBvnMsAHZZNLS1cXKt67QvMmHDdeSdKJxUhwCfYnDw+jplmDmHdLPx3Q3MbQnqqxLnFSNR97MdLgIsbCk7B3XHgsphE/LFA9caWIGQYf/LeoDm0TrFmOB8g5V+GJHF1nruLAwGH8WlLGGMhOgA0ShTcqLsYDhnt8ORHXxogn2gg2+wYZ8pFRHCLUFa63CfztjhIpLFe+UDHlWYMiGUE/u8H9shqBB9QRDcQRDP4RpvhagVqog3ChwTD+IkOG/fxRKF5N2xSAUtsMtMHmzTjHYkhYuFF5BW9t81spckSOHgkLaUnKf+QgLELZCl4H0US8ejoYJC2QEni6ZD5RZTKxCmAaFhgVPDeGAEiZY476mchaGQQYiPqBF5sf2WIS2iJuyiFPHg3g/tBWzeF4IYNARXutRGYXnlQlSCxSCsfX2HPeRnChDpYA0Hts5UwJChZLVP1g/9rBzYF4iuEwS6kEtt14bdpVcJoIWgvj9rR0HgzIO3wA3c38PwjGx4TEkgLdPQU8MxUEGBYJkgTa0vVr0UTswMu26KiQaaSTAETCAa6sD2mWDiC0l8CE4CILVD6ghcFJejzzZ+OcSjwSAlXmE94j7A4cT3KfiE0CQ5RmoYvToP3YNVxQ+DRtksIHrCR2aKIXJsmKGkwrDRyb6GvjEOYRMuChYI1rBzBy2vFiKC/tQLdI5hz5KK4BIYCZsEJy2jlMLgfTaL8I/EvrT1Kal4FXiVjwX8OXhjGc4AbNVkJxaLfeNlGbjOqDANYMoeAVmS9pugfsjarGUNP5iLNHRxM8s+3xkjr5dgt7KUHYyHt78IpTKKSrrjuNdGk91xnTnEH8MxD4OFHdZ0YG9w8AZwgFlyZyXuax7mImHvsncGMz4IGYOl0ZhFQJ0yxHtoFLWBMEcEHkJryLzz/mAU9A/YuxMcUAKHc9IdHtZCPvTCVcnDsQRbGwlHEdoPHSnAfRFxmTgh2neHamPrPdO+9IG0YiRNwLzs9rcOLZARa4SdeETgyKB1aRSpvoeIYsESEToFOzW7A6BBmE9EoE40MqS/D0le3QH/E6QJx+SEgvoD+we4rC36GByc+M74EF4HY7dC4cUIFgza0CGXRXZDwPoak/M7Rkb2ChsDVqVLmY3VKIa7WEDFRLBuxz5BGREM4/A3svf75RJyjMTBzYOtE0zlOwqiWhEQ7hpyJlbNIMG1PUcmceajk0GQjLegWIoJ3YcjvhJfILI0EPy5BD49JAiBxcfD8ajRcTNvcxC6Cf1CifBdqcQKg21wiGcRUj0QG6wFeS/Z+YSIxJ1ZexBdhh+sCY3BxTwi8sCWvDGxUF8suYSUNQRUBOvGWw1cJeTMXIjeEtkwjJE1wb0W1KLLcVl1v5oKRLZ4ROckDoO1EUMkeNAQ2cJH/BWcNxrYa8L4Sd4POR95KeB2iYF85NhMWorsU7JgLvTdcQgm9gjGAn2odJS+fnL+xlvC0RsMNwiWG8w8GkQPIpxj9Gy1BxTaMcLYEDSMQCon/anDq5PEQhQ4OA9ZmhQmQ8IWOIvsoZPIwXKkzrw6Qrh5auNUqTDyEYY9Sr21JR4hMqYURSmyP2hbQ3PR+RAkpqHiYyoFPBMKWHtuhA7kaeFVIYKzQVD64pMBIDjyPMOTd4CJEzmYplWwYd2xfPsgBeZkCVHViWIbB4Zo38iclNjZ0DUFyZpDjOhgCoqHiQV5JCmGEOLQ/5jjzIP6lIxz2H7jPbACnjgix2QcdRD3hsxNaDHGFOgAjmH8QmoH/C8Mj9sAxQkxfbCJI/ZNN3lOGhF5zc77HM7Ti/4SKXxAaLJz0bucOLp3xjAVImYPRisZBt7CtlrAEk7RuRh9q9XD5+oyLwdb7VG194WH1pkSQT9KcagiDR1fMRVIx8H6cym1+mviQhCMjpg3xOMP7QbBouV4NTf0cOy0j0xPRI85g5+s7SBYgRgr1hQJtrF+0HqwEGAQTTAWDnf3Qxh5ha9KTWI2j7bmiICtGDI/4GPpbXYFYdceoUYaFHg91QFsqIjY8ZL3FO0UGG7FYAgVQBhrn95DclEQVe0QFHkCSp4T4gujCuxJbrOL0MKT1xzUGam7oISLBFUtYvsE8jnaPowZRY5iNWVwnDZJBis5JJc8pSTa0/g8g4/AsJ9je3OA/LEuCL5YhXfEa3La9hClQEIQjqnzGjz30eAD7AM5oyOkYeTOcA6GXCZR7zhCP7DtHBDqxggREddPf0DYvw+St8wIEznRQw5mcc7DhUfaUFLM8cTwqROYOcmAVH2MOeFX4T4+gQdyCO5F+ESEbLI2hBbcAlFMyD1h49ifgyREdCCsBILyaA+MmJ8Y4RKJOelD20lAjiF7C2qo62l6sQgEiwoyjkhPrAambLBAUmkCuJvgF8R1Fdj2QbkMFpIMV4OJIrXDwVEw1MB3tiAFadSQcvRDbARq9FYkE3OIaTKN1leTOSB3hHM+m+7EaQ2hZEXe+rNzXqRN5UFITZHgzhCLwad+LEudnQQDEonYjp4/7AE5SRoJQYGZOtseuIDCm13twkPDQCBDDg3SiVhOzMHFwgnsPYkE2SebcGxCSoyPrCzeU0/JRI4RQxUzGJ1pJ2tgQK4ssEL4lOPrTeImq1ALY59cIEp5s7GlVswBawdpJ3F3gz7sQCPip71Dfq1uVlwOXMuH2OZNgPWplcxBmGCnK3wcSPDGIlgigRubCxs0uFAotuJApfSNgdDOlBCNLbCJ2dBhM5xCgBA3r2aITmrXm3OFqJoT7xO7Xk6cII3Kec7eDCRlnejAIfYcxuBE7MS3eHYJUdDZn5ATXrpYNkcR4dpQxsmfgBEHKWBaFKdJ2+gqpI0V8PdYUoKh1w/YnkBzzjHxO872Yftg3BEJOixBacPzfBERtiMIuekL6NpGF5wwki8RGX5CyTCPGJqc1uFYmtS0rBko7K5QhpJJXz0jBzMqs4nnzmquj+ja0wFygEgRQ9Rmy3vkf5qHHStgLQ/858iIiJSNAhI7QNrfQ4DfGJIkeewDY2u1hjoPYk8iKcgwg5YEmm+KSI/uZF4fnAQbcr2ENDVBolAuoUsmJ0lFeCgZIpIXIizUqau2H5gDopuZLEU45bm1QcOI4SJSrUKAljZQJiMmHHBiC2Z4oosYYSqCwEq+xluNCc6pKyLiDIk/Qzca3O5IDWML4RSYUiyyNV4gIKzlq16QHYO9RETYZz8oCmkUUhsEBXt/f7QLRlqFekLyEoyxbY6U04jIGo9kFiR6dAlWqTCz5H0O/GI+1UMyJKVaci6wb6gJebMwcuFUEnjUuqLBU+GdE4ElBzkVJ2cgOL2cIiw+1GYgE8EAGAkUKalHrIIIWHbZbIfs5BPrgQPYGxLikFtKmtrEE8UwYwoI4eZeQJ5gj2m1bVB86kYK7O+BqUiwkiNlWqXJ3manXLjMCV2k0PNWQ7gx0okVfirq5Ccc7EAQ5FK7tdopeMLeIBnSKLivcwvMaUh1DwhSIqXjqwGp3AX23SSCQMCWjDgUCDVKYjEHvPd7qDNDYF0GbE8saZVUeBaEIcO+HJuc44C4n0TsE8Oy03fOpgIBgrCPIzw7hOOkBId9gQygRCGKxhZOyPV2wWMlIOV7aIwW5DJiN2Nn9FAjLjsfszWw7sG7Aqm3zmoLS0+fDIWvEwhhF2M7wZVy0Lkl7DMcLPzNcjMtCGSU40XIeiKUuGA1QhAx5doB8UQXUKJhAxb4NH2bAma+8CADzi5N7oVwERUw0aSYclQJn5BxXgQmSM+IpZeNIkPQVw1GSWQX9DUlKYJPHs45pMy4E1DyJIUa0odgic3O7VolLhiqZIABOUXuCyAYp7FxwbEW6fiCI4+gr4BtUoDeFTen4RSRQ2ATx8iiGxzIAHgyRCLYccfYcKCLnHSgCKA25Jg2NqgE0xVyDeEC5YFrm6BKZp5n3fio/R1kjRgHvcRIsVlvBFMDAXSMUCLtJdljCozYMjhYIZhOyDfvY4Fwe9itNTjeAImRmSDJ58N0Brw7ZtMvmFeCse1ED4iL4YBAMiCudQZ7KRCNoDBZIlcn9nUZxaYK2QIK1fUUmHwqIkdnUBp8areIiOEjjYxoJbDewcaBDaIJ4a2BTvAMn6yIZEgQQGiQchtCkb3WiL8NFMwPzKve4JqEFcLB5n2ii+gLh1MJolnOQ2+7iDnux9gljtTfIoYcIMLI0Sdk8J3CdUQioRevOWGP21kgdSLAiu4k9reIBDcYIruR9AML1gmuochnDEglVEFmcRvrgYCOpIqUK+TwDxytCpEilJMv6MQclKhwCWdXcPKwbWzDSRCZrc4k1YeF9ASERYO9Ceogne7CZzsOTF0OR5+0XWiRouZ4Co7OD6IXfIJByPngBUkrp+EEI5RHnAIkWotsHK2DHHcYI6gvhBL2cTlZCVtpScdnISHARxIRJiFIcGrPB4m1PmvkkAqjA3pCyAYMTGAfHaf0zlHE7REhOEcgalCDBXWYwZEEB9wgGM8QWdJYASP7wgdkWAsh2XhwFk8CV0POtzBiZE4MQYs699PDZRRpx2QuTovoELCW4NVsocAu5zm46GCy1YFNYdNnv/TBMFcCx/cIgi4Sp7ghduJYGCu0VJTy6RuCz2zaXMIhFqrJkCHTmMmZqQgZ91G9N+qfIHVe0wZ9E9lZKE/kG9L2xAXCOtkgTLiXwsT5rICIlBvEQvn9ziktLPu7U0C6McnAK2Ycco4UHDqUmmz9AA0D3kYXsEOkQb46diRQAM2HQ1HQSG+GGcTyOW6oeTLoNnrwu+Cjgkzrbi1vMiPYOFyXvW0VVOUUxCHUHfGhB9zcVGgiwvqFjQFxqoN+Qz4HA0peCJGawC+cyACrRwoG9csGFstQ+1Jx0pLKgbNHGB0jRkqgyfucFNzrWDVrHowcH9fw96hUINsdsfuIe6OBOuIsOQTiQjr7Qz5ARNabaEowAfjhcQwR+FJF0DckattxAqsOgjOJcJacDFRqmMlxZkUKPhzKZLCA48oQLQB/9dDHbNBHFSvR54TKWv9K3rAf8aBGGIh9H8MKmyeczOAc+wnLF+bZ+xBxGoIfplyCrBgmAchQlWaLEhHtJ0B5UvhgBmsIPpWQj+szt3Owz6D9LI/hXUCKujaxXMlrkRdojpPinoRjJL4FuPiiAxKOt4+gQ5yl49mCQY9sj0phX0CwKfwpSdIgvw1ufnDSLHf3B8HCaoCQQCQOIKhMhnGBPiScVQbrq3FyjaJmAm89DmJBXF3qowvqZzDsWOCpPnQsXAqGEAREeXnoyzsBGHBjRxyYoRsXNebrvUVES5rrmw8o5LxIRbpXcE4ORYrn01XgNQj1QSs7/heCDoqAcIu+jQc0F2Axz8aPgJ30IIDIJwQXYAOE0y8PR5zAaITUL5adsDNBUDTyUXOgQzak1ZDOAaApwZGIYJ/+/k0S4fyO5DwjFfVQrg1i4uHENkB752wrjUXObMEWJedz5y2LJjiufPabWnLDY8lA7h6h06oc9y9KKLsMx5Qi6zfXsut37GAcRWQGouQDtx17HNpF2YYTLcY+rH1yjCWmCNU4GGUDc55GxiEjLgxPx2BSKQzpKNnqYq09OHjLpzsglYCUButV4VPCaVD5NKFD4g2SHr6HgCxtvxMQ7yIEViQJLqRkbawJp/oYmmy1coO0pij5zIYEQx0dzJAFsw8G250ndTvxvWquPl0IhzX69oBLBJojLRtOdOiXPcarsCsTMiuQ9OdP+eTAKXASGkFNSxk1NQEnOMGDAMd9ViFIhRacsKM56uS4lwCx7TkPOCly2NsDA3KsgyJ0LeJ4pKTS36t4j4NpKKcNn3AgMwek5noH71QKLXIQnwCNHDm7GnpRImDjKflECgGOo6tOOF8tpxT4CBnqWm6KaGPC4QIh5EP4Ql8SuXwuBiL1VcMJB7XR9gjhTis4+XC7+eiU+dpms+KUBmz6YR8YnpmCdLzWa9X38/QbbQuFndlqaC08/dwTcp0txLZW16GXfXz6yxswMb0KmAaHWH4ZmNpWU7RXgL3QF8C+fyrcmbBvF67zhkSUhAQphbu+bwFAKK9kbwcSgDYtd8rHtdIN5rMATSEyx+FpH6JNaB38hQVyH3LeZ+yHexF2NtiRYB1i95T2TmW7nUCSCcPuaTic9EBwfZCziQveQwRGBs0pP8NseKTw1Ts/PZcGTrXI3l64xfaQ5j4mzyEKlvjsV3OuRoysqtmFWIP+h15DiswlFp98PkK8E5rRL6DYUlSCfSJ59ep2NhMcfIDtMnNsHKPg93SIg2MFuqDP2aNbsdCv4tjsXZIEU8amOtanVAx8gQkOFo9J+qSNaaHn2SIqEPPMONAkHxbnj5FvDkLGaVQOJ8XYTvK1GrJfLEfjIdm09QNDn0P2JiRY8L1AKshN+KwiVEKmniFqp3/BiexE+WhZmF2GGimyYQrJIbvY2Wubh5VUUJHZRfUco7hBILRERkClw/ED3DktdQ+KEZ+g8HKmxAKT/C6DgxElIMYjetkYInBuM7CK/PLkBgl4CF5KiMVMjMOFtnpaXadypwuoFRwcwVYsqQm2ViiCQRCCK+J7LCqnk8KWCcM/dKZTPeCsmcCKxAlEsTfB5GgnW79hd6D+ySSSg17gQGBWn9zJSSSchmf53CqNvolLZOGESOVaa4L62CdVFmTQINUsaeqcfrKX03qk9eGcdYTEyfB0VdHERfYWQUH1jUId0b9g1wLL7yB41OdDtgP8loL+w4k5akDyHgdNmmPE6x4IBxcjAQLHNpMbnAgQsKFOiFZI4s2fgiIihIyT4cgshN83VqBUIH4Eaaywfg1yLHCQm2WjEcJyTkwiewyigzGIOGfktcFmcOl4HE2B+P3exgOqsyIQOeFcoG7YxV48UbbqJZRLVyTyDwaA0Ewcw4ZgAHDFjUsJ1j5vCIUO1Ev0g7sp5CPnkLgeusfv7p1iDEiSQAZSCDjuv+kC7mz4dBFDjGMCeo6xhNMgkAnqnE8q8SQYcZAIPHg4MpZadwxcuxxhIEdWoPby+7GgXT6vjLF47VQP3KgOqZ++1TkiqCnZO13uEcht9eNN4be2YtEb+f8mDjVPFrn4UlvaFlWjt12HVga7i1z/xOXqJ4LiaaPb6fp68etoW0OwKYNy+5hLmN2ipE1dPKybabAJjBmeoLlV5/YUst3edt080gg/mMdRJ9k1+K6tS11XVNH2uKDY1lNBfPoGlu82xatRlLZbvRp/1+Wr8a1Tv7pfHaXbGAp0jZsCQ7nq0WhTvpBRy/Fdr/L1L0jqjErQmgkppR4xD/iKsHqK6d1O2am6BlxdF6eudfMGoJhUN3/e+eWyWxsnY6VlXNQeCcE1QtnXGNV8wghw/488aCB6uVjcNCDA13+sP+W6oK3rJhcY3cD6eNPvmsfbNsaLpk7zePGwXKMSU9PRZLGpEox6yfnr54u9s6dnz76l5pef/L6WX2Pu/NS541iDPMJmgNoMkL906scafpmZdzlWZ9q90mudmW54VrR6RKT1iEjPnup6ened293M9d3hQf/2agz2oAyYo+jrrPnth1r9cJ8/d8C3bzArDOYg+2qY76aYXXlfgpZyWbK7xaStfYf6fKNyeZclTvPOzawE3/9Yzh4qnEEF1DVPVh/LVV22tnl2Oh8vq3JVTbYvuEIw9KZU1mhdzar7RVbMF+Pxwz2q0mWCqJF0V48EGN+WzuKGCPO5KI/4P4OxrnLVIgplfh+n80kubvvLAP7Ni7C6pm6ZrZqYd+/OG8jPM+gv+sNoSe9Jrbm6sR9o01o7tvCSY8unAj1zbJuhCb9kY/EL5jmcpuhrjExeYmTxC0jt0DRfhtJadH5ha3kRj2cLrO7L9fKh+pwX7aagdMuVOprcJtqhU1G6L7RDW8uCGnbOm7WNUp7l3VYKd3XLd22dT7jqkc4dctnUugY6KkLOcsSmgadgbHCGgjPXLPjDtlJ75tlNmfmLXKsYAyzv7mvbwX25LO+rNeoOfrjO1fxGb//2849/fPLnX98+/qX+9P/+1uM6/Hkc/P/dfv4y+P8FPu310jTQ//+Jnz8P773tXd8P7n/q/43BDWD7feD+p7fvB+PcwrQd60vi//mf9z3cvx3gvqGFbz7On96+/3MX9+04u3+3cP7249zivh7P2+Z7F+ffFqbNODu4f9sbZ2es35hO63Fucf+2XTtvtzh/2/lt897XHuufB7h/2362NLkPpn26/oq434yzXkv9tdPSbefegF6+2jgHfb4d8KOWHt72xvnT18N/298Qj8N109LCBs4H3nulz/vOOPuwGfLMhrd24Lx99+vCc4jDt4NxbnD/9tQcz4DNC46zxXGX779926GJ7rtPgeshWnv2Ow2Ou/L+AI0+Da7Pee/E3DZj2o75b3tp9Glj3fveCXycwsHbHs8/Y5znjPXAe+e8s//3A7revrX0pLE+b37H4fnjQA89c5xn4vG5fGPveury/cH+5NhYn4z7Lxrnj3twfwYOz+I7z+Rtz/48d5xDvLz2OF8Lj6/zqcfX/PEdj7P5/JjX2d+++3E29oSfv1J/z7QH/bwZ449fa5/6BbbA5svXxN/v4fMluP+6n+/eDvw7wn3fF/DH54/PH5/+52vbsb5knI0+c4Y++y3X/XN02m/C85+zT/gmPP85+4TvBPfn0Oq3wP1zYPqN5P1T7BjfVN7/bvazv5dxDnH/7cdzHu6/g/GcBdNvP5bjnyfw0JPr/pX9Sk+0s+3w/M27r70Wn2gPHPD859oVn0dvT8HZAPfP5G9fY230cf9c+/BX4N1Def9FuH9NmA7X/TNl2zfg4V+M+68mu5+D+2+jYzwHpt9EF3rOevomesaX8tJvBdPnze9bwPRZePjqPOo573xFmD4HLt9inDtxka9FL9/m83vYV+6O9duP5Vz8f/uxnDfO7xv3v5/1dDS27jv7/H7W0zDW/8U/o88XyOX68B+f7pGLe/Vvy+nkP8vZhz9Nq9lk9Pnzu/8LX0utuPNfAQA=', 'base64')).toString('utf8'));
function run(f:any,local:boolean,mode:string,liveWorld=false){
    clearSeaMemo();
    return withSeededRandom(991, () => {
        const world: any = makeSimWorld('warrior', 991);
        if (!local && !liveWorld)
            Object.assign(world, originals);
        world.sim.bindGeographyPolicies();
        const g = structuredClone(f.generated), zone = g.zone, entry = g.entry;
        for (const k of ['exitBoundaries', 'exitRoads', 'exitMelds'])
            if (zone[k])
                zone[k] = zone[k].map((v: any) => v ?? undefined);
        world.zoneMap[zone.id] = zone;
        world.zone = zone;
        world.arena = g.arena;
        world.arenaHull = hullOf(g.arena);
        world.zoneEntry = entry;
        world.player.pos = { ...entry };
        world.player.level = zone.level;
        world.time = 79;
        const layout = g.layout;
        layout.walk = g.grid ? GridWalkField.unpack(g.grid) : undefined;
        const scene = { zone, actors: [world.player] as Actor[], player: world.player };
        let localPopulation: NativeAreaScenePopulation | undefined;
        const geom = new NativeAreaSceneGeometry(scene, g.arena, { ledger: world.ledger, seasSeen: world.seasSeen,
            oceanBearing: (...a: any[]) => world.oceanBearing(...a), seaNameOf: (...a: any[]) => world.seaNameOf(...a),
            notice: (...a: any[]) => world.notice(...a), text: (...a: any[]) => world.text(...a),
            get time() { return world.time; }, get seats() { return world.seats; }, seatOf: (a: Actor) => world.seatOf(a),
            drainSurvival: (...a: any[]) => world.drainSurvival(...a), radianceCondHeld: (...a: any[]) => world.radianceCondHeld(...a),
            createMonster: (...a: Parameters<NativeAreaScenePopulation['createMonster']>) => { if (!localPopulation)
                throw Error('population owner not installed'); return localPopulation.createMonster(...a); } }, { navigationPad: NAV_CFG.pad, eventSpacing: 240, minPortalSeparation: 250 });
        geom.currentZoneSeed = zone.seed;
        geom.exits = g.exits.map((pos:any,i:number)=>({def:zone.exits[i],pos}));
        geom.zoneEntry = entry;
        geom.adopt(layout, entry);
        // Both lanes start at this SAME concrete mutable geometry stage. The baseline
        // remains an actual World; local production code never receives it.
        world.walk = geom.walk;
        world.tierViews = geom.tierViews;
        world.doodads = geom.doodads;
        world.grounds = geom.grounds;
        world.bridges = geom.bridges;
        world.structures = geom.structures;
        world.fog = geom.fog;
        world.doodadsRev++;
        world.convexNav = null;
        world.tierNavs.clear();
        world.currentZoneSeed = geom.currentZoneSeed;
        world.exits = geom.exits;
        world.eventAnchors = [];
        for(const key of ['caveEntrances','demonPortals','crusadePortals','necropolisPortals','fractureRifts','dimGates','breachPos','descentSite','waypointPos','farPointDraws'])world[key]=(geom as any)[key];
        const sources = { ambient: world.nativeAmbientHost(), groups: world.nativeEncounterGroupHost(), factory: world.nativeMonsterFactorySources(),
            promotion: world.nativeMonsterPromotionSources(), hostility: (World as any).nativeHostilitySources(), relay: (World as any).nativeStatusRelaySources() };
        const campaign = { get zoneMap() { return world.zoneMap; }, get time() { return world.time; }, get visited() { return world.visited; }, get surveyed() { return world.surveyed; }, get sim() { return world.sim; }, continentFor: (...a: any[]) => world.continentFor(...a) };
        const seats = world.seats;
        const context = { get time() { return world.time; }, get npcDialogues() { return world.npcDialogues; },
            applyPartyScale: (a: Actor) => applyScenePartyScale({ partyScaleCount: () => scenePartyScaleCount({ player: scene.player, seats }) }, a), opaqueAt: (x: number, y: number) => geom.opaqueAt(x, y),
            sanctuaryBlocksCombat: () => scene.zone.objective.kind === 'safe', resolveHit() { throw Error('unbound staged resolveHit'); } };
        const state = { squadSequence: 900, bombardMintRev: 100, zoneGenTagging: true, magicPackEffects: [], magicPackResolving: false, magicPackRefreshPending: false };
        const owner = local ? new NativeAreaScenePopulation({ scene, geometry: geom, campaign, sources,
            populationSources: (World as any).nativePopulationSources(), context, state }) : null;
        localPopulation = owner ?? undefined;
        if (owner) {
            assert.equal(Object.isFrozen(owner.ambient), true);
            assert.equal(Object.getOwnPropertyDescriptor(owner, 'input')?.writable, false);
            context.applyPartyScale = () => { throw Error('replaced callback authority'); };
        }
        world.actors = [world.player];
        world.squadSeq = 900;
        world.bombardMintRev = 100;
        world.zoneGenTagging = true;
        world.magicPackEffects = [];
        world.magicPackResolving = false;
        world.magicPackRefreshPending = false;
        world.wave = 0;
        world.waveActive = false;
        const nativeFactory=local?owner!.createMonster.bind(owner):world.createMonster.bind(world),factoryArgs:unknown[]=[];
        let factoryN=0;
        const loggedFactory=(...a:Parameters<NativeAreaScenePopulation['createMonster']>)=>{
          factoryArgs.push(a);const body=nativeFactory(...a);if(mode==='factory-fail'&&++factoryN===2)throw Error('post-allocation factory failure');return body;
        };
        if(local)owner!.createMonster=loggedFactory;else world.createMonster=loggedFactory;
        const ecologyState=freshSceneEcologyState(),env={geysers:null as World['geysers']};
        const clock={time:79};
        const ecoServices={get seats(){return seats;},get time(){return clock.time;},throngClaimed:new Set<string>(),
          radianceCondHeld(cond:Parameters<World['radianceCondHeld']>[0]){return radianceCondHeld(cond,clock.time,null,skyOf(scene.zone)==='sheltered');}};
        const ecoInput={scene,geometry:geom,population:owner!,environment:env,services:ecoServices,sources:{XP_SCALE:.8},state:ecologyState};
        if(owner&&mode==='natural')for(const key of Object.keys(ecoInput)){
          const raw:any={...ecoInput};let gets=0;
          Object.defineProperty(raw,key,{enumerable:true,configurable:true,get(){gets++;return (ecoInput as any)[key];}});
          assert.throws(()=>new NativeAreaSceneEcology(raw),/own-data binding/);assert.equal(gets,0);
          delete raw[key];assert.throws(()=>new NativeAreaSceneEcology(raw),/own-data binding/);
          Object.setPrototypeOf(raw,{[key]:(ecoInput as any)[key]});assert.throws(()=>new NativeAreaSceneEcology(raw),/own-data binding/);
        }
        const eco=owner?new NativeAreaSceneEcology(ecoInput):null;
        const target:any=eco??world;
        if(local){const prior=scene.actors;scene.actors=[...scene.actors];assert.notEqual(scene.actors,prior);assert.equal(eco!.host.actors,scene.actors);assert.equal(eco!.host.throngClaimed,ecoServices.throngClaimed);}
        if(!local){Object.assign(world,ecologyState);world.throngClaimed=ecoServices.throngClaimed;world.radianceCondHeld=ecoServices.radianceCondHeld.bind(ecoServices);}
        const used:any=local?ecologyState:world;
        const poi=structuredClone(layout.pois??[]);
        const initialDoodads=geom.doodads.length;
        if(mode!=='natural'){
          scene.player.skills[0]=makeSkillInstance(SKILLS.beckon_palewisps,1);
          scene.player.skills[1]=makeSkillInstance(SKILLS.raise_gnatveil,1);
          const gnat=target.liteKindOf('gnatling');used.lite.reset(g.arena.w,g.arena.h);
          used.lite.spawn(gnat,entry.x,entry.y,1,scene.player.id,2);
          used.lite.spawn(gnat,entry.x,entry.y,1,-923,3); // missing keeper consumes carried slot angle but never mints
          if(mode==='claimed')for(let p=0;p<20;p++)for(let i=0;i<20;i++)ecoServices.throngClaimed.add(throngPocketKey(zone.id,'beckon_palewisps',p,i));
          if(mode==='held-off')zone.theme.lite=structuredClone(TILESETS.deepwood.theme.lite);
          else if(mode==='vents'){
            const source=Object.values(TILESETS).find(t=>t.theme.lite?.swarms.some(row=>row.seat==='vents'))!;
            assert.ok(source,'installed vent seated source');zone.theme.lite=structuredClone(source.theme.lite);
          }else zone.theme.lite=structuredClone(TILESETS.sewerworks.theme.lite);
          if(mode==='saturation')zone.theme.lite={swarms:[{monsterId:'vermin_tide',pockets:[1,1],size:[used.lite.cap+10,used.lite.cap+10],chance:1}]};
          for(const [kind,row] of Object.entries(LIGHTWELLS))if(row.pool!==undefined||row.burst)geom.doodads.push({pos:{...entry},radius:14,kind:kind as any});
          geom.doodads.push({pos:{...entry},radius:14,kind:'none' as any,well:{power:3,max:9,id:991}});
        }
        world.time=clock.time;
        if(local)for(const key of ['zone','actors','player','walk','doodads','lineOfSight','clipShot','hostileTo','enemiesOf','farPoint','findFreeSpot','placeInHabitat','spawnEncounterGroup','refreshMagicPacks','createMonster','pointInSolid','pathField','actorById','lite','geysers','radianceCondHeld'])
          Object.defineProperty(world,key,{configurable:true,get(){throw Error('foreign standing '+key);}});
        const clean=(v:any):any=>{if(typeof v==='function')return {function:v.name};if(ArrayBuffer.isView(v))return Array.from(v as any);if(v instanceof Map)return [...v].map(([k,v])=>[k,clean(v)]);if(v instanceof Set)return [...v];if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,clean(v)]));return v;};
        resetActorIdCounter(700000);
        const draws:unknown[]=[],calls:unknown[]=[],next=Rng.prototype.next,ids=new WeakMap<Rng,number>();let stream=0;
        Rng.prototype.next=function(){if(!ids.has(this))ids.set(this,stream++);const before=this.snapshot(),v=next.call(this);draws.push([ids.get(this),before,v,this.snapshot()]);return v;};
        const revBefore=local?geom.doodadsRev:world.doodadsRev;
        let error:string|undefined;const selected:any={};
        for(const name of Object.keys(originals)){
          const fn=target[name];selected[name]=fn;
          target[name]=function(...a:any[]){calls.push({name,args:a.map(x=>x instanceof Actor?{actor:x.id}:x instanceof Rng?{rng:x.snapshot()}:clean(x))});return fn.apply(this,a);};
        }
        try{withSeededRandom(317,()=>{
          target.bootThrong(poi);
          target.bootLite(zone,poi);
          assert.equal(used.liteVentRows.length,zone.theme.lite?.swarms.filter((r:any)=>r.seat==='vents').length??0);
          if(mode==='vents'){
            const field=rollGeyserField(new Rng(819),{});
            anchorVent(field,new Rng(821),{...entry},'hiss');
            anchorVent(field,new Rng(823),{x:entry.x+180,y:entry.y+50},'geyser');
            field.surgeForce={c:0,t0:70,t1:100};
            if(local)env.geysers=field;else world.geysers=field;
          }
          target.bootLiteVentSeats();
          if(mode==='well-fail'){
            const bound:any=local?geom:world,fn=bound.markDoodadsChanged;bound.markDoodadsChanged=function(){fn.call(this);throw Error('well change failure');};
          }
          target.attachZoneWells();
          target.attachZoneWells(); // exact idempotent replay
        });}catch(e){error=(e as Error).message;if(mode!=='factory-fail'&&mode!=='well-fail')console.error((e as Error).stack);}finally{Rng.prototype.next=next;for(const [k,v]of Object.entries(selected))target[k]=v;}
        const actorList=local?scene.actors:world.actors;
        const stateCapture=Object.fromEntries(Object.keys(ecologyState).map(k=>[k,clean(used[k])]));
        const result={mode,id:zone.id,error,draws:clean(draws),calls:clean(calls),factoryArgs:clean(factoryArgs),actors:actorList.map((a:Actor)=>({id:a.id,state:captureNativeActorState(a)})),
          ecology:stateCapture,doodads:clean(geom.doodads),revDelta:(local?geom.doodadsRev:world.doodadsRev)-revBefore,
          nextActorId:new Actor('allocator witness','enemy',{x:0,y:0}).id};
        if(mode==='factory-fail'){assert.equal(error,'post-allocation factory failure');assert.equal(factoryArgs.length,2);assert.equal(actorList.length,2);}
        else if(mode==='well-fail'){assert.equal(error,'well change failure');assert.equal(used.wellSeq,5);assert.equal(geom.doodads.filter(d=>d.well).length,6);}
        else{assert.equal(error,undefined);if(mode!=='natural'){assert.ok(used.wellSeq>0);assert.ok(geom.doodads.length>initialDoodads);assert.equal(geom.doodads.find(d=>d.well?.id===991)!.well!.power,3);}}
        if(mode==='claimed')assert.equal(actorList.length,1);
        if(mode==='saturation')assert.equal(used.lite.liveCount,used.lite.cap);
        if(mode==='vents'){assert.ok(used.litePockets.length>0);assert.equal(used.liteVentRows.length,0);}
        return result;
    });
}
const log:unknown[]=[];let firstPositive:ReturnType<typeof run>|undefined;
for(const f of fixtures)for(const mode of ['natural','positive','held-off','vents','claimed','factory-fail','saturation','well-fail']){
 const original=run(f,false,mode),local=run(f,true,mode),live=run(f,false,mode,true);assert.deepEqual(local,original,`${f.row.id}/${mode}`);assert.deepEqual(live,original,`${f.row.id}/actual World/${mode}`);
 if(!firstPositive&&mode==='positive')firstPositive=local;
 log.push({id:f.row.id,mode,actors:local.actors.length,lite:local.ecology.lite.liveCount,pockets:local.ecology.litePockets.length,
 wells:local.ecology.wellSeq,draws:local.draws.length,calls:local.calls.length,error:local.error});
 console.log('PASS',log.at(-1));
}
assert.deepEqual(run(fixtures[0],true,'positive'),firstPositive,'cold A/B/A');
console.log('PASS cold A/B/A and42 own-data binding refusals');
console.log('PASS native scene ecology',log.length,'archived/local + actual World courses');





// Additional independent oracle lanes; imports may move to the probe header.
import {LitePool} from '../src/engine/lite';
import * as ecologyReviewCore from '../src/engine/nativeSceneEcology';
{
const core=ecologyReviewCore;
const clean=(v:any):any=>{if(v instanceof Rng)return v.snapshot();if(v instanceof Actor)return {actor:v.id};if(ArrayBuffer.isView(v))return Array.from(v as any);if(v instanceof Map)return [...v].map(([k,v])=>[k,clean(v)]);if(v instanceof Set)return [...v];if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,clean(v)]));return v;};
const names=Object.keys(originals);
function run(modern:boolean,mode:string){return withSeededRandom(1723,()=>{
 resetActorIdCounter(6500);const events:any[]=[],calls:any[]=[],draws:any[]=[];
 const hero=new Actor('local hero','player',{x:200,y:210}),dead=new Actor('dead keeper','player',{x:100,y:100}),lost=new Actor('lost skill','player',{x:300,y:310});dead.dead=true;
 hero.skills[0]=makeSkillInstance(SKILLS.raise_gnatveil,1);dead.skills[0]=makeSkillInstance(SKILLS.raise_gnatveil,1);
 const state=freshSceneEcologyState();state.lite=new LitePool(mode==='full'?2:16);
 const row:any={monsterId:'gnatling',pockets:[1,1],size:[4,4],chance:mode==='absent'?0:1,announce:true,regen:true};
 if(mode==='deferred')row.when={radiance:{from:.9}};
 if(mode.startsWith('vent'))row.seat='vents';
 if(mode==='vent-deferred')row.when={radiance:{from:.9}};
 const zone:any={id:'carry-oracle',level:5,theme:mode==='carry'?{}:{lite:{swarms:[row]}}};
 let host:any;const raw:any={...state,zone,actors:[hero,dead,lost],seats:[{actor:hero},{actor:dead}],arena:{w:480,h:480},arenaHull:{w:480,h:480},walk:null,currentZoneSeed:891,time:33,geysers:null,doodads:[],throngClaimed:new Set(),
  interactSpot(pois:any[],rng:Rng){calls.push(['interactSpot',this===host,clean(pois),rng.snapshot()]);return pois.shift()??{x:200,y:200};},
  markDoodadsChanged(){calls.push(['changed',this===host]);},radianceCondHeld(cond:any){calls.push(['radiance',this===host,clean(cond)]);return radianceCondHeld(cond,33,null,true);},
  clampPos(){throw Error('unused clamp');},createMonster(){throw Error('unused factory');}};
 for(const name of names){const fn=(modern?(core as any)['scene'+name[0].toUpperCase()+name.slice(1)]:(originals as any)[name]) as Function;raw[name]=function(...args:any[]){calls.push([name,this===host,clean(args)]);return modern?fn(host,...(name==='liteKindOf'?[{XP_SCALE:.8}]:[]),...args):fn.apply(host,args);};}
 host=new Proxy(raw,{get(t,k,r){events.push(['get',String(k)]);return Reflect.get(t,k,r);},set(t,k,v,r){events.push(['set',String(k)]);return Reflect.set(t,k,v,r);}});
 if(mode==='carry'){
  const k=host.liteKindOf('gnatling');assert.ok(k>=0);raw.lite.reset(480,480);
  for(const[owner,plies,kind]of [[hero.id,2,k],[-777,3,k],[dead.id,4,k],[lost.id,5,k],[hero.id,6,k],[hero.id,7,99],[0,8,k]])raw.lite.spawn(kind,0,0,1,owner,plies,-1,3);
  const deadRow=raw.lite.spawn(k,0,0,1,hero.id,9);raw.lite.free(deadRow);
 }
 if(mode.startsWith('vent')){raw.geysers=rollGeyserField(new Rng(44),{});anchorVent(raw.geysers,new Rng(45),{x:120,y:130},'hiss');}
 calls.length=0;events.length=0;const originalPool=raw.lite,originalIdx=raw.liteKindIdxMap,oldNext=Rng.prototype.next;
 Rng.prototype.next=function(){const before=this.snapshot(),v=oldNext.call(this);draws.push([before,v,this.snapshot()]);return v;};
 try{host.bootLite(zone,[{x:210,y:200}]);if(mode.startsWith('vent'))host.bootLiteVentSeats();}finally{Rng.prototype.next=oldNext;}
 assert.equal(raw.lite,originalPool);assert.equal(raw.liteKindIdxMap,originalIdx);
 if(mode==='carry'){
  assert.equal(raw.lite.liveCount,2);assert.deepEqual([raw.lite.plies[0],raw.lite.plies[1]],[2,6]);assert.deepEqual([raw.lite.owner[0],raw.lite.owner[1]],[hero.id,hero.id]);
  assert.equal(raw.lite.story[0],0);assert.equal(raw.lite.story[1],0); // exact native carry semantics, no invented floor migration
  raw.actors=[];host.bootLite(zone,[]);assert.equal(raw.lite.liveCount,0); // old keeper is no longer in the authoritative census
 }else if(mode.endsWith('deferred')){assert.equal(raw.lite.liveCount,0);assert.equal(raw.liteWhenCueDraws.length,1);assert.equal(raw.liteWhenCueDraws[0],row.when);assert.ok(raw.litePockets.length>0);}
 else if(mode==='absent'){assert.equal(raw.lite.liveCount,0);assert.equal(raw.liteWhenCueDraws.length,0);}
 else if(mode==='full')assert.equal(raw.lite.liveCount,2);else assert.equal(raw.lite.liveCount,4);
 if(mode.startsWith('vent'))assert.equal(raw.liteVentRows.length,0);
 return {events,calls,draws,state:clean(Object.fromEntries(Object.keys(state).map(k=>[k,raw[k]]))),doodads:clean(raw.doodads)};
});}
const rows:any[]=[];for(const mode of ['carry','immediate','deferred','absent','full','vent','vent-deferred']){const before=run(false,mode),after=run(true,mode);assert.deepEqual(after,before,mode);rows.push({mode,events:after.events.length,calls:after.calls.length,draws:after.draws.length});}
function binding(){
 const scene:any={zone:{},actors:[]},geometry:any={},population:any={input:{scene,geometry}},services:any={},environment:any={},state=freshSceneEcologyState(),sources={XP_SCALE:.8};
 const raw:any={scene,geometry,population,services,environment,state,sources},owner=new NativeAreaSceneEcology(raw);
 assert.equal(owner.input.scene,scene);assert.equal(owner.input.geometry,geometry);assert.ok(Object.isFrozen(owner.input));assert.ok(Object.isFrozen(owner.host));
 raw.scene={};raw.state={};assert.equal(owner.input.scene,scene);assert.equal(owner.input.state,state);
 let refused=0;for(const key of Object.keys(raw)){const bad:any={scene,geometry,population,services,environment,state,sources};let reads=0;Object.defineProperty(bad,key,{get(){reads++;return {};}});assert.throws(()=>new NativeAreaSceneEcology(bad));assert.equal(reads,0);refused++;}
 assert.throws(()=>new NativeAreaSceneEcology({scene,geometry:{},population,services,environment,state,sources} as any),/same mutable/);
 assert.throws(()=>new NativeAreaSceneEcology({scene:{},geometry,population,services,environment,state,sources} as any),/same mutable/);
 let selected=0;for(const[provider,name]of [[geometry,'interactSpot'],[geometry,'clampPos'],[geometry,'markDoodadsChanged'],[population,'createMonster'],[services,'radianceCondHeld']] as const){const calls:any[]=[];provider[name]=function(this:any){calls.push(['old',this===provider]);};const fn=(owner.host as any)[name];provider[name]=function(this:any){calls.push(['new',this===provider]);};fn();(owner.host as any)[name]();assert.deepEqual(calls,[['old',true],['new',true]]);selected++;}
 const actor=new Actor('replacement','player',{x:1,y:2});scene.actors=[actor];assert.equal(owner.actorById(actor.id),actor);scene.actors=[];assert.equal(owner.actorById(actor.id),undefined);
 delete services.radianceCondHeld;assert.throws(()=>owner.liteCondHeld({radiance:{from:0}}),/Missing native ecology capability/);
 return {refused,identityRefusals:2,selected,censusReplacement:true,missingCapabilityExplicit:true};
}
const result={pass:true,rows,binding:binding()};console.log('PASS independent carried/cue/receiver controls',JSON.stringify(result));

}


// True classic cached adapter: live roots, early method selection and no census pin.
let cachedSelections=0;
withSeededRandom(61991,()=>{
 const world:any=makeSimWorld('warrior',61991),actor=world.createMonster('zombie',10,'enemy');
 world.actors=[world.player,actor];const owned=new Map([['ecology-cache-witness',actor]]);
 assert.equal(massDormancyPins(world,owned).has(actor),false);
 const host=world.nativeSceneEcologyHost();assert.equal(host,world.nativeSceneEcologyHost());
 assert.equal(Object.getOwnPropertyDescriptor(world,'nativeSceneEcologyView')?.enumerable,false);
 assert.ok(!Object.keys(world).includes('nativeSceneEcologyView'));
 const changed=[actor,world.player];world.actors=changed;assert.equal(host.actors,changed);
 assert.equal(massDormancyPins(world,owned).has(actor),false);
 world.player.aiTargetId=actor.id;assert.equal(massDormancyPins(world,owned).has(actor),true);world.player.aiTargetId=-1;
 for(const [name,descriptor]of Object.entries(Object.getOwnPropertyDescriptors(host))){
  if(!descriptor.get||typeof host[name]!=='function'||typeof world[name]!=='function')continue;
  const prior=Object.getOwnPropertyDescriptor(world,name),calls:any[]=[],argument={name};
  try{
   Object.defineProperty(world,name,{configurable:true,writable:true,value:function(this:unknown,...args:unknown[]){calls.push(['old',this===world,args]);return 'old';}});
   const selected=host[name];
   Object.defineProperty(world,name,{configurable:true,writable:true,value:function(this:unknown,...args:unknown[]){calls.push(['new',this===world,args]);return 'new';}});
   assert.equal(selected(argument),'old');assert.equal(host[name](argument),'new');
   assert.equal(calls[0][2][0],argument);assert.deepEqual(calls,[['old',true,[argument]],['new',true,[argument]]]);cachedSelections++;
  }finally{if(prior)Object.defineProperty(world,name,prior);else delete world[name];}
 }
});
assert.equal(cachedSelections,16);
console.log('PASS actual World ecology cache',cachedSelections,'method selections and true controller pin control');
