import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { updateAI } from '../src/engine/ai';
import { massAdventure } from '../src/worldmass/preset';
import { WorldMassRuntime } from '../src/worldmass/runtime';
import { validateMassTerritory } from '../src/worldmass/territory';

const restore=seedGlobalRandom(4418);
const cfg=structuredClone(massAdventure());
delete cfg.settlement;delete cfg.journey;delete cfg.ecology;delete cfg.progression;delete cfg.rewards;
delete cfg.terrain.patches;delete cfg.terrain.landforms;delete cfg.terrain.regionalDiscoveries;delete cfg.terrain.nativeRegional;
cfg.terrain.fields =[];cfg.terrain.surfaces=[{id:'plain',source:'test/plain',priority:0,when:[],region:'ground',color:'#424b32',biome:'downs'}];
cfg.terrain.places=[{id:'wolves',version:1,content:'wolves',period:900,chance:1,radius:150,jitter:0,priority:1,when:[]}];
cfg.content=[{id:'wolves',source:'test/wolves',level:1,count:1,table:[{id:'plains_wolf',weight:1}]}];
cfg.populationRadius=950;cfg.startRadius=0;
for(const patch of [null,{}, {source:'x',radius:NaN},{source:'x',radius:0},{source:'x',radius:4097},{source:'',radius:600},{source:4,radius:600}])
 assert.throws(()=>validateMassTerritory(patch as any),/Invalid worldmass territory/);
for(const radius of [128,4096])validateMassTerritory({source:'test/range',radius});
const invalid=structuredClone(cfg);(invalid as any).territory=null;
assert.throws(()=>new WorldMassRuntime(42,'invalid',invalid),/Invalid worldmass territory/);
console.log('PASS territory descriptors reject invalid bounds and accept the configured range');

const w=makeSimWorld('rogue',42),m=new WorldMassRuntime(42,'territory',cfg);m.attach(w);
const wolf=w.actors.find(a=>a.defId==='plains_wolf')!;
assert.ok(wolf);const home={...wolf.aiAnchor!},radius=cfg.territory!.radius;
assert.deepEqual(wolf.aiTerritory,{...cfg.territory,heal:false});
w.player.pos={x:home.x+radius+1200,y:home.y};
wolf.life*=.43;const wound=wolf.life;
wolf.pos={x:home.x+radius+40,y:home.y};wolf.aiTargetId=w.player.id;wolf.aggroed=true;
updateAI(wolf,w,1/60);
assert.equal(wolf.aiPhase,'leash_home');assert.equal(wolf.aiTargetId,undefined);
assert.equal(wolf.aggroed,false);assert.equal(wolf.life,wound);
assert.ok(wolf.pos.x<home.x+radius+40);assert.deepEqual(wolf.aiAnchor,home);
wolf.pos={x:home.x+radius*.8,y:home.y};
updateAI(wolf,w,1/60);
assert.equal(wolf.aiPhase,'leash_home');assert.equal(wolf.life,wound);
const snapshot=m.snapshot(w);
const again=makeSimWorld('rogue',9),continued=new WorldMassRuntime(42,'territory',cfg,snapshot);
continued.attach(again,snapshot);
const same=again.actors.find(a=>a.defId===wolf.defId&&a.aiAnchor?.x===home.x&&a.aiAnchor?.y===home.y)!;
assert.ok(same);assert.equal(same.life,wound);assert.equal(same.aiPhase,'leash_home');
assert.deepEqual(same.aiTerritory,wolf.aiTerritory);assert.deepEqual(same.aiAnchor,home);
const before=same.pos.x;updateAI(same,again,1/60);
assert.ok(same.pos.x<before);assert.equal(same.life,wound);
wolf.pos={x:home.x+radius*.5,y:home.y};updateAI(wolf,w,1/60);
assert.notEqual(wolf.aiPhase,'leash_home');
console.log('PASS native return drops pursuit, walks without healing and retains home/wounds/hysteresis through Continue');

wolf.pos={x:home.x+radius+20,y:home.y};wolf.aiPhase='';
wolf.aiTuning={target:{leash:{radius:1000,heal:true}}};
updateAI(wolf,w,1/60);assert.notEqual(wolf.aiPhase,'leash_home');
wolf.pos={x:home.x+1040,y:home.y};updateAI(wolf,w,1/60);
assert.equal(wolf.aiPhase,'leash_home');
updateAI(wolf,w,1/60);assert.ok(wolf.life>wound,'authored healing retains native authority');
wolf.aiPhase='';wolf.aiTuning={target:{relentless:true}};wolf.pos={x:home.x+1040,y:home.y};
updateAI(wolf,w,1/60);assert.notEqual(wolf.aiPhase,'leash_home','relentless tuning overrides only fallback');
wolf.aiTuning={target:{relentless:true,leash:{radius:200}}};updateAI(wolf,w,1/60);
assert.equal(wolf.aiPhase,'leash_home','explicit native leash retains its existing precedence');
console.log('PASS authored and dynamic leashes, healing and relentless phases retain native precedence');

const legacy=structuredClone(cfg);delete legacy.territory;
const old=makeSimWorld('rogue',8),oldMass=new WorldMassRuntime(42,'legacy-territory',legacy);oldMass.attach(old);
const oldWolf=old.actors.find(a=>a.defId==='plains_wolf')!;
assert.equal(oldWolf.aiTerritory,undefined);
oldWolf.pos.x+=1000;old.player.pos={x:oldWolf.pos.x+1200,y:oldWolf.pos.y};
updateAI(oldWolf,old,1/60);assert.notEqual(oldWolf.aiPhase,'leash_home');
const legacySave=oldMass.snapshot(old),older=makeSimWorld('rogue',10);
new WorldMassRuntime(42,'legacy-territory',legacy,legacySave).attach(older,legacySave);
assert.ok(older.actors.filter(a=>a.defId==='plains_wolf').every(a=>a.aiTerritory===undefined));
console.log('PASS absent saved territory retains old chase behavior on admission and Continue');
restore();
