import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { START_ZONE } from '../src/data/zones';
import { SALVAGE_CFG } from '../src/data/essences';
import { fontStandsIn } from '../src/engine/fontPlacement';
import { refugeDeparture } from '../src/engine/refugeDeparture';
import { serializeSnapshot, applySnapshot } from '../src/net/snapshot';

let failures = 0;
const check = (name: string, ok: boolean): void => { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`); if (!ok) failures++; };
seedGlobalRandom(8192);
const w = makeSimWorld('warrior', 8192);
const base = { ...w.zone, special: undefined, port: false, font: undefined };
check('safe settlements host Fonts', fontStandsIn({ ...base, objective: { kind: 'safe' } }));
check('ordinary combat ground has no Font', !fontStandsIn({ ...base, objective: { kind: 'clear', all: true } }));
check('harbors host Fonts', fontStandsIn({ ...base, objective: { kind: 'clear', all: true }, port: true }));
check('explicit Font overrides enable or disable authored sites', fontStandsIn({ ...base, font: true }) && !fontStandsIn({ ...base, font: false }));
w.loadZone(START_ZONE);
check('Lastlight creates a real Font', w.fonts.length === 1);
const f = w.fonts[0];
if (f) {
  const poll = (dt: number) => (w as unknown as { updateFont(dt: number): void }).updateFont(dt);
  w.fontDwellRequested = false;
  w.player.pos = { x: f.pos.x + 500, y: f.pos.y }; poll(0);
  w.player.pos = { ...f.pos }; w.player.push = null; w.player.casting = null;
  w.localSeat.lastActedAt = -100;
  poll(0);
  check('proximity alone does not open the Font', !w.fontDwellRequested);
  poll(SALVAGE_CFG.stationDwell + 0.1);
  check('Font still opens after a deliberate dwell', w.fontDwellRequested);
}
const rat = w.createMonster('gutter_rat', 1, 'enemy');
rat.refuge = { kind: 'tree', fx: 'scramble' };
rat.pos = { x: 700, y: 700 }; w.actors.push(rat);
const target = { x: 720, y: 700 };
const drops = w.drops.length, text = w.texts.length, xp = w.meta.xp;
w.fleeIntoRefuge(rat, target);
const cue = w.flashes.at(-1);
check('escape removes the body without a death, reward or narration', !w.actors.includes(rat) && !rat.dead && w.meta.xp === xp && w.drops.length === drops && w.texts.length === text);
check('climb records the original body and actual cover position', !!cue?.departure && cue.departure.body.look === rat.look && cue.departure.target.x === target.x && cue.departure.rise > 0);
rat.refuge = { kind: 'water' };
const dive = refugeDeparture(rat, target);
check('water uses a downward dive and splash instead of a climb', dive.cue.rise < 0 && dive.cue.fx === 'plunge');
const snap = JSON.parse(JSON.stringify(serializeSnapshot(w, 1)));
const replica = makeSimWorld('warrior', 8193);
applySnapshot(replica, snap);
check('co-op carries the complete visual departure', JSON.stringify(replica.flashes.at(-1)?.departure) === JSON.stringify(cue?.departure));
check('departure is a bounded transient', !!cue && cue.maxLife > 0 && cue.maxLife < 2);
if (failures) process.exitCode = 1;
