import assert from 'node:assert/strict';
import {exactNumber,fraction,nativeNumber,exactMappedPoint,mappedPoint,sampleMappedPoint,physicalAnchorForNative,validateMapping,type MassNativeMapping} from '../src/worldmass/nativeGeography';
import {createNativeGeographyReader} from '../src/world/geographySource';
import {captureNativeGeographySource} from '../src/world/captureGeography';
import {MassNativeGeography,makeMassNativeGeographySpec} from '../src/worldmass/nativeGeography';
import {canonical,massDigest} from '../src/worldmass/random';
const source=captureNativeGeographySource(713),sourceJson=JSON.stringify(source),reader=createNativeGeographyReader(source);
const spec:MassNativeMapping={schema:1,algorithm:'bigint-relative-native-map-v1',addressSpan:960,physicalOrigin:{dimension:'surface',cx:'9007199254740993',cy:'-9007199254740993',x:.25,y:959.5},nativeOrigin:{x:-35,y:160},physicalUnitsPerNativeUnit:{numerator:'20',denominator:'1'},nativeDimension:'surface',nativeBounds:{minX:-20000,minY:-20000,maxX:20000,maxY:20000},outsideDomain:'refuse',rounding:'nearest-binary64-ties-even-once'};
const checks:any[]=[];const check=(name:string,fn:()=>unknown)=>{checks.push({name,result:fn()??true});};
check('finite binary64 exact decomposition and roundtrip',()=>{const values=[0,-0,Number.MIN_VALUE,-Number.MIN_VALUE,Number.MAX_VALUE,1,-1,.1,-.3,2**-1022,2**53,Math.PI,-1234567.89];for(const v of values)assert.equal(nativeNumber(exactNumber(v)),v===0?0:v);return {n:values.length};});
check('ties to even at unity',()=>{const d=1n<<53n;assert.equal(nativeNumber(fraction(d+1n,d)),1);assert.equal(nativeNumber(fraction(d+3n,d)),1+2**-51);});
check('subnormal rounding and overflow',()=>{assert.equal(nativeNumber(fraction(1n,1n<<1075n)),0);assert.equal(nativeNumber(fraction(3n,1n<<1075n)),2*Number.MIN_VALUE);assert.throws(()=>nativeNumber(fraction(1n<<1024n)));});
check('both recorded origins align exactly',()=>assert.deepEqual(mappedPoint(spec,spec.physicalOrigin),spec.nativeOrigin));
check('large absolute cells preserve quarter offset',()=>{const at={...spec.physicalOrigin,x:.5};assert.deepEqual(exactMappedPoint(spec,at).x,fraction(-2799n,80n));assert.equal(mappedPoint(spec,at).x,-34.9875);});
check('adjacent cells above Number safe integer remain distinct',()=>{const at={...spec.physicalOrigin,cx:'9007199254740994'};assert.equal(mappedPoint(spec,at).x,13);assert.equal(Number(at.cx)-Number(spec.physicalOrigin.cx),2);return {exactPhysicalDelta:960,naivePhysicalDelta:(Number(at.cx)-Number(spec.physicalOrigin.cx))*960};});
check('negative relative cell subtraction and fractional carry',()=>{const at={...spec.physicalOrigin,cy:'-9007199254740992',y:.5};assert.equal(mappedPoint(spec,at).y,160.05);});
check('large translated frame produces identical native point',()=>{const at={...spec.physicalOrigin,cx:'9007199254740994',x:2.25};const moved={...spec,physicalOrigin:{...spec.physicalOrigin,cx:'0',cy:'0'}};assert.deepEqual(mappedPoint(spec,at),mappedPoint(moved,{...at,cx:'1',cy:'0'}));});
check('noninteger positive reduced ratio',()=>{const ratio={...spec,physicalUnitsPerNativeUnit:{numerator:'3',denominator:'2'}};assert.equal(mappedPoint(ratio,{...spec.physicalOrigin,x:3.25}).x,-33);});
check('invalid mappings and incompatible dimension refuse',()=>{for(const ratio of [{numerator:'0',denominator:'1'},{numerator:'02',denominator:'1'},{numerator:'20',denominator:'2'},{numerator:'1',denominator:'-1'}])assert.throws(()=>validateMapping({...spec,physicalUnitsPerNativeUnit:ratio}));assert.throws(()=>mappedPoint(spec,{...spec.physicalOrigin,dimension:'underworld'}));assert.throws(()=>mappedPoint(spec,{...spec.physicalOrigin,x:960}));return {n:6};});
check('signed64 edge origins work locally and far mapping refuses native domain',()=>{const extreme={...spec,physicalOrigin:{...spec.physicalOrigin,cx:'9223372036854775807',cy:'-9223372036854775808'}};assert.deepEqual(sampleMappedPoint(extreme,reader,extreme.physicalOrigin).native,spec.nativeOrigin);assert.throws(()=>sampleMappedPoint(extreme,reader,{...extreme.physicalOrigin,cx:'-9223372036854775808'}),/native geography|lattice|coordinate|mapping envelope/i);});
check('actual source point context and frame translation agree',()=>{const a=sampleMappedPoint(spec,reader,{...spec.physicalOrigin,x:20.25});const b=sampleMappedPoint({...spec,physicalOrigin:{...spec.physicalOrigin,cx:'0',cy:'0'}},reader,{...spec.physicalOrigin,cx:'0',cy:'0',x:20.25});assert.deepEqual(a,b);return {native:a.native,biome:a.biome,depth:a.depth};});
check('inverse authoritative atlas anchor keeps exact large physical frame',()=>{for(const native of [{x:-35,y:160},{x:-67.5,y:-8745},{x:9747.5,y:-6145}]){const at=physicalAnchorForNative(spec,native);assert.deepEqual(mappedPoint(spec,at),native);}assert.deepEqual(physicalAnchorForNative(spec,spec.nativeOrigin),spec.physicalOrigin);return {n:3};});

check('inverse authoritative anchors refuse physical rounding collapse and drift',()=>{
 const tiny={...spec,physicalUnitsPerNativeUnit:{numerator:'1',denominator:'9223372036854775807'}};
 assert.deepEqual(physicalAnchorForNative(tiny,tiny.nativeOrigin),tiny.physicalOrigin);
 assert.throws(()=>physicalAnchorForNative(tiny,{x:tiny.nativeOrigin.x+1,y:tiny.nativeOrigin.y}),/preserve the authoritative/);
 // Normal scales can also lose an exact target near origin cancellation.
 for(const x of [1/3,-1/3,Math.PI,-Math.PI])assert.throws(()=>physicalAnchorForNative(spec,{x,y:160}),/preserve the authoritative/);
 for(const x of [.1,-.1,100.1,1000.1])assert.deepEqual(mappedPoint(spec,physicalAnchorForNative(spec,{x,y:160})),{x,y:160});
 const m=new MassNativeGeography(makeMassNativeGeographySpec(sourceJson,tiny)),request=m.ownerContext('tiny-scale',tiny.physicalOrigin);
 assert.throws(()=>m.resolveOwnerContext(request,{resolvedOwnerId:'resolved/tiny',resolutionKey:'atlas/verified',nativeId:'native/tiny',resolvedTarget:{x:-34,y:160},resolvedSeed:991}),/preserve the authoritative/);
 return {collapsedRefusals:1,ordinaryFloatRefusals:4,preserved:5};
});
check('independent native division and binary64 roundtrip oracle',()=>{
 for(let i=1;i<=1536;i++){const n=(i*65537%99999989)*(i%2?-1:1),d=i*313%99991+1;assert.equal(nativeNumber(fraction(BigInt(n),BigInt(d))),n/d);}
 const view=new DataView(new ArrayBuffer(8));for(let i=1;i<=512;i++){const bits=(BigInt(i*104729)<<32n)|BigInt(i*15485863);view.setBigUint64(0,bits);const v=view.getFloat64(0);if(Number.isFinite(v))assert.equal(nativeNumber(exactNumber(v)),v===0?0:v);}return {divisionPairs:1536,binaryPairs:512};
});
const savedSpec=makeMassNativeGeographySpec(sourceJson,spec),mapped=new MassNativeGeography(savedSpec);
check('native bytes survive canonical parent cloning',()=>{const restored=new MassNativeGeography(JSON.parse(canonical(savedSpec)));assert.equal(restored.spec.sourceJson,sourceJson);assert.equal(restored.identity,mapped.identity);assert.deepEqual(restored.pointAt(spec.physicalOrigin),mapped.pointAt(spec.physicalOrigin));mapped.assertCompatible(restored.spec);});
check('point context and owner context remain separate and stable',()=>{const anchor={...spec.physicalOrigin,x:20.25};const first=mapped.ownerContext('area/9007199254740993/0',anchor);mapped.pointAt({...anchor,x:121.75});const second=mapped.ownerContext(first.ownerId,anchor);assert.deepEqual(second,first);assert(!('tileset' in first));assert(!('depth' in first));assert(!('climate' in first));assert.deepEqual(first.requestedTarget,{x:-34,y:160});assert.equal(first.requestedSeed,mapped.restoreOwnerContext(JSON.parse(canonical(first))).requestedSeed);assert(Object.isFrozen(first.canonicalAnchor));assert.throws(()=>{(first.canonicalAnchor as any).x=2;});return {requestedSeed:first.requestedSeed,target:first.requestedTarget};});
check('atlas resolution can replace anchor seed and identity before mint',()=>{const request=mapped.ownerContext('candidate/east',spec.physicalOrigin);const resolved=mapped.resolveOwnerContext(request,{resolvedOwnerId:'atlas/inland-lake/713',resolutionKey:'atlas-v1/inland-lake/713',nativeId:'locale/inland-lake',resolvedTarget:{x:100.5,y:-220.25},resolvedSeed:991});assert.equal(resolved.resolvedSeed,991);assert.notEqual(resolved.request.requestedSeed,991);assert.deepEqual(mapped.nativePoint(resolved.physicalAnchor),resolved.resolvedTarget);assert.deepEqual(mapped.restoreResolvedOwnerContext(JSON.parse(canonical(resolved))),resolved);assert(!('tileset' in resolved));return {requestSeed:request.requestedSeed,resolvedSeed:resolved.resolvedSeed,physicalAnchor:resolved.physicalAnchor};});
check('context tampering and source conflict refuse before publication',()=>{const clone=(v:unknown):any=>JSON.parse(JSON.stringify(v));const request=mapped.ownerContext('stable',spec.physicalOrigin);const changed=clone(request);changed.requestedSeed^=1;assert.throws(()=>mapped.restoreOwnerContext(changed));const changedTarget=clone(request);changedTarget.requestedTarget.x++;assert.throws(()=>mapped.restoreOwnerContext(changedTarget));const changedSource=clone(savedSpec);const altered=JSON.parse(sourceJson);altered.seed=991;changedSource.sourceJson=JSON.stringify(altered);assert.throws(()=>mapped.assertCompatible(changedSource));changedSource.sourceHash=massDigest(changedSource.sourceJson);assert.throws(()=>mapped.assertCompatible(changedSource));assert.throws(()=>new MassNativeGeography({...savedSpec,version:2} as any));assert.throws(()=>new MassNativeGeography({...savedSpec,sourceJson:' '+sourceJson,sourceHash:massDigest(' '+sourceJson)}));return {n:6};});
check('declared envelope is checked before rounding and source domain remains authoritative',()=>{const edge={...spec,nativeOrigin:{x:0,y:0},nativeBounds:{minX:-1,minY:-1,maxX:1,maxY:1}};assert.equal(mappedPoint(edge,{...spec.physicalOrigin,x:20.25}).x,1);assert.throws(()=>mappedPoint(edge,{...spec.physicalOrigin,x:20.250000000000004}),/envelope/);const broad={...spec,nativeBounds:{minX:-Number.MAX_VALUE,minY:-Number.MAX_VALUE,maxX:Number.MAX_VALUE,maxY:Number.MAX_VALUE}};const distant=new MassNativeGeography(makeMassNativeGeographySpec(sourceJson,broad));assert.throws(()=>distant.nativePoint({...spec.physicalOrigin,cx:'-9223372036854775808'}),/lattice|native geography/);});
check('constructors copy and freeze; dynamic properties never execute',()=>{const clone=JSON.parse(JSON.stringify(spec));const m=new MassNativeGeography(makeMassNativeGeographySpec(sourceJson,clone));clone.nativeOrigin.x=100;assert.equal(m.nativePoint(spec.physicalOrigin).x,-35);assert(Object.isFrozen(m.spec.mapping.nativeBounds));let calls=0;const dynamic={...spec.physicalOrigin};Object.defineProperty(dynamic,'x',{get(){calls++;return 0;},enumerable:true});assert.throws(()=>m.nativePoint(dynamic));assert.equal(calls,0);assert.throws(()=>m.ownerContext('bad-address',{...spec.physicalOrigin,extra:1} as any));const random=Math.random;Math.random=()=>{throw Error('ambient RNG');};try{assert.deepEqual(m.ownerContext('stable-rng',spec.physicalOrigin),m.ownerContext('stable-rng',spec.physicalOrigin));}finally{Math.random=random;}});
console.log(JSON.stringify({status:'PASS',groups:checks.length,checks,sourceSeed:mapped.seed,sourceChecksum:mapped.spec.sourceHash,mappingChecksum:mapped.spec.mappingHash}));
