import assert from 'node:assert/strict';
import { ZONES, type ZoneDef } from '../src/data/zones';
import { SNOW_CFG } from '../src/engine/snowCover';
import type { WeatherFront } from '../src/world/weather';
import { address, moveAddress } from '../src/worldmass/address';
import { canonical } from '../src/worldmass/random';
import { MassSnow, MASS_SNOW_DEFAULT } from '../src/worldmass/snow';
const origin=address('surface','0','0',0,0,960), other=moveAddress(origin,{x:1350,y:0},960);
const zone:ZoneDef={...ZONES.lastlight,theme:{...ZONES.lastlight.theme,heat:0}};
const front:WeatherFront={kind:'snow',pos:{x:0,y:0},vel:{x:1,y:0},radius:100,intensity:.8,age:90,life:200};
let snowfall:WeatherFront|null=front,samples=0;
const snow=new MassSnow(960,1350,MASS_SNOW_DEFAULT,()=>zone,()=>{samples++;return snowfall;});
assert.equal(snow.at(origin),SNOW_CFG.frozenBaseline);assert.equal(snow.count,0,'reading untouched ground never creates a save row');
snow.update(10,10,[origin,moveAddress(origin,{x:400,y:400},960),origin]);
assert.equal(samples,1);assert.equal(snow.count,1);assert.equal(snow.at(origin),SNOW_CFG.frozenBaseline+10*.8/SNOW_CFG.accumulateSec);
assert.equal(snow.at(other),SNOW_CFG.frozenBaseline);const before=snow.at(origin);
snow.update(10,10,[origin]);assert.equal(snow.at(origin),before,'same frame never double integrates');
snow.update(10,20,[other]);assert.equal(snow.at(origin),before);const saved=JSON.parse(JSON.stringify(snow.snapshot()));
const n=new MassSnow(960,1350,MASS_SNOW_DEFAULT,()=>zone,()=>snowfall,saved);assert.deepEqual(n.snapshot(),saved);
n.update(1,50000,[origin]);assert.equal(n.at(origin),before+.8/SNOW_CFG.accumulateSec,'50,000-second absence freezes ground instead of inventing snowfall');
assert.equal(n.at(other),snow.at(other));
console.log('PASS native snow amount, exact chunk ownership, once-per-frame integration, sparse reads, dormant freezing and JSON Continue');

snowfall=null;const warm={...zone,theme:{...zone.theme,heat:.8}};
const melting=new MassSnow(960,1350,MASS_SNOW_DEFAULT,()=>warm,()=>null,saved);
melting.update(5,25,[origin]);assert.equal(melting.at(origin),Math.max(0,before-5*.8/SNOW_CFG.meltSecAtHeat1));
melting.update(500,525,[origin]);assert.equal(melting.at(origin),0);assert.equal(melting.at(other),snow.at(other));
const bad=JSON.parse(JSON.stringify(saved));bad.rows[0].center.x+=1;assert.throws(()=>new MassSnow(960,1350,MASS_SNOW_DEFAULT,()=>zone,()=>null,bad),/owner/);
assert.throws(()=>n.update(1,-1,[origin]),/clock/);
const huge=address('surface','9007199254740993','-9007199254740993',.25,.75,960);
n.update(1,50001,[huge]);assert.equal(n.count,3);assert.equal(n.at(huge),SNOW_CFG.frozenBaseline);
assert.ok(canonical(n.snapshot()).includes('900719925474099'));
console.log('PASS native warm-ground melt/clamps, isolated neighboring cover, precise distant chunk ownership and malformed-state refusal');
