import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { FEATURE, makeAccount, serializeAccount, deserializeAccount, isSkillUnlockedForDrop, isClassUnlocked, STARTER_SKILLS } from '../src/meta/account';
import { CLASS_BUNDLES, classUnlockFor, acknowledgeClassUnlock, isSkillUnlockedForSelection } from '../src/meta/unlocks';
import { ORACLE_RESCUED } from '../src/data/oracle';
import { oracleCommanderId, revengeCommanderId } from '../src/quests/revenge';
import { questRewardChoices } from '../src/engine/questRewardChoices';
import { QUESTS } from '../src/quests/defs';
import { townTier, TOWN_TIERS } from '../src/data/townBuild';
import { STRUCTURE_SERVICE_SIGNS } from '../src/data/structures';
import { LOOKS } from '../src/data/looks';
import { autoPlace } from '../src/engine/inventory';
import { forgeItem } from '../src/engine/itemgen';
import { serializeCharacter, applySavedCharacter } from '../src/meta/character';

const a = makeAccount();
const b = CLASS_BUNDLES.find(b => !a.unlockedClasses.has(b.classId) && b.skillIds.some(id => !a.unlockedSkills.has(id)))!;
const id = b.skillIds.find(id => !a.unlockedSkills.has(id))!;
a.unlockedClasses.add(b.classId); a.pendingClassUnlocks.add(b.classId);
for (const sid of b.skillIds) a.unlockedSkills.add(sid);
assert(isSkillUnlockedForDrop(a, id)); assert(!isSkillUnlockedForSelection(a, id));
assert(!isClassUnlocked(a, b.classId));
const repeat = QUESTS[oracleCommanderId('goblin')];
assert(!questRewardChoices(a, repeat).some(c => c.id === id));
assert(acknowledgeClassUnlock(a, classUnlockFor(b.classId)!));
assert(isSkillUnlockedForSelection(a, id)); assert(questRewardChoices(a, repeat).some(c => c.id === id));
a.pendingClassUnlocks.add(b.classId); a.explicitSkillUnlocks.add(id);
assert(isSkillUnlockedForSelection(a, id), 'independent ownership survives a pending shared class');
const legacy = serializeAccount(a); delete legacy.explicitSkillUnlocks;
assert(!isSkillUnlockedForSelection(deserializeAccount(legacy)!, id), 'ambiguous old pending-only ownership is conservatively drop-only');
assert(isSkillUnlockedForSelection(deserializeAccount(serializeAccount(a))!, id));
assert(STARTER_SKILLS.every(s => isSkillUnlockedForSelection(a, s)));
console.log('PASS selection distinguishes discovery, activation, independent/shared grants, starters and old saves');

assert(LOOKS.npc_oracle_bound.parts.some(p => p.kind === 'captiveCage'));
assert(!LOOKS.npc_scholar.parts.some(p => p.kind === 'captiveCage'));
const w = makeSimWorld('warrior', 17631); w.loadZone('lastlight');
assert.equal(w.townTierIndex(), 0);
assert(w.doodads.some(d => d.kind === 'service_sign_inn'));
assert(w.doodads.some(d => d.kind === 'service_sign_smith'));
assert(!w.zone.fixtures?.some(f => f.structure === 'oracle_home'));
w.account.ledger[ORACLE_RESCUED] = 1; w.loadZone('lastlight');
assert.equal(w.townTierIndex(), 1); assert.equal(w.arena.w, TOWN_TIERS[1].w);
assert(w.zone.fixtures?.some(f => f.structure === 'oracle_home'));
assert(w.doodads.some(d => d.kind === 'service_sign_oracle'));
w.account.features.add(FEATURE.QUEST_GIVER); w.loadZone('lastlight');
assert(STRUCTURE_SERVICE_SIGNS.every(s => w.doodads.some(d => d.kind === s.kind)));
w.odyssey.update(); assert(w.activeQuests.some(q => q.questId === repeat.id));
assert(!w.activeQuests.some(q => q.questId === revengeCommanderId('goblin')));
assert.equal(townTier(w.account), w.townTierIndex());
console.log('PASS cage/free looks, immediate town growth, residence and all four physical service signs');

w.player.invulnerable = true; w.player.level = 14;
w.loadZone(`quest_${repeat.id}`); w.questRescues.update();
assert(!w.actors.some(a => a.defId === 'townsfolk_oracle'), 'no second captivity');
assert(!w.claimQuestReward(repeat.id, STARTER_SKILLS[0]));
for (const enemy of [...w.actors]) if (enemy.team === 'enemy' && !enemy.invulnerable && !enemy.dead) w.kill(enemy, false, w.player);
w.update(1 / 60); assert(w.completedObjectives.has(w.zone.id));
assert(!w.claimQuestReward(repeat.id, STARTER_SKILLS[0]), 'no remote reward');
w.loadZone('lastlight');
const oracle = w.actors.find(a => a.defId === 'townsfolk_oracle')!;
w.player.pos = { x: oracle.pos.x + 20, y: oracle.pos.y };
const offers = w.questRewardOffers().find(q => q.questId === repeat.id)!; assert(offers.choices.length);
const chosen = offers.choices[0].id;
assert(!w.claimQuestReward(repeat.id, 'not-a-skill'));
assert(!w.claimQuestReward(repeat.id, chosen, { ...w.localSeat, id: 'guest' }));
w.meta.items.length = 0;
while (autoPlace(w.meta.items, forgeItem({ ilvl: 1, baseId: 'relic_charm', rarity: 'magic', affixes: [{ id: 'relic_life' }], quality: 1 })!)) { /* full pack */ }
assert(!w.claimQuestReward(repeat.id, chosen));
w.meta.items.length = 0;
const saved = JSON.parse(JSON.stringify(serializeCharacter(w)));
const back = makeSimWorld('warrior', 17631); Object.assign(back.account, deserializeAccount(serializeAccount(w.account))!);
assert(applySavedCharacter(back, saved)); assert(back.adoptWorldState(saved.world)); back.resumeSpawn('exact', saved.world.player);
assert(back.claimQuestReward(repeat.id, chosen)); assert(!back.claimQuestReward(repeat.id, chosen));
const memory = back.meta.items.find(i => i.gem?.kind === 'skill'); assert(memory && memory.gem?.kind === 'skill');
assert.equal(memory.gem.skillId, chosen); assert.equal(memory.gem.rarity, 'magic'); assert.equal(memory.gem.level, 1);
back.odyssey.update(); assert(!back.activeQuests.some(q => q.questId === repeat.id));
console.log('PASS actual repeat commander, deferred full-pack reward, save, host-only magic selection and once-per-life payout');

const oldTown = makeSimWorld('warrior', 819); oldTown.loadZone('lastlight');
const oldSave = JSON.parse(JSON.stringify(serializeCharacter(oldTown)));
oldSave.world.player.x = 1230; oldSave.world.player.y = 330;
const grown = makeSimWorld('warrior', 819); grown.account.ledger[ORACLE_RESCUED] = 1;
assert(applySavedCharacter(grown, oldSave)); assert(grown.adoptWorldState(oldSave.world));
grown.resumeSpawn('exact', oldSave.world.player);
assert.equal(grown.townTierIndex(), 1); assert.equal(grown.arena.w, TOWN_TIERS[1].w);
assert(Math.hypot(grown.player.pos.x - 1230, grown.player.pos.y - 330) > 40, 'old coordinates must not bury the player inside a relocated inn');
console.log('PASS older hamlet saves wake safely when account rescue expands the town');
