import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { serializeCharacter } from '../src/meta/character';
import { captureZoneContents } from '../src/engine/zonecontents';
import { WorldMassRuntime } from '../src/worldmass/runtime';
import { nativeMassAltar } from '../src/worldmass/fields';
import { massAdventure } from '../src/worldmass/preset';
import { canonical } from '../src/worldmass/random';
import { ALTARS } from '../src/data/shrines';
import { altarInfluences } from '../src/engine/altarCues';
import { serializeSnapshot, applySnapshot } from '../src/net/snapshot';

// Keep the actual legacy policy under test as the default adds repeated fields.
const finiteAdventure=()=>{
 const config=JSON.parse(canonical(massAdventure()));
 delete config.fieldResidency;
 // Preserve the legacy field-only fixture; native puzzle fixtures have their own residency.
 for(const c of config.content)if(c.site?.puzzles){delete c.site.puzzles;c.count=3;}
 const repeated=new Set(config.content.filter((c:any)=>c.site?.altars?.length).map((c:any)=>c.id));
 config.terrain.places=config.terrain.places.filter((p:any)=>!repeated.has(p.content));
 config.terrain.version=6;
 return config;
};
const restore=seedGlobalRandom(18431);
const w=makeSimWorld('warrior',431), base=JSON.parse(canonical(finiteAdventure()));
delete base.progression;base.content.find((c:{id:string})=>c.id==='memorial-grove').level=7;
const m=new WorldMassRuntime(431,'field-level',base);m.attach(w);
const place=m.journey!.places.find(p=>p.content==='memorial-grove')!;
assert.ok(place);
w.player.pos=m.journey!.local(place);m.update(w,true);
const altar=w.altars.find(a=>a.massSource)!;
assert.ok(altar && altar.def.id==='mending_altar');
assert.equal(altar.level,m.populationFor(place).level);
assert.equal(w.pointInSolid(altar.pos.x,altar.pos.y,16)?.kind,'altar_plinth','the drawn stone slab has a native footprint');
assert.ok(!w.pointInSolid(altar.pos.x+50,altar.pos.y,16),'body-clear approach beside the slab stays open');
m.update(w,true);assert.equal(w.altars.filter(a=>a.massSource===altar.massSource).length,1);
assert.equal(captureZoneContents(w).altars.some(a=>a.pos.x===altar.pos.x&&a.pos.y===altar.pos.y),false,'one checkpoint owner, no generic duplicate');
const pulse=(world:typeof w,dt:number)=>(world as unknown as {updateAltars(dt:number):void}).updateAltars(dt);
const enemy=w.createMonster('zombie',1,'enemy'),outside=w.createMonster('zombie',1,'enemy');
w.actors.push(enemy,outside);
w.player.pos={...altar.pos};enemy.pos={x:altar.pos.x+40,y:altar.pos.y};
outside.pos={x:altar.pos.x+altar.def.radius+outside.radius+20,y:altar.pos.y};
w.player.life=20;enemy.life=10;outside.life=10;
w.flashes=[];
altar.mendTimer=.2;pulse(w,.19);
assert.equal(w.player.life,20);assert.equal(enemy.life,10);
pulse(w,.02);
const heal=altar.def.mend!.base+altar.def.mend!.perLevel*altar.level!;
assert.equal(w.player.life,20+heal);assert.equal(enemy.life,10+heal);assert.equal(outside.life,10);
const mendCues=w.flashes.filter(f=>f.feedingCue?.kind==='restore');
assert.equal(mendCues.length,2,'source cues name only actual recipients, including the enemy');
assert.deepEqual(mendCues.map(f=>f.feedingCue!.to),[w.player.pos,enemy.pos]);
assert.ok(mendCues.every(f=>f.pos.x===altar.pos.x&&f.pos.y===altar.pos.y&&f.color===altar.def.color));
const cueClient=makeSimWorld('warrior',734),cuePacket=serializeSnapshot(w,1);
applySnapshot(cueClient,cuePacket);
assert.equal(cueClient.flashes.filter(f=>f.feedingCue?.kind==='restore').length,2,'restoration kind survives native network presentation');
cuePacket.flashes.find(f=>f.feedingCue)!.feedingCue!.to.x=-999;
assert.equal(mendCues[0].feedingCue!.to.x,w.player.pos.x,'wire cannot mutate source outcome');
assert.notEqual(cueClient.flashes.find(f=>f.feedingCue)!.feedingCue!.to.x,-999);
const cueOnly=makeSimWorld('warrior',735);
cueOnly.altars=[{...altar,pos:{...cueOnly.player.pos},affected:new Set()}];
cueOnly.player.life=cueOnly.player.maxLife();cueOnly.altars[0].mendTimer=0;pulse(cueOnly,.01);
assert.ok(!cueOnly.flashes.some(f=>f.feedingCue),'full health invents no transfer');
cueOnly.player.life=10;cueOnly.altars[0].def=JSON.parse(JSON.stringify(altar.def));
cueOnly.altars[0].def.mend!.cue=false;cueOnly.altars[0].mendTimer=0;pulse(cueOnly,.01);
assert.ok(cueOnly.player.life>10&&!cueOnly.flashes.some(f=>f.feedingCue),'cue opt-out does not change healing');
console.log('PASS measured shared-field source/recipient cues, full-pool silence, opt-out and native wire copying');
w.player.pos={...outside.pos};const leftLife=w.player.life;
altar.mendTimer=0;pulse(w,.01);assert.equal(w.player.life,leftLife,'stepping outside leaves the shared healing field');
console.log('PASS geographic mending uses native pulse timing and fixed level for friend/foe, with a real outside');

altar.mendTimer=.67;
w.player.pos={x:-10000,y:-10000};m.update(w,true);
assert.ok(w.altars.includes(altar),'finite field remains resident with its clock across page departure');
const save=serializeCharacter(w), checkpoint=save.world!.worldmass!;
assert.equal(checkpoint.fields!.length,1);
const registry=ALTARS.find(a=>a.id==='mending_altar')!, radiusBefore=registry.radius;
registry.radius=42; // an updated registry must not retune the stored place
const next=makeSimWorld('warrior',832);
assert.ok(next.adoptWorldState(save.world));next.startWorldMass(checkpoint.state.run.seed,checkpoint);
const restored=next.altars.find(a=>a.massSource===altar.massSource)!;
assert.ok(restored);assert.equal(restored.mendTimer,.67);assert.equal(restored.level,altar.level);
assert.deepEqual(restored.def,altar.def);
registry.radius=radiusBefore;
next.player.pos={...restored.pos};next.player.life=20;
pulse(next,.66);assert.equal(next.player.life,20);
pulse(next,.02);assert.equal(next.player.life,20+heal);
next.massRuntime!.update(next,true);assert.equal(next.altars.filter(a=>a.massSource===altar.massSource).length,1);
console.log('PASS field source, descriptor and remaining pulse survive distant actual character Continue without duplication');

const config=JSON.parse(canonical(finiteAdventure()));
const grove=config.content.find((c:{id:string})=>c.id==='memorial-grove');
grove.site.altars=[nativeMassAltar('wrath_altar',0,-95)];
const boost=makeSimWorld('warrior',194), bm=new WorldMassRuntime(431,'wrath',config);bm.attach(boost);
const bp=bm.journey!.places.find(p=>p.content==='memorial-grove')!;
boost.player.pos=bm.journey!.local(bp);bm.update(boost,true);
const ba=boost.altars.find(a=>a.massSource)!, foe=boost.createMonster('zombie',1,'enemy');boost.actors.push(foe);
const baseline=boost.player.sheet.get('damage'),foeBase=foe.sheet.get('damage');
boost.player.pos={...ba.pos};foe.pos={x:ba.pos.x+25,y:ba.pos.y};pulse(boost,.01);
assert.ok(boost.player.sheet.get('damage')>baseline && foe.sheet.get('damage')>foeBase);
const cues=altarInfluences(boost.player,boost.altars);
assert.equal(cues.length,1);assert.equal(cues[0].source,'altar:'+ba.massSource);
assert.equal(cues[0].color,ba.def.color);
assert.equal(altarInfluences(foe,boost.altars).length,1,'the same source visibly influences the foe');
const granted=boost.player.sheet.getSourceMods(cues[0].source)!;
boost.player.sheet.removeSource(cues[0].source);
assert.equal(altarInfluences(boost.player,boost.altars).length,0,'membership alone cannot invent a modifier source');
boost.player.sheet.setSource(cues[0].source,granted);
ba.def={...ba.def,influenceCue:false};
assert.equal(altarInfluences(boost.player,boost.altars).length,0,'data may silence the cue without changing the field');
ba.def={...ba.def,influenceCue:true};
boost.player.tier=1;
assert.equal(altarInfluences(boost.player,boost.altars).length,0,'another story does not inherit a stale membership cue');
boost.player.tier=0;
foe.dead=true;assert.equal(altarInfluences(foe,boost.altars).length,0);foe.dead=false;
boost.player.pos={x:ba.pos.x+ba.def.radius+boost.player.radius,y:ba.pos.y};pulse(boost,.01);
assert.equal(altarInfluences(boost.player,boost.altars).length,1,'native body-edge contact remains affected');
boost.player.pos.x+=.01;pulse(boost,.01);
assert.equal(altarInfluences(boost.player,boost.altars).length,0,'native departure removes both source and sigil');
boost.player.pos={...ba.pos};pulse(boost,.01);
const applied=boost.player.sheet.get('damage');pulse(boost,.01);assert.equal(boost.player.sheet.get('damage'),applied,'native source cannot stack on re-entry updates');
boost.player.pos={x:ba.pos.x+500,y:ba.pos.y};foe.pos={...boost.player.pos};pulse(boost,.01);
assert.equal(boost.player.sheet.get('damage'),baseline);assert.equal(foe.sheet.get('damage'),foeBase);
assert.equal(altarInfluences(boost.player,boost.altars).length,0);assert.equal(altarInfluences(foe,boost.altars).length,0);
assert.equal(altarInfluences(w.player,w.altars).length,0,'pulse-only Mending keeps its actual-transfer cue');
console.log('PASS actual native modifier membership cues enter/leave both teams, honor contact, story, death, source and opt-out');
console.log('PASS a second native rule composes without bespoke combat code; modifiers enter and leave both teams exactly');

// Native localized storms keep their encounter level and remaining cadence.
const stormCfg=JSON.parse(canonical(finiteAdventure()));
delete stormCfg.progression;
stormCfg.content.find((c:{id:string})=>c.id==='fallen-court').level=7;
const stormWorld=makeSimWorld('warrior',923),stormRuntime=new WorldMassRuntime(431,'storm-field',stormCfg);
stormRuntime.attach(stormWorld);
const court=stormRuntime.journey!.places.find(p=>p.content==='fallen-court')!;
stormWorld.player.pos=stormRuntime.journey!.local(court);stormRuntime.update(stormWorld,true);
const storm=stormWorld.altars.find(a=>a.def.bolts)!;
assert.ok(storm?.massSource);assert.equal(storm.level,7);
const bolts=storm.def.bolts!;
stormWorld.player.level=40;
storm.boltTimer=.2;stormWorld.zones=[];
pulse(stormWorld,.19);assert.equal(stormWorld.zones.length,0);
pulse(stormWorld,.02);
const strike=stormWorld.zones[0];assert.ok(strike);
assert.equal(strike.delay,bolts.telegraph,'the native warning always precedes impact');
assert.equal(strike.caster.level,7);assert.equal(strike.inst.level,3);
assert.equal(strike.radius,bolts.radius);assert.ok(strike.hitAll&&strike.spareDormant&&strike.spareRoofed);
assert.ok(Math.hypot(strike.pos.x-storm.pos.x,strike.pos.y-storm.pos.y)<=storm.def.radius);
const originalCaster=strike.caster,originalPosition={...originalCaster.pos};
storm.boltTimer=0;pulse(stormWorld,.01);
assert.notEqual(stormWorld.zones[1].caster,originalCaster,'a later strike cannot move an in-flight source');
assert.deepEqual(originalCaster.pos,originalPosition);
stormWorld.zones=[strike];
const struck=stormWorld.createMonster('zombie',7,'enemy'),escaped=stormWorld.createMonster('zombie',7,'enemy');
stormWorld.actors=[stormWorld.player,struck,escaped];
stormWorld.player.pos={...strike.pos};struck.pos={...strike.pos};
escaped.pos={x:strike.pos.x+strike.radius+escaped.radius+20,y:strike.pos.y};
const lifeBefore=[stormWorld.player.life,struck.life,escaped.life];
const advanceZones=(dt:number)=>(stormWorld as unknown as {updateZones(dt:number):void}).updateZones(dt);
advanceZones(bolts.telegraph-.01);
assert.deepEqual([stormWorld.player.life,struck.life,escaped.life],lifeBefore,'no damage while warning remains');
advanceZones(.02);
assert.ok(stormWorld.player.life<lifeBefore[0]&&struck.life<lifeBefore[1],'native impact reaches both sides');
assert.equal(escaped.life,lifeBefore[2],'leaving the native strike radius avoids impact');
console.log('PASS native storm warning, fixed level, source isolation, friend/foe impact and spatial avoidance');

storm.boltTimer=.43;
const stormSave=stormRuntime.snapshot(stormWorld);
const stormNext=makeSimWorld('warrior',924),stormResume=new WorldMassRuntime(431,'storm-field',stormCfg,stormSave);
stormResume.attach(stormNext,stormSave);
const returnedStorm=stormNext.altars.find(a=>a.massSource===storm.massSource)!;
assert.equal(returnedStorm.boltTimer,.43);assert.equal(returnedStorm.level,7);
assert.equal(stormNext.zones.length,0,'Continue does not restore a partially elapsed damaging strike');
pulse(stormNext,.42);assert.equal(stormNext.zones.length,0);
pulse(stormNext,.02);
assert.equal(stormNext.zones[0].delay,bolts.telegraph,'the next restored beat starts a complete native warning');
const zeroSave=structuredClone(stormSave);
zeroSave.fields!.find(f=>f.id===storm.massSource)!.boltTimer=0;
const zeroWorld=makeSimWorld('warrior',925),zeroRuntime=new WorldMassRuntime(431,'storm-field',stormCfg,zeroSave);
zeroRuntime.attach(zeroWorld,zeroSave);pulse(zeroWorld,.01);
assert.equal(zeroWorld.zones[0].delay,bolts.telegraph,'a due-at-save beat cannot cause an unwarned arrival hit');
for(const value of [NaN,Infinity,-1]) {
 const bad=structuredClone(stormSave);bad.fields!.find(f=>f.id===storm.massSource)!.boltTimer=value;
 assert.throws(()=>new WorldMassRuntime(431,'bad',stormCfg,bad),/field checkpoint/);
}
for(const patch of [{ratePerSec:0},{ratePerSec:NaN},{radius:-1},{telegraph:0},{skillId:'missing'},{skillId:'toString'},{throughRoofs:'yes'}]) {
 const bad=structuredClone(stormCfg);
 Object.assign(bad.content.find((c:{id:string})=>c.id==='fallen-court').site.altars[0].def.bolts,patch);
 assert.throws(()=>new WorldMassRuntime(431,'bad',bad),/altar field|finite JSON/);
}
console.log('PASS storm cadence through Continue, complete re-warning and malformed field refusal');

const legacy=JSON.parse(canonical(finiteAdventure()));
for(const row of legacy.content)if(row.site)delete row.site.altars;
const old=makeSimWorld('warrior',733),om=new WorldMassRuntime(431,'legacy',legacy);om.attach(old);
old.player.pos=om.journey!.local(om.journey!.places.find(p=>p.content==='memorial-grove')!);om.update(old,true);
assert.equal(old.altars.some(a=>a.massSource),false);
const capped=JSON.parse(canonical(config));capped.maxPopulation=1;
const cw=makeSimWorld('warrior',712),cm=new WorldMassRuntime(431,'capped',capped);cm.attach(cw);
cw.player.pos=cm.journey!.local(cm.journey!.places.find(p=>p.content==='memorial-grove')!);cm.update(cw,true);
assert.equal(cw.altars.some(a=>a.massSource),false,'unadmitted encounter cannot expose a free field');
const repeated=JSON.parse(canonical(config));
repeated.terrain.places.push({...repeated.terrain.places[0],id:'illegal',content:'memorial-grove',radius:330});
assert.throws(()=>new WorldMassRuntime(431,'bad',repeated),/finite journey/);
const invalid=JSON.parse(canonical(config));invalid.content.find((c:{id:string})=>c.id==='memorial-grove').site.altars[0].def.radius=999;
assert.throws(()=>new WorldMassRuntime(431,'bad',invalid),/altar field/);
const unknown=JSON.parse(JSON.stringify(checkpoint));unknown.fields=[{id:'foreign'}];
const uw=makeSimWorld('warrior',721);
assert.throws(()=>new WorldMassRuntime(431,'bad',unknown.config,unknown).attach(uw,unknown),/Unknown saved/);
restore();
console.log('PASS legacy descriptors, bounded ownership, admission and malformed field refusal');
