import { DeedTracker, deedKey } from '../src/engine/deeds';
import { CLASS_DEEDS, COMBAT_DEEDS, DEED_CFG } from '../src/data/classdeeds';
import { CLASS_BUNDLES, classUnlockFor, settleClassUnlocks } from '../src/meta/unlocks';
import { makeAccount, serializeAccount, deserializeAccount } from '../src/meta/account';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { makeSkillInstance } from '../src/engine/skills';
import { SKILLS } from '../src/data/skills';
import { applyHit } from '../src/engine/damage';
import { mod } from '../src/engine/stats';
import type { Actor } from '../src/engine/actor';

let failed = 0;
function check(name: string, ok: boolean) { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`); if (!ok) failed++; }
const get = (ledger: Record<string, number>, id: string) => ledger[deedKey(id)] ?? 0;
const tracker = new DeedTracker(COMBAT_DEEDS), ledger: Record<string, number> = {};
tracker.record(ledger, { kind: 'block', value: 120 });
tracker.record(ledger, { kind: 'block', value: 80 });
check('one event feeds independent count and damage facts', get(ledger, 'blocks') === 2 && get(ledger, 'blocked_damage') === 200);
tracker.record(ledger, { kind: 'hit', keys: ['fire', 'fire', 'cold'] });
tracker.record(ledger, { kind: 'hit', keys: ['fire'] });
const resumed = deserializeAccount(serializeAccount({ ...makeAccount(), ledger }))!;
new DeedTracker(COMBAT_DEEDS).record(resumed.ledger, { kind: 'hit', keys: ['cold', 'lightning'] });
check('distinct elements survive account save/load without double counting', get(resumed.ledger, 'elements_landed') === 3);
tracker.record(ledger, { kind: 'hit', tags: ['projectile'], distance: 159 });
tracker.record(ledger, { kind: 'hit', tags: ['projectile'], distance: 160 });
check('range boundary and independent projectile total', get(ledger, 'distant_projectile_hits') === 1 && get(ledger, 'projectile_hits') === 2);
const first = {}, second = {};
tracker.record(ledger, { kind: 'poise', subject: first });
tracker.record(ledger, { kind: 'poise', subject: first });
tracker.record(ledger, { kind: 'poise', subject: second });
check('different enemies cannot add up to the deliberate Breaker deed', get(ledger, 'same_enemy_poise_breaks') === 2);
tracker.reset();
tracker.record(ledger, { kind: 'poise', subject: first });
check('travel/death resets the encounter but preserves its lifetime best', get(ledger, 'same_enemy_poise_breaks') === 2);
tracker.hurt(100, 29, 100, DEED_CFG.crisisEnter);
check('low-life oscillation cannot award an unfinished crisis', !tracker.recovered(31, 100, DEED_CFG.crisisRecover));
check('reaching the recovery boundary completes one crisis', tracker.recovered(60, 100, DEED_CFG.crisisRecover));
check('the same recovery cannot count twice', !tracker.recovered(100, 100, DEED_CFG.crisisRecover));
tracker.hurt(100, 29, 100, DEED_CFG.crisisEnter);
check('lowering maximum life cannot fake recovery', !tracker.recovered(29, 40, DEED_CFG.crisisRecover));
tracker.reset();
tracker.hurt(100, 20, 100, DEED_CFG.crisisEnter);
tracker.hurt(20, 0, 100, DEED_CFG.crisisEnter);
check('a fatal crisis grants no survived damage or recovery', !tracker.recovered(100, 100, DEED_CFG.crisisRecover) && tracker.heal(100) === 0);
check('all class-discovery rows are gameplay deeds', CLASS_BUNDLES.every(b => b.unlock.objectives?.length && b.unlock.objectives.every(r => !!r.ledger && !r.classLevel)));
check('all new class recipes use registered counters', Object.values(CLASS_DEEDS).every(d => COMBAT_DEEDS.some(r => deedKey(r.id) === d.objectives[0].ledger)));

seedGlobalRandom(0xd33d);
const w = makeSimWorld('warrior', 0xd33d), p = w.player;
const live = w as any;
function foe(): Actor {
  const e = w.createMonster('plains_wolf', 1, 'enemy');
  e.pos = { x: p.pos.x + 50, y: p.pos.y }; e.aiCooldown = 9999;
  e.sheet.setSource('deed-probe', [mod('life', 'override', 10000), mod('evasion', 'override', 0), mod('blockChance', 'override', 0), mod('poise', 'override', 0)]);
  e.fillResources(); w.actors.push(e); return e;
}
const e = foe();
p.sheet.setSource('deed-probe', [mod('life', 'override', 1000), mod('evasion', 'override', 0), mod('blockChance', 'override', 0), mod('poise', 'override', 0), mod('armour', 'override', 0)]);
p.fillResources();
const blow = makeSkillInstance({ ...SKILLS.firebolt, id: 'deed_probe_blow', tags: ['spell', 'physical'], baseDamage: { physical: [10, 10] }, effects: [{ type: 'damage' }] }, 1);
const hit = (caster: Actor, victim: Actor, inst = blow) => live.resolveHit(caster, inst, victim);
const n = (id: string) => get(w.account.ledger, id);
hit(e, p);
const lost = p.maxLife() - p.life;
check('real hostile hit stamps only life actually lost', lost > 0 && Math.abs(n('survived_hit_damage') - lost) < 0.001);
p.healBy(1000, true);
p.life -= 50; p.healBy(50);
check('silent regeneration consumes wound budget; later self-healing cannot recycle it', n('mended_wounds') === 0);
hit(e, p); p.healBy(1000);
check('real healing records the enemy wound once and excludes overheal', Math.abs(n('mended_wounds') - lost) < 0.001);
const hurtBefore = n('survived_hit_damage');
hit(p, p);
check('self-inflicted hits grant no survived damage', n('survived_hit_damage') === hurtBefore);
e.noBounty = true; hit(e, p); e.noBounty = false;
check('conjured/no-bounty attackers cannot farm defensive deeds', n('survived_hit_damage') === hurtBefore);
p.sheet.setSource('immune-probe', [mod('hitImmune', 'override', 1)]);
hit(e, p);
check('real evade stamps once', n('evades') === 1);
p.sheet.removeSource('immune-probe');
p.sheet.setSource('block-probe', [mod('blockChance', 'override', 1), mod('blockValue', 'override', 0), mod('blockPower', 'override', 0.5)]);
hit(e, p);
check('real passive block records stopped damage', n('blocks') === 1 && n('blocked_damage') > 0);
const passive = applyHit(e, p, { amounts: { physical: 1000 }, tags: new Set(['spell']), crit: false, sourceName: 'block probe' });
check('passive block result separates prevented damage from seep', (passive.blockedAmount ?? 0) > 0 && passive.total > 0 && passive.blockedAmount! < 1000);
p.sheet.removeSource('block-probe'); p.fillResources();
const guard = makeSkillInstance(SKILLS.shield_up, 1);
p.facing = 0;
p.casting = { mode: 'guard', inst: guard, aim: e.pos, remaining: 1, channelTime: 1, shield: 100, maxShield: 100 } as any;
live.tryGuardBlock(p, e, e.pos, 35);
check('raised guards feed the same block counters', n('blocks') === 2 && n('blocked_damage') >= 35);
p.casting = null;
const minion = foe(); minion.team = 'player'; minion.owner = p;
const victim = foe(); w.kill(victim, false, minion); w.kill(victim, false, minion);
check('owned companion kills count once', n('companion_kills') === 1);
const stranger = foe(); stranger.team = 'player'; w.kill(foe(), false, stranger);
check('unowned allies do not earn the local companion deed', n('companion_kills') === 1);
const swarmVictim = foe(); swarmVictim.life = 1;
live.litePooledHit(swarmVictim, { physical: 100 }, p);
check('pooled companion kills carry the keeper attribution exactly once', n('companion_kills') === 2);
const target = foe(); target.poise = 1;
target.sheet.setSource('poise-probe', [mod('poise', 'override', 10)]);
for (let i = 0; i < 3; i++) { target.poise = 1; target.poiseBroken = false; hit(p, target); }
check('three real poise breaks against one survivor complete Breaker', n('same_enemy_poise_breaks') === 3);
w.account.unlockedClasses.delete('breaker');
check('the real deed settles into a class claim', settleClassUnlocks(w.account).some(u => u.id === classUnlockFor('breaker')!.id));
p.fillResources();
const crisisStart = n('crises_recovered');
const crisisBlow = makeSkillInstance({ ...blow.def, baseDamage: { physical: [1, 1] } }, 1);
p.life = p.maxLife() * 0.30 + 0.1;
hit(e, p, crisisBlow); p.healBy(p.maxLife()); live.updateDeedRecovery();
check('a real hostile threshold crossing and recovery earns one crisis', n('crises_recovered') === crisisStart + 1);
live.updateDeedRecovery();
check('a later recovery sweep cannot duplicate the same crisis', n('crises_recovered') === crisisStart + 1);
const beforeCast = n('battle_cries');
w.executeSkill(p, makeSkillInstance(SKILLS.war_cry, 1), e.pos);
w.executeSkill(p, makeSkillInstance(SKILLS.war_cry, 1), e.pos, { noRepeat: true });
check('one deliberate warcry counts; its scheduled repeat does not', n('battle_cries') === beforeCast + 1);
const before = n('fire_hits');
live.metaProgressionActive = () => false;
hit(p, target, makeSkillInstance(SKILLS.firebolt, 1));
check('sealed mode stages grant no combat deeds', n('fire_hits') === before);

console.log(`\nClass deeds: ${failed ? `${failed} FAILED` : 'all passed'}`);
process.exitCode = failed ? 1 : 0;
