// ---------------------------------------------------------------------------
// ONE-OFF PROBE — THE CHARACTER SHEET AS DATA (data/sheet.ts). Pins the
// organization's structural honesty after a FULL engine boot (so every
// generated stat family has minted):
//   - every seated id (core/used, every category) EXISTS in STAT_DEFS —
//     a typo'd seat silently no-ops in the UI; here it fails,
//   - no id is seated twice (within or across categories, vitals included),
//   - every STATIC stat is seated, vital, or deliberately omitted — the
//     misc auto-fold is a runtime safety net, never an authoring license
//     (generated families are exempt: they seat by prefix),
//   - every static stat carries a BLURB (StatDef.desc) — a new stat brings
//     its player-facing line with it,
//   - every generated id resolves to a family seat, and every family seat
//     points at a real category and carries its shared blurb,
//   - the fold itself: a base-state sheet shows core rows only; touching a
//     stat surfaces exactly that row (visibility IS investment).
// Run: npx tsx balance/probe_sheet.ts
// ---------------------------------------------------------------------------

import { bootSimEngine } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { STAT_DEFS } from '../src/engine/stats';
import {
  SHEET_CATS, SHEET_FALLBACK_CAT, SHEET_FAMILY_SEATS, SHEET_OMIT, SHEET_VITALS,
  sheetFamilyOf, sheetTabs, statBlurbOf, statRestingValue,
} from '../src/data/sheet';

let failed = 0;
const check = (name: string, ok: boolean, detail = ''): void => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? ' — ' + detail : ''}`);
  if (!ok) failed++;
};

seedGlobalRandom(0xC0FFEE);
bootSimEngine(); // load the whole data layer — every generated family mints

// --- seated ids exist, and none twice --------------------------------------
const seatCount = new Map<string, number>();
const unknownSeats: string[] = [];
const seat = (id: string): void => {
  seatCount.set(id, (seatCount.get(id) ?? 0) + 1);
  if (!STAT_DEFS[id]) unknownSeats.push(id);
};
for (const id of SHEET_VITALS) seat(id);
for (const def of Object.values(SHEET_CATS)) {
  for (const id of def.core) seat(id);
  for (const id of def.used) seat(id);
}
check('every seated id exists in STAT_DEFS', unknownSeats.length === 0, unknownSeats.join(', '));
const doubled = [...seatCount].filter(([, n]) => n > 1).map(([id]) => id);
check('no id is seated twice', doubled.length === 0, doubled.join(', '));

// --- static coverage: seated, omitted, or generated ------------------------
const isGenerated = (id: string): boolean => sheetFamilyOf(id) !== null;
const unseated = Object.keys(STAT_DEFS).filter(id =>
  !seatCount.has(id) && !SHEET_OMIT.has(id) && !isGenerated(id));
check('every static stat is seated or omitted (no silent misc-folds)',
  unseated.length === 0, unseated.join(', '));

// --- blurb coverage --------------------------------------------------------
const silentStatics = Object.keys(STAT_DEFS).filter(id =>
  !isGenerated(id) && !SHEET_OMIT.has(id) && !STAT_DEFS[id].desc);
check('every static stat carries a blurb', silentStatics.length === 0,
  silentStatics.slice(0, 8).join(', ') + (silentStatics.length > 8 ? ` … +${silentStatics.length - 8}` : ''));
const silentGenerated = Object.keys(STAT_DEFS).filter(id =>
  isGenerated(id) && !statBlurbOf(id));
check('every generated id serves a family blurb', silentGenerated.length === 0,
  silentGenerated.slice(0, 8).join(', '));

// --- family seats point at real categories ---------------------------------
const badFamilyCats = SHEET_FAMILY_SEATS.filter(f => !SHEET_CATS[f.cat] || !f.blurb);
check('family seats name real categories and carry blurbs', badFamilyCats.length === 0,
  badFamilyCats.map(f => f.prefix).join(', '));
check('the fallback category exists', !!SHEET_CATS[SHEET_FALLBACK_CAT], SHEET_FALLBACK_CAT);
const generatedCount = Object.keys(STAT_DEFS).filter(isGenerated).length;
console.log(`      (${Object.keys(STAT_DEFS).length} stats total: ` +
  `${seatCount.size} seated, ${generatedCount} generated by family, ${SHEET_OMIT.size} omitted)`);

// --- the fold: visibility IS investment ------------------------------------
// A base sheet shows exactly the core rows. The base model mirrors the
// engine: StatSheet.get clamps to [min, max], so dials authored `base 0,
// min 0.5` (overdrive, trigger thresholds) REST at their floor — they must
// read untouched there, not "invested" on every fresh character.
const baseGet = (id: string): number => statRestingValue(id);
const baseTabs = sheetTabs(baseGet, false);
const coreOnly = baseTabs.every(t => t.rows.length === t.def.core.length && t.invested === 0);
check('a base-state sheet shows core rows only', coreOnly,
  baseTabs.map(t => `${t.cat}:${t.rows.length}/${t.def.core.length}`).join(' '));
const floorRested = (['overdriveIdleDelay', 'overdriveRecovery', 'triggerThreshold', 'triggerPower'] as const)
  .every(id => STAT_DEFS[id] && statRestingValue(id) > STAT_DEFS[id].base);
check('min-clamped dials rest at their floor (the fresh-sheet false-positive fix)', floorRested,
  `overdriveIdleDelay rests ${statRestingValue('overdriveIdleDelay')}`);

// Touch one used stat, one generated stat, and one core stat: exactly those
// surface (the core one only bumps the badge — it was already visible).
const touched: Record<string, number> = { lifeLeech: 0.05, poise: 40 };
const genId = Object.keys(STAT_DEFS).find(id => id.startsWith('apply_'));
if (genId) touched[genId] = 0.2;
touched.armor = 120; // defense core — visible either way
const touchedGet = (id: string): number => touched[id] ?? baseGet(id);
const t2 = sheetTabs(touchedGet, false);
const sus = t2.find(t => t.cat === 'sustain');
const dfn = t2.find(t => t.cat === 'defense');
const off = t2.find(t => t.cat === 'offense');
check('touching a used stat surfaces exactly its row',
  !!sus && sus.rows.includes('lifeLeech') && sus.rows.length === sus.def.core.length + 1
  && !!dfn && dfn.rows.includes('poise'),
  `sustain rows ${sus?.rows.length}, defense has poise: ${dfn?.rows.includes('poise')}`);
check('touching a generated stat folds it into its family seat',
  !genId || (!!off && off.rows.includes(genId)), genId ?? 'no apply_ family minted');
check('the invested badge counts touched rows',
  !!dfn && dfn.invested === 2 && !!sus && sus.invested === 1, // poise + armor; lifeLeech
  `defense ${dfn?.invested}, sustain ${sus?.invested}`);

// Show-all lists the whole static shelf — and still no untouched generated.
const t3 = sheetTabs(baseGet, true);
const allSeated = t3.every(t => t.rows.length === t.def.core.length + t.def.used.length && t.hidden === 0);
check('show-all lists every seated row and nothing generated', allSeated,
  t3.map(t => `${t.cat}:${t.rows.length}`).join(' '));

console.log(failed ? `\n${failed} FAILURES` : '\nALL PASS');
process.exit(failed ? 1 : 0);
