import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { START_ZONE } from '../src/data/zones';
import { dialogueConditionMet, npcDialogueReceipt } from '../src/engine/npcDialogues';
import { townStationFeatures } from '../src/data/townBuild';
import { serializeCharacter } from '../src/meta/character';

const restore=seedGlobalRandom(55531), receipt=npcDialogueReceipt('mireille_frontier_welcome');
for(const grown of [false,true]){
 const w=makeSimWorld('warrior',215);
 if(grown)for(const f of townStationFeatures())w.account.features.add(f);
 w.startWorldMass(451);
 const m=w.massRuntime!,town=m.settlement!,paths=m.journey!.departurePoints;
 assert.equal(paths.length,4);assert.equal(w.exits.length,0);
 assert.equal(w.localZoneAt(w.player.pos).id,START_ZONE);
 assert.equal(dialogueConditionMet(w,{fact:'oracleAtHome'}),true);
 assert.equal(w.npcDialogues.callout(true),null,'spawn is not a departure');
 const start=paths[0],dx=town.zone.size.w/2-start.x,dy=town.zone.size.h/2-start.y,d=Math.hypot(dx,dy);
 w.player.pos={x:start.x+dx/d*90,y:start.y+dy/d*90};w.player.tier=0;
 assert.ok(w.lineOfSight(w.player.pos,start,0,0));
 assert.equal(w.npcDialogues.callout(false),null);
 assert.equal(w.ledger[receipt],undefined,'hidden reader does not consume');
 const invitation=w.npcDialogues.callout(true)!;
 assert.ok(invitation);assert.equal(invitation.a.defId,'townsfolk_innkeep');
 assert.equal(invitation.delivery,'callout');assert.ok(!invitation.text.includes('Crossroads'));
 assert.equal(w.ledger[receipt],1);assert.equal(w.exits.length,0);
 w.player.pos={x:-600,y:-600};
 assert.equal(w.npcDialogues.callout(true),null,'leaving spatial town withdraws invitation');
 assert.equal(dialogueConditionMet(w,{fact:'oracleAtHome'}),false);
 const save=serializeCharacter(w),again=makeSimWorld('warrior',92);
 again.adoptWorldState(save.world);again.startWorldMass(451,save.world!.worldmass);
 again.ledger={...w.ledger};again.player.pos={x:start.x+dx/d*90,y:start.y+dy/d*90};
 assert.equal(again.npcDialogues.callout(true),null,'receipt survives Continue');
 assert.deepEqual(again.massRuntime!.journey!.departurePoints,paths);
 console.log('PASS continuous Lastlight optional welcome, local Oracle context and saved departure identity',grown);
}
const w=makeSimWorld('warrior',215);w.startWorldMass(452);w.npcDialogues.callout(true);
const p=w.massRuntime!.journey!.departurePoints[0];
w.player.pos={x:p.x+90,y:p.y};
const real=w.lineOfSight;w.lineOfSight=()=>false;
assert.equal(w.npcDialogues.callout(true),null);assert.equal(w.ledger[receipt],undefined);
w.lineOfSight=real;
w.player.tier=1;assert.equal(w.npcDialogues.callout(true),null);
w.player.tier=0;
assert.ok(w.npcDialogues.callout(true));
w.npcDialogues.finish(w.actors.find(a=>a.defId==='townsfolk_innkeep')!.id);
assert.equal(w.npcDialogues.callout(true),null);
console.log('PASS hidden approaches and upper floors refuse; dismissal does not repeat');
restore();
