import assert from 'node:assert/strict';
import { MassSurvey } from '../src/worldmass/survey';
import { MassState } from '../src/worldmass/state';
import { makeMassRun } from '../src/worldmass/generator';
import { massAdventure } from '../src/worldmass/preset';
import { address, cellKey, localOffset } from '../src/worldmass/address';
import { canonical } from '../src/worldmass/random';
import { WorldMassRuntime } from '../src/worldmass/runtime';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { serializeCharacter } from '../src/meta/character';
import { massMap } from '../src/worldmass/paint';

const config=massAdventure(),spec=config.survey!,span=config.terrain.addressSpan;
const state=new MassState(makeMassRun(42,'survey-unit',config.terrain),config.terrain.terrainCell);
const survey=new MassSurvey(state,spec);
const at=address('surface','9007199254740993','-9007199254740993',-12,12,span);
let calls=0;
survey.observe(at,target=>{calls++;return localOffset(target,at,span).x<0;});
assert.ok(calls>0&&calls<=256);
assert.ok(survey.known(at));
assert.ok(survey.known(address(at.dimension,at.cx,at.cy,at.x-240,at.y,span)));
assert.ok(!survey.known(address(at.dimension,at.cx,at.cy,at.x+240,at.y,span)));
assert.ok(!survey.known(address(at.dimension,at.cx,at.cy,at.x-720,at.y,span)));
const before=canonical(state.snapshot().claims),rev=state.terrainRevision;
survey.observe(at,target=>localOffset(target,at,span).x<0);
assert.equal(canonical(state.snapshot().claims),before);assert.equal(state.terrainRevision,rev);
const continued=new MassState(state.run,state.cell);continued.restore(state.snapshot());
assert.ok(new MassSurvey(continued,spec).known(at));
assert.ok(!new MassSurvey(continued,{...spec,source:'other-survey'}).known(at));
const mutable={...spec},owned=new MassSurvey(state,mutable);mutable.cell=0;mutable.source='changed';
assert.equal(owned.spec!.cell,spec.cell);assert.equal(owned.known(at),true);
console.log('PASS bounded sight admission, durable memory, negative/far addresses, source ownership and no terrain edits');
for(const bad of [null,{...spec,cell:0},{...spec,cell:31},{...spec,cell:60,radius:960},
 {...spec,radius:NaN},{...spec,radius:0},{...spec,source:''}])
 assert.throws(()=>new MassSurvey(state,bad as typeof spec));
const legacy=new MassSurvey(state);assert.equal(legacy.known(at),false);
state.claim('explored',cellKey(at));assert.equal(legacy.known(at),true);
assert.equal(legacy.observe(at,()=>{throw Error('Legacy does not cast survey rays');}),0);
console.log('PASS malformed and excessive survey refusal, exact legacy page knowledge');

const restore=seedGlobalRandom(1649);
try{
 const cfg=JSON.parse(canonical(config));
 delete cfg.settlement;delete cfg.journey;delete cfg.ecology;delete cfg.progression;
 delete cfg.terrain.patches;
 cfg.terrain.places=[];cfg.terrain.surfaces =[{id:'plain',source:'test/plain',priority:0,when:[],region:'ground',color:'#445522',biome:'downs'}];
 cfg.content=[];cfg.maxPopulation=0;
 const w=makeSimWorld('warrior',12),m=new WorldMassRuntime(42,'survey-native',cfg);
 for(let y=-600;y<=600;y+=30)m.state.paint({address:m.walk.at(240,y),region:'wall',color:'#666666',cause:'probe:survey-wall'});
 m.attach(w);
 const front=m.walk.at(180,60),behind=m.walk.at(420,60),far=m.walk.at(900,60);
 assert.ok(m.survey.known(front));assert.ok(!m.survey.known(behind));assert.ok(!m.survey.known(far));
 assert.ok(m.state.claimed('explored',cellKey(behind)),'residency page alone cannot reveal fine survey');
 assert.ok(!w.lineOfSight(w.player.pos,{x:420,y:60},w.player.tier),'native masonry blocks the sample');
 const claims=canonical(m.state.snapshot().claims),html=massMap(m,w.player.pos);
 assert.ok(html.includes('Survey of explored terrain'));
 assert.equal(canonical(m.state.snapshot().claims),claims,'map render cannot discover ground');
 for(let y=-600;y<=600;y+=30)m.state.paint({address:m.walk.at(240,y),region:'ground',color:'#445522',cause:'probe:removed-wall'});
 w.time+=.6;m.update(w);
 assert.ok(m.survey.known(behind),'native geometry changes expose newly visible ground');
 w.landPartyAt({x:-1200,y:60});m.update(w,true);
 assert.ok(m.survey.known(behind),'survey persists after residency crossing');
 const save=serializeCharacter(w),again=makeSimWorld('warrior',13);
 assert.ok(again.adoptWorldState(save.world));again.startWorldMass(42,save.world!.worldmass!);
 assert.equal(canonical(again.massRuntime!.state.snapshot().claims),canonical(m.state.snapshot().claims));
 assert.ok(again.massRuntime!.survey.known(behind));
 console.log('PASS native wall concealment/removal, read-only map, page crossing and exact Continue');
 const rock={kind:'rock' as const,pos:{x:2160,y:60},radius:90,rot:0,gone:false};
 w.doodads.push(rock);w.landPartyAt({x:1980,y:60});m.update(w,true);
 const screened=m.walk.at(2340,60);
 assert.ok(!w.lineOfSight(w.player.pos,{x:2340,y:60},w.player.tier));
 assert.ok(!m.survey.known(screened),'native solid scenery blocks survey');
 rock.gone=true;w.time+=.6;m.update(w);
 assert.ok(m.survey.known(screened),'native scenery removal releases the ray');
 console.log('PASS native solid scenery and removal use the same sight admission');
 delete cfg.survey;const oldWorld=makeSimWorld('warrior',14),old=new WorldMassRuntime(42,'old-survey',cfg);old.attach(oldWorld);
 assert.ok(old.survey.known(old.walk.at(900,60)));const oldSave=old.snapshot(oldWorld);
 const oldAgain=makeSimWorld('warrior',15);new WorldMassRuntime(42,'old-survey',cfg,oldSave).attach(oldAgain,oldSave);
 assert.equal(oldAgain.massRuntime!.config.survey,undefined);assert.ok(oldAgain.massRuntime!.survey.known(oldAgain.massRuntime!.walk.at(900,60)));
 console.log('PASS legacy descriptor and native Continue retain whole-page cartography');
}finally{restore();}
