import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { START_ZONE } from '../src/data/zones';
import { TOWN_PORTAL_CFG } from '../src/data/townportals';
import { SHRINES } from '../src/data/shrines';
import { FIXTURE_IDS } from '../src/data/monsters';
import { SKILLS } from '../src/data/skills';
import { makeSkillGem } from '../src/engine/skills';
import { captureZoneContents } from '../src/engine/zonecontents';
import type { World } from '../src/engine/world';
let failures = 0;
const check = (name: string, ok: boolean): void => { console.log(`${ok ? 'PASS' : 'FAIL'} ${name}`); if (!ok) failures++; };
const tick = (w: World, sec: number): void => { for (let t = 0; t < sec; t += 1 / 60) w.update(1 / 60); };
const portalTick = (w: World, sec: number): boolean =>
  (w as unknown as { updateTownPortals(dt: number): boolean }).updateTownPortals(sec);
const linger = (w: World): void => {
  const v = w.townPortalViews()[0];
  if (!v) throw new Error('Expected visible portal');
  w.player.pos = { x: v.pos.x + 150, y: v.pos.y }; portalTick(w, 0);
  w.player.pos = { ...v.pos }; w.player.push = null; w.player.casting = null;
  w.localSeat.lastActedAt = -100;
  portalTick(w, TOWN_PORTAL_CFG.dwellSeconds + 0.1);
};
seedGlobalRandom(7421);
const w = makeSimWorld('warrior', 7421);
w.zone.objective = { kind: 'clear', all: true };
const source = w.zone.id;
// Keep the combat floor occupied; no AI runs in this controlled fixture.
const cache = w.createMonster(FIXTURE_IDS.gem_cache, 1, 'enemy');
cache.fromZoneGen = true; cache.pos = { x: 200, y: 200 }; w.actors.push(cache);
const survivor = w.createMonster('skeleton_warrior', 1, 'enemy');
survivor.fromZoneGen = true; survivor.pos = { x: 250, y: 200 }; survivor.life = 17; w.actors.push(survivor);
w.chests = [{ pos: { x: 300, y: 300 }, kind: 'timed', mimic: false, opened: true, lockTime: 0, maxLock: 3 }];
w.shrines = [{ pos: { x: 400, y: 300 }, def: SHRINES[0], used: true }];
w.drops = [{ pos: { x: 420, y: 310 }, bob: 0, item: { kind: 'skill', inst: makeSkillGem(SKILLS.cleave, 1, 'common') } }];
cache.dead = true;
w.player.pos = { x: 700, y: 600 };
const origin = { ...w.player.pos };
check('cast starts through ordinary skill pipeline', w.castTownPortal());
tick(w, 2);
check('cast makes one owned portal without spending a gem', w.townPortals.length === 1 && w.townPortals[0].owner === w.localSeat.id);
check('dwell requires being near the portal', !portalTick(w, 2) && w.zone.id === source);
const before = captureZoneContents(w);
const survivorLife = survivor.life;
linger(w);
check('outbound dwell travels to configured town', w.zone.id === TOWN_PORTAL_CFG.destination);
check('arrival cannot instantly bounce back', !portalTick(w, 2) && w.zone.id === START_ZONE);
const door = w.doodads.find(d => d.door);
check('town has an actual door fixture', !!door?.door);
if (door?.door) w.setDoorState(door.door.id, 'open', { silent: true });
const doorId = door?.door?.id;
const saved = JSON.parse(JSON.stringify(w.serializeWorldState()));
w.time += 3600;
w.player.life = w.player.maxLife();
linger(w);
check('return lands at casting position', w.zone.id === source && Math.hypot(w.player.pos.x - origin.x, w.player.pos.y - origin.y) < 1);
check('used portal is consumed by configurable return policy', w.townPortals.length === 0);
check('dead cache stays dead beyond old expiry', !w.actors.some(a => a.defId === FIXTURE_IDS.gem_cache && !a.dead));
check('survivor health persists', w.actors.some(a => a.defId === survivor.defId && a.life === survivorLife));
check('opened chest and used shrine persist', w.chests[0]?.opened && w.shrines[0]?.used);
check('uncollected gem survives return', JSON.stringify(captureZoneContents(w).drops) === JSON.stringify(before.drops));
w.drops = []; w.loadZone(START_ZONE); w.loadZone(source);
check('picked-up loot does not reappear', w.drops.length === 0);
w.loadZone(START_ZONE);
check('town door remains open after leaving and re-entering', !!w.doodads.find(d => d.door?.id === doorId)?.door?.open);

const resumed = makeSimWorld('warrior', 9921);
check('town-side save adopts', resumed.adoptWorldState(saved));
resumed.resumeSpawn('exact', saved.player);
check('town endpoint survives save/load', resumed.townPortalViews().length === 1);
linger(resumed);
check('saved portal returns to same spent contents', resumed.zone.id === source && resumed.chests[0]?.opened && resumed.shrines[0]?.used);
resumed.loadZone(START_ZONE);
check('saved town door is open', !!resumed.doodads.find(d => d.door?.id === doorId)?.door?.open);
resumed.refreshZones();
check('campfire clears return passages', resumed.townPortals.length === 0);
check('campfire preserves town doors', !!resumed.doodads.find(d => d.door?.id === doorId)?.door?.open);
resumed.loadZone(source);
check('campfire refreshes spent chest state', !resumed.chests.some(c => c.opened));

// Nested cave route uses the same saved ladder as exact resume.
const enter = (seed: number): void => (resumed as unknown as {
  enterSidezone(cm: { pos: { x: number; y: number }; seed: number; kind: string }): void;
}).enterSidezone({ pos: { ...resumed.player.pos }, seed, kind: 'cave_entrance' });
enter(4242); enter(777);
const cave = resumed.zone.id;
resumed.player.cooldowns.clear(); resumed.player.useLock = 0;
check('portal can cast in a stable nested sidezone', resumed.castTownPortal());
tick(resumed, 2);
linger(resumed); linger(resumed);
check('round trip rebuilds the nested cave route', resumed.zone.id === cave && !!resumed.caveReturn);
resumed.zone.townPortals = false;
check('authored sealed zones refuse portal casts', !resumed.castTownPortal());
process.exitCode = failures ? 1 : 0;
