import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { START_ZONE } from '../src/data/zones';
import { NPC_DIALOGUES } from '../src/data/npcDialogues';
import { LEDGER_FLASK_LESSON } from '../src/meta/account';
import { dialogueConditionMet, npcDialogueReceipt } from '../src/engine/npcDialogues';
import { townStationFeatures } from '../src/data/townBuild';
import { serializeCharacter } from '../src/meta/character';

const restore=seedGlobalRandom(55531), receipt=npcDialogueReceipt('mireille_frontier_welcome');
for(const grown of [false,true]){
 const w=makeSimWorld('warrior',215);
 if(grown)for(const f of townStationFeatures())w.account.features.add(f);
 w.startWorldMass(451);
 const m=w.massRuntime!,town=m.settlement!,paths=m.journey!.departurePoints;
 const untouched=JSON.stringify([w.ledger,w.activeQuests,m.state.snapshot()]);
 const guide=w.npcDialogues.guidance();
 assert.equal(guide.length,1);assert.ok(guide[0].label.includes('Prepare flasks'));
 const inn=w.actors.find(a=>a.defId==='townsfolk_innkeep')!;
 assert.equal(guide[0].x,inn.pos.x);assert.equal(guide[0].y,inn.pos.y);
 assert.equal(JSON.stringify([w.ledger,w.activeQuests,m.state.snapshot()]),untouched,'guidance cannot grant, accept, admit or survey');
 assert.equal(paths.length,4);assert.equal(w.exits.length,0);
 assert.equal(w.localZoneAt(w.player.pos).id,START_ZONE);
 assert.equal(dialogueConditionMet(w,{fact:'oracleAtHome'}),true);
 assert.equal(w.npcDialogues.callout(true),null,'spawn is not a departure');
 const start=paths[0],dx=town.zone.size.w/2-start.x,dy=town.zone.size.h/2-start.y,d=Math.hypot(dx,dy);
 w.player.pos={x:start.x+dx/d*90,y:start.y+dy/d*90};w.player.tier=0;
 assert.ok(w.lineOfSight(w.player.pos,start,0,0));
 assert.equal(w.npcDialogues.callout(false),null);
 assert.equal(w.ledger[receipt],undefined,'hidden reader does not consume');
 const invitation=w.npcDialogues.callout(true)!;
 assert.ok(invitation);assert.equal(invitation.a.defId,'townsfolk_innkeep');
 assert.equal(invitation.delivery,'callout');assert.ok(!invitation.text.includes('Crossroads'));
 assert.equal(w.npcDialogues.guidance().length,1,'spoken invitation does not dismiss the unmet lesson guide');
 assert.equal(w.ledger[receipt],1);assert.equal(w.exits.length,0);
 w.player.pos={x:-600,y:-600};
 assert.equal(w.npcDialogues.callout(true),null,'leaving spatial town withdraws invitation');
 assert.equal(dialogueConditionMet(w,{fact:'oracleAtHome'}),false);
 assert.equal(w.npcDialogues.guidance().length,0,'unsafe country gets no sanctuary guidance');
 const save=serializeCharacter(w),again=makeSimWorld('warrior',92);
 again.adoptWorldState(save.world);again.startWorldMass(451,save.world!.worldmass);
 again.ledger={...w.ledger};again.player.pos={x:start.x+dx/d*90,y:start.y+dy/d*90};
 assert.equal(again.npcDialogues.callout(true),null,'receipt survives Continue');
 assert.deepEqual(again.massRuntime!.journey!.departurePoints,paths);
 assert.equal(again.npcDialogues.guidance().length,1,'unmet lesson guide survives spoken receipt and Continue');
 again.account.ledger[LEDGER_FLASK_LESSON]=1;
 assert.equal(again.npcDialogues.guidance().length,0,'native graduation removes the guide');
 console.log('PASS continuous Lastlight optional welcome, local Oracle context and saved departure identity',grown);
}
const w=makeSimWorld('warrior',215);w.startWorldMass(452);w.npcDialogues.callout(true);
const p=w.massRuntime!.journey!.departurePoints[0];
w.player.pos={x:p.x+90,y:p.y};
const real=w.lineOfSight;w.lineOfSight=()=>false;
assert.equal(w.npcDialogues.callout(true),null);assert.equal(w.ledger[receipt],undefined);
w.lineOfSight=real;
w.player.tier=1;assert.equal(w.npcDialogues.callout(true),null);
w.player.tier=0;
assert.ok(w.npcDialogues.callout(true));
w.npcDialogues.finish(w.actors.find(a=>a.defId==='townsfolk_innkeep')!.id);
assert.equal(w.npcDialogues.callout(true),null);
console.log('PASS hidden approaches and upper floors refuse; dismissal does not repeat');
const g=makeSimWorld('warrior',29);g.startWorldMass(42);
const definition=NPC_DIALOGUES.find(d=>d.id==='mireille_frontier_welcome')!,all=definition.all;
try {
 definition.all=[{fact:'unknown-mod-fact'}];
 assert.equal(g.npcDialogues.guidance().length,0,'unknown author conditions fail closed');
} finally { definition.all=all; }
const speaker=g.actors.find(a=>a.defId==='townsfolk_innkeep')!;
speaker.dead=true;assert.equal(g.npcDialogues.guidance().length,0);
speaker.dead=false;g.player.downed=true;assert.equal(g.npcDialogues.guidance().length,0);
g.player.downed=false;g.player.dead=true;assert.equal(g.npcDialogues.guidance().length,0);
g.player.dead=false;g.clientActionHook=()=>{};assert.equal(g.npcDialogues.guidance().length,0);
console.log('PASS sanctuary guidance reads real speaker/conditions and refuses missing/dead/mirror contexts');
restore();
