import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { FEATURE, makeAccount, serializeAccount, deserializeAccount, sealReckoning } from '../src/meta/account';
import { RELIQUARY_CFG } from '../src/data/reliquary';
import { reliquaryCost, reliquaryPower, investReliquary } from '../src/meta/reliquary';
import { empowerRelicMods } from '../src/engine/relicPower';
import { migrateRelicCarry } from '../src/engine/accountReliquary';
import { forgeItem, compileItemMods, itemLevelReq } from '../src/engine/itemgen';
import { autoPlace } from '../src/engine/inventory';
import { serializeCharacter, applySavedCharacter } from '../src/meta/character';
import { captureLoot } from '../src/meta/death';
import { RELIQUARY } from '../src/data/containers';
import type { World } from '../src/engine/world';
import { mod } from '../src/engine/stats';
import { serializeSeatMeta, applySeatMeta } from '../src/net/snapshot';
import { migrateRelicCorpses } from '../src/engine/accountReliquary';
import { DEATH_SCHEMA, type DeathRecord } from '../src/meta/death';

const charm = (level = 1) => forgeItem({ ilvl: level, baseId: 'relic_charm', rarity: 'magic', affixes: [{ id: 'relic_life' }], quality: 1 })!;
const near = (a: number, b: number) => assert(Math.abs(a - b) < 1e-6, `${a} != ${b}`);
function home(w: World): void {
  for (const r of RELIQUARY.ladder) w.account.features.add(r.feature);
  w.account.features.add(FEATURE.ORACLE_STONE); w.account.ledger.oracle_rescued = 1;
  w.loadZone('lastlight'); const anchor = w.stationAnchor('oracle')!;
  w.lastCombatAt = -999; w.player.pos = { ...anchor.pos }; w.player.invulnerable = true;
}
const a = makeAccount(); a.credits = 100;
assert.equal(investReliquary(a), 0);
a.ledger[RELIQUARY_CFG.attunement] = 1; a.credits = 10;
assert.equal(investReliquary(a), 10); assert.equal(a.reliquary.rank, 0);
sealReckoning(a); assert.equal(a.reliquary.invested, 10);
const savedAccount = deserializeAccount(serializeAccount(a))!;
savedAccount.credits = 1000;
assert.equal(investReliquary(savedAccount), 15); assert.equal(savedAccount.reliquary.rank, 1);
assert.equal(reliquaryCost(savedAccount.reliquary), 100); near(reliquaryPower(savedAccount.reliquary), 0.02);
assert.equal(investReliquary(savedAccount), 100); assert.equal(reliquaryCost(savedAccount.reliquary), 225);
near(reliquaryPower(savedAccount.reliquary), 0.04);
savedAccount.credits = NaN; assert.equal(investReliquary(savedAccount), 0);
console.log('PASS quadratic costs, linear power, partial investment, seal, save and invalid currency');

const raw = [mod('life', 'flat', 6), mod('damage', 'increased', 0.02), mod('companiongrant_summon_stone_golem', 'flat', 1),
  mod('summonReservation_summon_stone_golem', 'override', 0), mod('fireRes', 'flat', -0.2),
  mod('critChance', 'flat', 0.02), mod('unknown', 'flat', 1), mod('damage', 'flat', 0.5)];
raw[7].fromStat = 'life';
const powered = empowerRelicMods(raw, 1, 2);
assert.equal(powered[0].value, 24); assert.equal(powered[2].value, 1); assert.equal(powered[3].value, 0);
assert.equal(powered[4].value, -0.2); assert.equal(powered[6].value, 1); assert.equal(powered[7].value, 0.5);
assert.equal(raw[0].value, 6); assert.equal(empowerRelicMods(raw, 1e9)[5].value, 0.5);
const low = charm(), high = charm(80);
assert.equal(itemLevelReq(high), 1);
const lowValue = compileItemMods(low)[0].value, highValue = compileItemMods(high)[0].value;
assert(highValue / lowValue <= 1.25); assert(highValue <= 8);
console.log('PASS reduced baseline, shallow level scaling, numeric allowlist, caps and immutable grants/tradeoffs');

const w = makeSimWorld('warrior', 27180); home(w);
autoPlace(w.meta.items, low); const original = structuredClone(low);
const baseLife = w.player.maxLife();
w.containerPlace(w.localSeat, 'reliquary', low.uid, 1, 1);
assert.equal(w.account.reliquary.items.length, 1); assert.equal(w.meta.items.length, 0);
near(w.player.maxLife() - baseLife, lowValue);
w.account.reliquary.rank = 50; w.recalcPlayer(); near(w.player.maxLife() - baseLife, lowValue * 2);
w.recalcPlayer(); near(w.player.maxLife() - baseLife, lowValue * 2);
w.oracleAttune(w.localSeat); assert.equal(w.account.ledger[RELIQUARY_CFG.attunement], 1);
w.player.pos = { x: 0, y: 0 }; w.lastCombatAt = w.time;
w.containerTake(w.localSeat, 'reliquary', low.uid); assert.equal(w.meta.containers.reliquary.length, 1);
home(w);
w.oracleRelic({ ...w.localSeat, id: 'guest' }, low.uid, 'unseat'); assert.equal(w.meta.containers.reliquary.length, 1);
w.dropGearFromBag(w.localSeat, low.uid); assert.equal(w.meta.containers.reliquary.length, 1);
w.containerTake(w.localSeat, 'reliquary', low.uid);
assert.equal(w.meta.containers.reliquary.length, 0); assert.equal(w.meta.items.length, 1); near(w.player.maxLife(), baseLife);
w.oracleRelic(w.localSeat, low.uid, 'equip'); assert.equal(w.meta.containers.reliquary.length, 1);
assert(!captureLoot(w.meta).items.some(i => i.kind === 'gear' && i.item.relicKey));
const accountSave = serializeAccount(w.account), characterSave = serializeCharacter(w);
assert.equal(characterSave.containers?.reliquary.length, 0);
const next = makeSimWorld('warrior', 27181); Object.assign(next.account, deserializeAccount(accountSave)!);
home(next); next.restoreAccountRelics(next.localSeat); next.recalcPlayer();
assert.equal(next.meta.containers.reliquary.length, 1);
assert(applySavedCharacter(next, characterSave)); assert.equal(next.meta.containers.reliquary.length, 1);
near(next.player.maxLife(), w.player.maxLife());
(next as any).stripCarryOf(next.localSeat); assert.equal(next.meta.containers.reliquary.length, 1);
console.log('PASS host and station authority, account equipment/reserve, death, new life, character/account roundtrip, no double stats');

const legacy = structuredClone(characterSave); delete legacy.accountRelics;
legacy.containers = { reliquary: [{ ...original, x: 1, y: 1 }] }; legacy.items = [charm(70)];
const old = makeSimWorld('warrior', 27182); home(old);
assert(applySavedCharacter(old, legacy)); assert.equal(old.account.reliquary.items.length, 2);
assert.equal(old.meta.containers.reliquary.length, 1); assert.equal(old.meta.items.length, 0);
home(old); old.oracleRelic(old.localSeat, old.meta.containers.reliquary[0].uid, 'unseat');
assert(applySavedCharacter(old, legacy)); assert.equal(old.account.reliquary.items.length, 2);
assert.equal(old.meta.containers.reliquary.length, 0, 'stale save cannot reseat or duplicate');
const current = serializeCharacter(old); current.items = [charm()];
assert(applySavedCharacter(old, current)); assert.equal(old.meta.items.filter(i => !i.relicKey).length, 1, 'reload does not auto-bank modern loose finds');
// Canonical copy wins over an old character copy with changed affix rolls.
const stale = { items: [structuredClone(old.account.reliquary.items[0])], equipped: {}, containers: {} };
stale.items[0].affixes[0].rolls[0] = 0;
migrateRelicCarry(old.account, stale, 'other'); assert.equal(old.account.reliquary.items.length, 2);
assert.equal(stale.items.length, 1); assert(old.account.reliquary.items.includes(stale.items[0])); assert.equal(old.account.reliquary.items[0].affixes[0].rolls[0], 1);
console.log('PASS legacy bag/equipment migration, idempotency, stale save authority and loose-find reload distinction');

const mw = makeSimWorld('warrior', 27183); home(mw);
const idol = forgeItem({ ilvl: 30, uniqueId: 'unquarried_idol', quality: 1 })!;
autoPlace(mw.meta.items, idol); mw.containerPlace(mw.localSeat, 'reliquary', idol.uid, 1, 1);
mw.update(0.05);
const follower = mw.actors.find(a => a.owner === mw.player && a.summonInst?.companionGrant)!;
assert(follower); assert.equal(follower.summonInst?.relicSource, idol.relicKey);
assert(follower.sheet.hasSource('relic:' + idol.relicKey));
const damage = follower.sheet.get('damage'), life = follower.maxLife();
mw.player.sheet.setSource('probe:minions', [mod('minionDamage', 'increased', 10), mod('minionLife', 'increased', 10)]);
mw.recalcPlayer(); near(follower.sheet.get('damage'), damage); near(follower.maxLife(), life);
follower.life = follower.maxLife() * 0.4;
mw.account.reliquary.rank = 50; mw.recalcPlayer(); near(follower.sheet.get('damage'), damage * 2);
near(follower.life / follower.maxLife(), 0.4);
mw.player.level = 12; mw.recalcPlayer(); assert.equal(follower.level, 12);
home(mw); mw.reliquaryToggle(mw.localSeat, false); assert(follower.dead);
assert(!mw.player.skills.some(s => s?.relicSource === idol.relicKey));
mw.reliquaryToggle(mw.localSeat, true); mw.update(0.05);
const restoredFollower = mw.actors.find(a => !a.dead && a.owner === mw.player && a.summonInst?.relicSource === idol.relicKey)!;
assert(restoredFollower);
home(mw); mw.oracleRelic(mw.localSeat, idol.uid, 'unseat'); assert(restoredFollower.dead);
console.log('PASS Relic minion provenance, explicit level/power scaling, ordinary-stat isolation, no free heal and removal');

const edge = makeSimWorld('warrior', 27184); home(edge);
edge.account.features = new Set([FEATURE.RELIQUARY, FEATURE.ORACLE_STONE]);
edge.account.ledger.reliquary_lesson = 1;
const first = charm(), second = charm();
autoPlace(edge.meta.items, first); edge.containerPlace(edge.localSeat, 'reliquary', first.uid);
autoPlace(edge.meta.items, second);
const before = JSON.stringify(serializeAccount(edge.account));
edge.containerPlace(edge.localSeat, 'reliquary', second.uid);
assert.equal(JSON.stringify(serializeAccount(edge.account)), before, 'full board leaves account unchanged');
edge.containerPlace(edge.localSeat, 'reliquary', second.uid, 2, 2);
assert.equal(JSON.stringify(serializeAccount(edge.account)), before, 'sealed cell leaves account unchanged');
const staleGround = structuredClone(second);
edge.containerPlace(edge.localSeat, 'reliquary', second.uid, 1, 1);
assert.equal(edge.meta.containers.reliquary[0], second); assert.equal(edge.account.reliquary.items.length, 2);
assert.deepEqual(edge.meta.items, [first]); assert(!edge.account.reliquary.seated.includes(first.relicKey!));
edge.dropGearAt(edge.player.pos, staleGround, undefined, true);
edge.pickupNearestGear(edge.localSeat); assert.deepEqual(edge.meta.items, [first], 'old ground state cannot duplicate a deposit');
edge.account.reliquary.rank = 12; edge.recalcPlayer();
const wire = serializeSeatMeta(edge.localSeat);
const client = makeSimWorld('warrior', 27185); home(client); client.clientActionHook = () => {};
client.account.reliquary.rank = 900;
applySeatMeta(client, client.localSeat, wire);
near(client.meta.relicEmpowerment!, 0.24); near(client.player.maxLife(), edge.player.maxLife());
const untouched = JSON.stringify(serializeAccount(client.account));
client.oracleRelic(client.localSeat, second.uid, 'unseat'); client.oracleAttune(client.localSeat);
assert.equal(JSON.stringify(serializeAccount(client.account)), untouched);
const corpseRelic = charm();
const corpse = { schema: DEATH_SCHEMA, timestamp: 500, owner: 'p0', loot: { items: [{ kind: 'gear', item: corpseRelic }] } } as DeathRecord;
const oldCorpse = structuredClone(corpse);
const corpseAccount = makeAccount(); migrateRelicCorpses(corpseAccount, [corpse]);
assert.equal(corpseAccount.reliquary.items.length, 1); assert.equal(corpse.loot.items.length, 0);
migrateRelicCorpses(corpseAccount, [oldCorpse]); assert.equal(corpseAccount.reliquary.items.length, 1);
console.log('PASS atomic full/sealed refusal, one-occupant swap, stale ground suppression, host-derived client view and corpse migration');
