import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { seedGlobalRandom } from '../src/sim/rng';
import { WorldMassRuntime } from '../src/worldmass/runtime';
import { massAdventure, MASS_ZONE } from '../src/worldmass/preset';
import { canonical } from '../src/worldmass/random';
import { serializeCharacter } from '../src/meta/character';
import { START_ZONE } from '../src/data/zones';
import { updateAI } from '../src/engine/ai';
import { setSimTap } from '../src/engine/tap';
import { makeSkillInstance } from '../src/engine/skills';
import { SKILLS } from '../src/data/skills';
import { regionKind } from '../src/world/regions';
import { groundedCellsIn } from '../src/render/vis/boilLayer';

const restore = seedGlobalRandom(812735);
const w = makeSimWorld('warrior', 812735), config = JSON.parse(JSON.stringify(massAdventure()));
delete config.progression; delete config.journey; delete config.ecology;
delete config.settlement; // this probe isolates the wilderness adapter
delete config.survey; // legacy lattice fixture retains page-based cartography
delete config.nativeCountry;delete config.geography; // legacy 24-unit grid fixture owns its complete terrain
config.terrain.addressSpan = 768; config.terrain.terrainCell = 24;
config.terrain.fields = [];
config.terrain.surfaces = [{ id: 'test-land', priority: 0, when: [], region: 'ground', color: '#445522', biome: 'downs' }];
config.terrain.places = [{ id: 'patrol', version: 1, content: 'native', period: 600, radius: 150, jitter: 0, chance: 1, when: [], priority: 1 }];
config.content = [{ id: 'native', source: 'monsters/zombie', level: 1, count: 2, table: [{ id: 'zombie', weight: 1 }] }];
config.maxPopulation = 32;
const mass = new WorldMassRuntime(345, 'engine-probe', config);
mass.attach(w);
assert.equal(w.walk, mass.walk); assert.equal(w.arena.boundless, true); assert.equal(w.zone.id, MASS_ZONE);
const hero = w.player, skill = hero.skills.find(s => !!s)!;
hero.invulnerable = true;
const native = w.actors.find(a => a.team === 'enemy')!;
assert.ok(native, 'places seat native monsters');
const nativeCount = mass.population;
let loads = 0;
const originalLoad = w.loadZone.bind(w);
w.loadZone = (...args) => { loads++; originalLoad(...args); };
hero.pos = { x: 755, y: 12 };
native.pos = { x: 815, y: 12 };
native.aiAnchor = { ...native.pos }; // this fixture places the encounter itself at the seam
let hits = 0, casts = 0;
setSimTap({ onHit(c, t) { if (c === hero && t === native) hits++; }, onCast(c) { if (c === hero) casts++; } });
w.useSkill(hero, skill, native.pos);
hero.pos = { x: 780, y: 12 };
for (let i = 0; i < 180; i++) { updateAI(native, w, 1 / 60); w.update(1 / 60); }
setSimTap(null);
assert.equal(loads, 0, 'crossing pages never loads a zone');
assert.equal(w.player, hero); assert.equal(hero.skills.find(s => s === skill), skill);
assert.ok(casts > 0 && hits > 0, 'native skill pipeline still casts and hits across a page seam');
assert.ok(mass.population >= nativeCount - 1);
console.log('PASS worldmass real hero, native monsters, shared combat and uninterrupted page crossing');

const victim = w.actors.find(a => a.team === 'enemy' && !a.dead)!;
w.kill(victim, true);
const survivor = w.actors.find(a => a.team === 'enemy' && !a.dead)!;
survivor.life = Math.max(1, survivor.maxLife() * .37);
mass.state.paint({ address: mass.walk.at(-800, 30), region: 'wall', color: '#557788', cause: 'probe:raised-wall' });
const save = serializeCharacter(w);
assert.ok(save.world?.worldmass, 'real character writer includes the worldmass checkpoint');
const stored = JSON.parse(JSON.stringify(save.world!.worldmass!));
assert.ok(stored.state.claims.some((r: string[]) => r[0] === 'fallen'));
const expected = stored.enemies.map((e: { id: string; life: number }) => [e.id, e.life]).sort();
const resumed = makeSimWorld('warrior', 912735);
assert.ok(resumed.adoptWorldState(save.world));
resumed.startWorldMass(stored.state.run.seed, stored);
resumed.resumeSpawn('exact', save.world!.player);
const replay = resumed.massRuntime!.snapshot(resumed);
assert.deepEqual(replay.enemies.map(e => [e.id, e.life]).sort(), expected);
assert.equal(resumed.walk?.regionAt?.(-795, 35), 'wall');
assert.deepEqual(resumed.player.pos, { x: stored.player.x, y: stored.player.y });
assert.equal(replay.state.run.seed, 345);
assert.deepEqual(replay.state.claims, stored.state.claims);
const before = canonical(replay.state);
resumed.loadZone(START_ZONE);
assert.equal(resumed.massRuntime!.generator.run.seed, 345, 'survived-death wake retains the run');
assert.equal(resumed.zone.id, MASS_ZONE);
assert.equal(canonical(resumed.massRuntime!.snapshot(resumed).state), before);
const fresh = new WorldMassRuntime(346, 'new-run', config);
assert.notEqual(fresh.generator.run.seed, mass.generator.run.seed);
assert.equal(fresh.state.claimed('fallen', stored.state.claims.find((r: string[]) => r[0] === 'fallen')[1]), false);
assert.throws(() => new WorldMassRuntime(0, 'bad', { ...config, maxPopulation: Infinity }));
assert.throws(() => new WorldMassRuntime(0, 'bad', config, { ...stored, configHash: 'wrong' }));
console.log('PASS worldmass real character persistence, wounds, kills, terrain edits, same-run wake and new-run reset');

const rw = resumed.massRuntime!;
resumed.actors.forEach(a => { if (a !== resumed.player) a.passive = true; });
resumed.player.pos = { x: 720, y: 12 };
resumed.player.sheet.setBase('mana', 10000); resumed.player.fillResources();
for (let y = -120; y <= 120; y += 24) rw.state.paint({ address: rw.walk.at(768, y), region: 'wall', color: '#777777', cause: 'probe:shot-wall' });
let blocked = 0;
setSimTap({ onOccluded(kind) { if (kind === 'proj') blocked++; } });
const bolt = makeSkillInstance(SKILLS.firebolt);
assert.ok(resumed.useSkill(resumed.player, bolt, { x: 1100, y: 12 }));
for (let i = 0; i < 120; i++) resumed.update(1 / 60);
setSimTap(null);
assert.ok(blocked > 0, 'a real moving projectile stops at streamed masonry');
assert.equal(resumed.projectiles.some(p => p.caster === resumed.player && p.pos.x > 792), false);
const wet = { x: -120, y: -120 };
rw.state.paint({ address: rw.walk.at(wet.x, wet.y), region: 'water', color: '#334455', cause: 'probe:water' });
resumed.player.pos = { x: -108, y: -108 }; resumed.update(1 / 60);
assert.equal(resumed.player.gridRegion, 'water');
assert.ok(resumed.player.statuses.some(s => s.id === regionKind('water')!.standStatus), 'native wet-ground effects apply');
assert.ok(groundedCellsIn(rw.walk, resumed.player.pos, 50, ['water']).some(c => c.x === -108 && c.y === -108), 'grounded spell telegraph includes negative streamed cells');
console.log('PASS worldmass moving-projectile occlusion, native terrain effects and grounded telegraphs');
restore();
