import assert from 'node:assert/strict';
import { makeSimWorld } from '../src/sim/arena';
import { makeMemoryItem, MEMORY_CFG } from '../src/engine/memories';
import { autoPlace } from '../src/engine/inventory';
import { menuFold } from '../src/engine/menu';
import { serializeAccount, deserializeAccount } from '../src/meta/account';
import { ownedUnlockById } from '../src/meta/unlocks';
import '../src/data/menu';
const w=makeSimWorld('warrior',778), seat=w.localSeat;
const fold=(open=false)=>menuFold({account:w.account,world:w,seat,pageOpen:()=>open,ownedUnlock:ownedUnlockById(w.account)})
 .entries.find(e=>e.def.id==='inventory')!.attention.lesson;
assert.equal(w.memoryRecallLesson(),false);assert.equal(fold(),false);
const item=makeMemoryItem('rough',[{d:'zombie',s:742},{d:'zombie',s:743}]);
assert.ok(autoPlace(seat.meta.items,item));
assert.ok(w.memoryRecallLesson());assert.ok(fold());assert.equal(fold(true),false);
assert.equal(w.memoryRecallLesson({...seat}),false,'another seat cannot consume this player invitation');
assert.equal(w.recallMemory(seat,item.uid,'missing'),null);
assert.equal(w.account.ledger[MEMORY_CFG.lessonReceipt],undefined);
assert.ok(fold(),'failed recall keeps invitation');
console.log('PASS first Memory uses native menu attention and open-page handoff; failed or foreign actions do not graduate');
assert.ok(w.recallMemory(seat,item.uid,'zombie'));
assert.equal(w.memoryRecallLesson(),false);assert.equal(fold(),false);
assert.equal(item.mem!.length,1,'remaining units do not nag after successful recall');
assert.equal(w.ledger[MEMORY_CFG.lessonReceipt],1);
assert.equal(w.account.ledger[MEMORY_CFG.lessonReceipt],1);
const next=makeSimWorld('warrior',779);
Object.assign(next.account,deserializeAccount(serializeAccount(w.account))!);
assert.ok(autoPlace(next.meta.items,makeMemoryItem('rough',[{d:'zombie',s:744}])));
assert.equal(next.memoryRecallLesson(),false);
console.log('PASS successful native recall ends invitation; account round-trip and new life remain quiet');
