// Reviewed mechanic relationships. Numeric tuning comes from the extractor.
module.exports = function updatePaths({maps, map, n, raw}) {
  const R=raw.rules, B=R.brandt, V=R.vendors, P=R.reliquary, S=R.relicStash;
  const get=id=>maps.find(m=>m.id===id);
  const edit=(m,id,detail,label)=>{const node=get(m).nodes.find(n=>n.id===id);if(!node)throw Error(`Missing step ${m}:${id}`);node.detail=detail;if(label)node.label=label;};
  const replace=m=>{const i=maps.findIndex(p=>p.id===m.id);if(i<0)maps.push(m);else maps[i]=m;};
  const costs=ladder=>ladder.map(r=>r.cost).join(' / ');
  let period=V.restock.baseSec;
  const clocks=[period/60,...V.restock.ladder.map(r=>(period=Math.max(V.restock.minSec,period-r.cutSec))/60)];
  replace(map('markets','Markets, Brandt & commissioning',[
    n('trade','Brandt: common stock + selling','play','Buy common equipment and sell scrap immediately. Salvage is not needed for Brandt’s basic trade. Other counters retain their own policies.'),
    n('board','Claim the Bounty Board','vault','The initial board is a free Vault claim. Complete and turn in its postings.','feat_bounty_board'),
    n('writs',`${B.magicWares.required} crafting-writ payouts`,'account','Only completed bounties that actually pay a crafting writ count. Ordinary bounty totals, picked-up writs and abandoned postings do not qualify.'),
    n('magic','Brandt: Magic Wares','vault','Qualification does not buy this unlock. Adds magic gear to common stock; opens the Memory Counter and the later shared stock/refresh tiers.',B.magicWares.unlock),
    n('early','Stock & refresh tiers I → III','vault',`Available from the initial Vault, with each ladder sequential. Broader Wares costs ${costs(V.wares.ladder.slice(0,3))}; Rush Orders costs ${costs(V.restock.ladder.slice(0,3))}. No Magic Wares or Salvage prerequisite for these early rungs.`),
    n('wares','Broader Wares · later tiers','vault',`${V.wares.ladder.length} total ranks; later-rank costs ${costs(V.wares.ladder.slice(3))}. Each requires the previous rank, with Magic Wares for IV–V and Rare Wares for VI onward. Added Memory slots fill only after the Memory Counter is owned; larger shelves continue onto additional pages.`),
    n('rush','Rush Orders · later tiers','vault',`${V.restock.ladder.length} total ranks; later-rank costs ${costs(V.restock.ladder.slice(3))}. Each requires the previous rank, with Magic Wares for IV–V and Rare Wares for VI onward. The complete market refresh ladder is ${clocks.join(' → ')} minutes; the Bounty Board keeps its independent clock.`),
    n('quality','Curated Wares','vault',`${V.quality.ladder.length} ranks cost ${costs(V.quality.ladder)}. First requires Rare Wares, Broader Wares V and Rush Orders V; later ranks require the previous rank and Broader Wares VI–IX. Each adds ${V.quality.ladder[0].pieces} curated pieces at Brandt with ${V.quality.bestTierCount} best level-eligible affix and rolls in the top ${Math.round((1-V.quality.rollFloor)*100)}%. At least ${V.quality.magicPieces} selected pieces remain magic crafting bases. Reserved stock keeps its original properties.`),
    n('counter','Memory Counter','vault','Requires Magic Wares. Direct Skill Memories stock account-wide; Brandt’s pouches and Memory Essence exchange also become available.','feat_vendor_gems'),
    n('supports','Support stock','vault','Additional purchase after the Memory Counter; supports retain their cut system.','feat_brandt_supports'),
    n('reserve','Reserved Wares I → III','vault','First rung needs Memory Counter, Broader Wares II, Rush Orders II and a successful vendor purchase. Later rungs require the previous rank plus Curated Wares II / IV respectively.','feat_vendor_lock_1'),
    n('ready','Eligible Memory + Odyssey milestone','account',`Odyssey stage ${raw.power.awakening.odysseyStage} AND a discovered awakened skill, OR that milestone plus a discovered support with ${raw.commissionFinds} genuine finds.`),
    n('service','Commission service','vault','Reserved Wares I plus at least one eligible Memory.','feat_vendor_commission'),
    n('place','Order → stock roll → purchase','play','Normal counter reach, restock odds, price and stock policy still apply. Brandt’s equipment, direct skills and purchased pouches share his current rarity ceiling; purchased pouch ceilings persist through later recall.'),
    n('hammer',`Magic Wares → hammer quest · ${B.quest.offerLevels.join('–')}`,'play',`A seeded offer threshold in this level window stays fixed for the run. Defeat Cindermaw at the level-${B.quest.level} forge, collect the physical hammer and return it to Brandt. A field kill alone does not qualify.`),
    n('rare','Brandt: Rare Wares','vault','The first hammer return exposes this purchase. Buying it adds rare gear and rare Skill Memories, and opens Salvage. Spending the imbue is not required.',B.rareWares.unlock),
    n('salvage','Salvage: breaking & craft study','vault','Requires Rare Wares. Adds gear/Memory breaking and craft lore; Brandt already buys scrap.','feat_salvage_station'),
    n('imbue','One deferred imbue per life','character',`The hammer return grants saved offers: choose a magic item and one of ${B.quest.choices} eligible affix options per base, capped at reward level ${B.quest.level}. Adds a natural affix and makes the item rare; no reroll by waiting or reloading.`),
    n('trophy','Later lives: iron-fang trophy','play','After the account remembers the hammer, the same quarry offers another imbue through a trophy return. Hammer and trophy quests exclude each other within one life.')
  ],[['trade','board'],['early','writs'],['magic'],['wares','rush','counter'],['supports','reserve','hammer'],['ready','rare','imbue'],['service','salvage','trophy'],['place','quality']],
  ['board>writs','writs>magic','early>wares','early>rush','magic>wares','magic>rush','magic>counter','counter>supports','counter>reserve','early>reserve','trade>reserve','reserve>service','ready>service','service>place','magic>hammer','hammer>rare','rare>salvage','rare>wares','rare>rush','rare>quality','wares>quality','rush>quality','quality>reserve','hammer>imbue','hammer>trophy','trophy>imbue'],r=>/^feat_vendor_|^feat_brandt_|^feat_salvage/.test(r.id),'magic'));
  replace(map('craft','Equipment, skill levels & the Font',[
    n('rare','Brandt’s hammer → Rare Wares','vault','Follow Brandt’s market progression; Rare Wares exposes Salvage.',B.rareWares.unlock),
    n('salvage','Salvage Station','vault','Break items for Essence and study their affix families. Basic selling at Brandt remains available without it.','feat_salvage_station'),
    n('lore','Study natural affixes → craft lore','account','Only eligible natural lines at the needed quality advance the next rank. Craft knowledge survives death; spent materials do not.'),
    n('forge','Crafting + Twin Anvils','vault','Craft studied affixes; Twin Anvils adds a second crafted affix after Salvage and character-level milestone 15.','feat_craft_second'),
    n('memory','Memory Essence I–IV','character','A separate wallet used for skill-instance leveling; Awakening is not required to level a skill.'),
    n('font','Sacrificial Font · location access','play',`In-world station, no Vault purchase. Merge ${Object.values(R.font.merge).join(' / ')} matching Memories per ascending rarity; convert ${R.font.convertUp}:1 upward or 1:${R.font.convertDown} downward; reset a skill tree for ${R.font.reset.count} Memory Essence in its current band. Font merges do not count as genuine legendary finds.`),
    n('refund','Refund passives · free','character',`${R.font.passiveRespec.enabled?'Enabled':'Disabled'} by the Font policy. Requires a reachable Font and calm; independent of the Awakening milestone. Remove legal nodes while preserving rooted paths and Vocation gates; original point pools are refunded.`),
    n('rebuild','Reallocate the character’s points','character','Free roots never refund points. Paid choices refund their paid picks; disconnected branches and invalid shared-choice refunds are refused.')
  ],[['rare','memory'],['salvage','font'],['lore','refund'],['forge','rebuild']],['rare>salvage','salvage>lore','lore>forge','memory>font','font>refund','refund>rebuild'],r=>/^feat_craft|^feat_salvage/.test(r.id),'font'));
  replace(map('relics','Oracle, account Relics & storage',[
    n('lead','Old-road lead / commander camp','play','The tutorial revenge commander holds the Oracle. This miniboss is around level 14, distinct from the four main Odyssey leaders.'),
    n('rescue','Clear the actual rescue objective','account','The quest’s field completion records Oracle rescue and immediately grants the Oracle Stone and one Reliquary seat. No crafting-rank bypass, return turn-in or paid service purchase is required for these grants.'),
    n('oracle','Oracle returns to Lastlight','account','His furnished residence arrives with town growth to at least village size on the next return. Reroll service and the rescue persist across lives.','feat_oracle_stone'),
    n('drops','Relics enter world drops','account','Oracle rescue opens the drop gate immediately; first seating teaches equipment, rather than unlocking drops.'),
    n('case','Choose an introductory charm','play','Return to the Oracle and select one of three charms. A full pack or deferred choice keeps the reward available. The old burial-shrine quest is now an optional Oracle quest.'),
    n('seat','Equip the account Reliquary','account','First seating completes the lesson and banks the Relic. Equipped bodies and arrangement persist across characters and lives; only equipped Relics supply power.'),
    n('grow','Expand equipped board','vault','The four existing board expansions remain sequential, with their level/deed gates in the exact register. Board area is independent from storage pages and empowerment.'),
    n('lesson','Learn Reliquary Empowerment','play','The Oracle lesson records a separate account entitlement that exposes the power investment.'),
    n('power','Repeatable empowerment ranks','vault',`Memories & Power shelf. Next rank costs ${P.costBase} × (rank + 1)² Mortal Essence; each rank adds ${P.powerPerRank*100}% eligible Relic power. Partial investment persists. First three prices: ${[1,2,3].map(n=>P.costBase*n*n).join(' / ')}.`, 'reliquary_power_1'),
    n('toggle','Equipped power ↔ XP tradeoff','character',`Enabled Relics reduce player XP by ${P.xpPenaltyPerCell*100}% per occupied square. Disable the whole board to remove both effects and penalty without losing death protection. Changes require ${P.toggleCalmSeconds} seconds of calm, no pressing foe and no cast.`),
    n('storage','Oracle stash · separate capacity','account',`Starts with ${S.initialPages} page of ${S.board.w}×${S.board.h} cells. Transfers use the living local host at the Oracle. Stored Relics are inert; equipped/stored Relics survive death, even when the board is disabled.`),
    n('pages','Buy stash pages in Town','vault',`Up to ${S.maxPages} pages, independently from empowerment. Additional page costs: ${Array.from({length:S.maxPages-S.initialPages},(_,i)=>S.pageCostBase*(i+1)**2).join(' / ')} Mortal Essence. Partial investment persists.`, 'relic_stash_2'),
    n('risk','Pack Relics are lost on death','character','All Relics in the pack are destroyed on final death, including previously stored, unequipped or locked bodies. A revivable co-op down is not final death; Relics never enter corpse loot.'),
    n('repeat','Later-life commander reward','play',`After rescue is already remembered, complete that life’s commander hunt and return to the Oracle for one chosen level-${R.oracleReward.level} ${R.oracleReward.rarity} Skill Memory. Only explicitly selectable droppable skills qualify; pending-only class skills may drop but cannot be chosen. One reward per life; no second hunt in the initial rescue life.`),
    n('locker','Immortal’s private locker','character',`At the Oracle, that living vessel can store ordinary gear and Memories in a ${R.immortalStash.board.w}×${R.immortalStash.board.h} page. No Relics or quest cargo, cross-character sharing or purchased extra pages. Contents persist through Sworn/Undying deaths; deleting the vessel deletes its locker.`)
  ],[['lead'],['rescue'],['oracle','drops'],['case','lesson','storage'],['seat','power','pages'],['grow','toggle','risk'],['repeat','locker']],
  ['lead>rescue','rescue>oracle','rescue>drops','oracle>case','case>seat','seat>grow','oracle>lesson','lesson>power','power>toggle','seat>toggle','rescue>storage','storage>pages','seat>storage','storage>risk','oracle>repeat','oracle>locker'],r=>/^feat_oracle|^feat_reliquary/.test(r.id)||['power','storage'].includes(r.kind),'rescue'));
  // Keep unchanged category shapes, but update their links to the revised systems.
  edit('classes','gems','Discovery grants the base starting bar and authored supports into drops. Pending-only class skills cannot be chosen by explicit reward selectors; activating a sharing class or an independent explicit unlock supplies selection permission.','Class gems enter drops immediately');
  edit('memories','grant','Starter, class and mastery rewards grant discovery. Pending-only class discovery is drop access; an activated class or independent explicit grant also enables deliberate reward selection.');
  edit('memories','found','Discovery opens eligible future drops. Deliberate choices additionally check explicit selection permission; ordinary source, binding and level rules remain.');
  edit('memories','copy','Drop or recall a Memory, buy permitted stock, or choose an eligible Oracle reward. Brandt uses his purchased rarity ceiling; purchased pouch ceilings remain fixed.');
  const memory=get('memories');
  memory.nodes.push(n('choice','Explicit skill-selection permission','account','Starter skills, independent explicit grants and activated sharing classes qualify. Pending-only class discoveries enlarge drops without opening deliberate reward choices.'),n('oracle','Later-life Oracle choice','play','After the account rescue, complete that life’s commander hunt and return for a chosen level-1 magic droppable skill. The initial rescue life does not also grant this reward.'));
  memory.nodes.push(n('milestone',`Odyssey ${raw.power.awakening.odysseyStage} · Awakening milestone`,'account','Depth reached in one Odyssey is remembered account-wide. Legendary entitlements earned earlier remain dormant until this milestone; ordinary skill leveling is already available.'));
  memory.layers=[['grant','draw'],['found','choice'],['copy','oracle'],['legend','level','milestone'],['wake'],['access'],['tree','order'],['debug','graft']];
  memory.edges.push(['grant','choice'],['draw','choice'],['choice','oracle'],['oracle','copy'],['milestone','wake'],['milestone','access']);
  memory.nodes.find(n=>n.id==='access').label='Milestone AND per-skill entitlement';
  memory.nodes.find(n=>n.id==='legend').label='Legendary find: permanent entitlement';
  const journey=get('journey');journey.nodes.push(n('rescue','Revenge commander → Oracle rescue','account','Around level 14, the actual tutorial miniboss objective frees the Oracle and opens Relics. This is separate from the main leaders’ Vocation and Awakening milestones.'));
  journey.layers=[['world'],['lead','rescue'],['leaders'],['points','release','chain'],['grant','survey'],['spend']];
  journey.edges.push(['lead','rescue'],['leaders','chain']);
  journey.nodes.find(n=>n.id==='chain').label=`Odyssey ${raw.power.vocations.odysseyStage} + Vocation entry rules`;
  edit('journey','release','Defeating the tutorial faction’s MAIN Odyssey leader releases future mandatory faction enrollment. Rescuing the Oracle instead ends his captivity and changes later-life commander rewards.');
  edit('town','board','Free initial claim after Vault access. Crafting-writ reward payouts separately count toward Brandt’s Magic Wares; the board refresh clock is independent of market Rush Orders.');
  edit('lives','legacy','Account services, discovery, craft lore, equipped Relics and Oracle storage persist. Pack Relics are destroyed at final death. An Immortal’s private locker survives with that vessel; current stage policy still decides account gains.');
  edit('loop','seal','Completed unlocks and partial investments persist, including Relic empowerment and stash-page investments. Equipped/stored account Relics survive; final death destroys pack Relics. Unassigned Mortal Essence is lost on sealing.');
};
