// Authored relationships between systems. Catalog membership and gates come from live registries.
// Arrows are labeled relationships, not an implicit AND/OR expression or level timeline.
module.exports = {
  nodes: [
    ['mu','Mu · choose a life','play',['loop:mu']],
    ['run','Live an expedition','play',['loop:run']],
    ['character','Grow this character','character',['loop:build']],
    ['deeds','Record discoveries & deeds','account',['loop:deeds']],
    ['purse','Carry ordinary Essence','character',['loop:purse']],
    ['reckoning','Run ends · appraisal','play',['loop:end','lives:cross']],
    ['vault','Vault · invest & claim','vault',['loop:vault','loop:buy']],
    ['classes','Discover a class','account',['classes:parent','classes:discover','classes:gems','classes:vessel']],
    ['odyssey','Odyssey · four leaders','play',['journey:world','journey:lead','journey:leaders','journey:points','journey:release','journey:survey']],
    ['world','Encounter the living world','world',['events:baseline','events:substrate']],
    ['activate','Activate the class','vault',['classes:activate','classes:pool']],{kind:'class'},
    ['vocations','Vocations · milestone + chain','character',['journey:chain','journey:grant','journey:spend']],
    ['eventbase','Event configuration','vault',['events:deed','events:base','events:pit']],{kind:'package',tier:false},
    ['cards','More class card slots','vault',['classes:slots']],{kind:'slot'},
    ['power','Awakening milestone','account',[], 'After {awakening} leaders defeated in ONE Odyssey, account Awakening and commissioning become available. Earlier genuine legendary entitlements become active; skills without an entitlement remain asleep.'],
    ['eventtiers','Wider event tuning','vault',['events:tier','events:widen']],{kind:'package',tier:true},
    ['mastery','Class mastery & starting kits','vault',['classes:levels','classes:mastery','classes:kit']],{kind:'classtier'},
    ['discovery','Discover a random Memory','vault',['memories:draw','memories:grant']],{id:'memory_discovery'},
    ['explore','Roads, ports & exploration','play',['travel:roads','travel:port','travel:hold']],
    ['copy','Find or acquire a Memory','play',['memories:found','memories:copy']],
    ['legend','Legendary find · entitlement','account',['memories:legend']],
    ['caravan','Caravan · travel reach','vault',['travel:caravan','travel:deep','travel:far','travel:world']],{pattern:'^feat_caravan'},
    ['skilllevels','Memory Essence · skill levels','character',['memories:level']],
    ['awaken','Awaken a random skill','vault',['memories:wake']],{id:'memory_secondary'},
    ['ships','Shipwright · better hulls','vault',['travel:hulls']],{pattern:'^ship_'},
    ['tree','Awakened skill · tree access','character',['memories:access','memories:tree']],
    ['knowledge','Commissioning knowledge','account',['markets:ready']],
    ['mercs','Mercenaries & town recruiter','vault',['travel:market','travel:recruit']],{pattern:'^feat_merc'},
    ['salvage','Salvage · trade & crafting','vault',['markets:touch','markets:salvage','markets:trade']],{id:'feat_salvage_station'},
    ['wares','Broader wares & restocking','vault',['markets:wares','markets:rush']],{pattern:'^feat_vendor_(wares|restock)'},
    ['care','Flasks, life, mana & XP care','vault',['town:lesson','town:life','town:mana','town:xp']],{pattern:'^feat_mireille'},
    ['craft','Craft lore & Twin Anvils','character',['craft:lore','craft:forge']],{pattern:'^feat_craft'},
    ['counter','Memory Counter · skills + supports','vault',['markets:counter','markets:supports']],{pattern:'^feat_vendor_gems$|^feat_brandt_'},
    ['bestiary','Bestiary & mastered forms','vault',['town:tracker']],{id:'feat_tracker'},
    ['oracle','Oracle · affix rerolls','vault',['craft:oracle']],{pattern:'^feat_oracle'},
    ['reserve','Reserved wares','vault',['markets:reserve']],{pattern:'^feat_vendor_lock_'},
    ['bounties','Bounties & posting upgrades','vault',['town:board','town:bounty','town:post']],{pattern:'^feat_bounty'},
    ['font','Sacrificial Font · transformations','play',['craft:font']],
    ['commission','Commission · standing orders','vault',['markets:service','markets:place']],{id:'feat_vendor_commission'},
    ['quests','Quartermaster & quest chains','vault',['craft:quest']],{id:'feat_quest_giver'},
    ['relics','Relics & Reliquary','account',['craft:case','craft:seat','craft:grow']],{pattern:'^feat_reliquary'},
    ['wardrobe','Wardrobe · looks & skill styles','account',[], 'Achievement rewards, permanent appearance choices and repeatable skill-style charges. Cosmetic ownership does not activate a class.'],
    ['utility','Training Dummy & Campfire','vault',['town:legend','town:dummy','town:zones','town:fire']],{pattern:'^feat_target|^feat_camp'},
    ['contracts','Immortal covenant & vessels','vault',['lives:deaths','lives:covenant','lives:offer','lives:slots']],{pattern:'^feat_immortal'},
    ['undying','Sworn → Undying → Fallen','character',['lives:sworn','lives:cross','lives:undying','lives:fallen','lives:legacy']],
    ['resurrect','Fund a fallen vessel','vault',['lives:resurrect']],
    ['debug','Grand Codex · debug bypass','debug',['memories:debug']],{id:'feat_unlock_all_gems'},
    ['graft','Skill Grafting · next-run choice','vault',['memories:graft']],{kind:'graft'},
    ['settings','Next expedition · world settings','account',['events:next','events:tempo']],{id:'feat_global_frequency'},
    ['seal','Seal · carry ownership forward','account',['loop:seal']],
  ],
  layers: [
    ['mu'],['run'],['character','deeds','purse'],['reckoning'],['vault'],
    ['classes','odyssey','world'],['activate','vocations','eventbase'],['cards','power','eventtiers'],
    ['mastery','discovery','explore'],['copy','legend','caravan'],['skilllevels','awaken','ships'],
    ['tree','knowledge','mercs'],['salvage','wares','care'],['craft','counter','bestiary'],
    ['oracle','reserve','bounties'],['font','commission','quests'],['relics','wardrobe','utility'],
    ['contracts','undying','resurrect'],['debug','graft','settings'],['seal']
  ],
  edges: [
    ['mu','run','begin'],['run','character','XP, gear and passives'],['run','deeds','eligible account deeds'],['run','purse','collect'],['purse','reckoning','carried balance'],['reckoning','vault','Mortal Essence + account level'],['deeds','vault','purchase eligibility'],
    ['deeds','classes','class-specific roads'],['classes','activate','free explicit claim'],['activate','mu','class enters selectable pool'],['activate','cards','enough activated classes'],['activate','mastery','play class to authored milestones'],['classes','copy','base bar + authored supports discovered'],['mastery','copy','owned alternate gems discovered'],
    ['run','odyssey','campaigns and leaders'],['odyssey','vocations','{vocations} leader milestone + chain rules'],['odyssey','power','{awakening} leaders in one Odyssey'],['odyssey','character','Vocation and passive points'],['quests','vocations','ordinary quest-giver route; secret sites differ'],['vocations','character','Vocation + points + home-node gate'],
    ['vault','discovery','repeatable investment'],['discovery','copy','enters future find pool'],['copy','legend','genuine legendary acquisition'],['copy','skilllevels','spend separate Memory Essence'],['copy','awaken','already discoverable and still asleep'],['power','awaken','opens Vault draw'],['power','tree','account milestone required'],['legend','tree','per-skill entitlement; dormant before milestone'],['awaken','tree','per-skill entitlement'],['skilllevels','tree','current level supplies points'],['tree','knowledge','skill awakening satisfies knowledge'],['power','knowledge','support commissions also need milestone'],['copy','knowledge','supports need {commissionFinds} genuine finds'],
    ['purse','salvage','first touch exposes 1-cost purchase'],['salvage','wares','purchase chain'],['wares','counter','Broader Wares I'],['counter','reserve','plus Wares I and vendor purchase'],['reserve','commission','Reserved Wares I'],['knowledge','commission','eligible Memory required'],['commission','copy','eligible counter + normal stock roll + purchase'],['salvage','craft','affix study and crafting'],['craft','oracle','five families studied'],['skilllevels','font','in-world merge, conversion and reset services'],
    ['deeds','care','Mireille flask lesson'],['care','bestiary','mana-care ownership + study'],['vault','bounties','free initial board claim'],['bounties','deeds','completed bounty opens upgrade ladders'],['deeds','quests','character level 5 exposes purchase'],['quests','relics','level 8 quest reward; seating enables ambient finds'],['deeds','utility','legendary skill / fifty explored zones'],
    ['run','explore','normal roads need no Caravan'],['explore','caravan','level and Unmade milestones'],['explore','ships','voyage then landfall and level gates'],['explore','mercs','meet a market'],['deeds','wardrobe','achievement routes'],['vault','wardrobe','shared credits for purchasable styles'],
    ['run','world','default-enabled content'],['world','eventbase','authored discovery predicates'],['eventbase','eventtiers','base + prior tiers + deeds'],['eventbase','settings','base control; Pit adds optional content'],['eventtiers','settings','wider bounds'],['deeds','settings','character 100 opens World Tempo'],
    ['reckoning','contracts','counted death threshold'],['activate','contracts','offer uses activated classes'],['contracts','undying','accept offered contract'],['undying','resurrect','later death freezes fee'],['vault','resurrect','mortal earnings fund return'],['resurrect','undying','resume character'],
    ['vault','debug','debug purchase'],['debug','copy','discovery bypass'],['debug','tree','secondary bypass'],['debug','graft','current prerequisite'],['graft','mu','one armed next-run choice'],['vault','seal','purchases and partial investments persist'],['settings','seal','new-run manifest'],['seal','mu','unassigned credits lost; begin next life']
  ]
};
