// Authored relationships between systems. Catalog membership and gates come from live registries.
// Arrows are labeled relationships, not an implicit AND/OR expression or level timeline.
module.exports = {
  nodes: [
    ['mu','Mu · choose a life','play',['loop:mu']],
    ['run','Live an expedition','play',['loop:run']],
    ['character','Grow this character','character',['loop:build']],
    ['deeds','Record discoveries & deeds','account',['loop:deeds']],
    ['purse','Carry ordinary Essence','character',['loop:purse']],
    ['reckoning','Run ends · appraisal','play',['loop:end','lives:cross']],
    ['vault','Vault · invest & claim','vault',['loop:vault','loop:buy']],
    ['classes','Discover a class','account',['classes:parent','classes:discover','classes:gems','classes:vessel']],
    ['odyssey','Odyssey · four leaders','play',['journey:world','journey:lead','journey:leaders','journey:points','journey:release','journey:survey']],
    ['world','Encounter the living world','world',['events:baseline','events:substrate']],
    ['activate','Activate the class','vault',['classes:activate','classes:pool']],{kind:'class'},
    ['vocations','Vocations · milestone + chain','character',['journey:chain','journey:grant','journey:spend']],
    ['eventbase','Event configuration','vault',['events:deed','events:base','events:pit']],{kind:'package',tier:false},
    ['cards','More class card slots','vault',['classes:slots']],{kind:'slot'},
    ['power','Awakening milestone','account',[], 'After {awakening} leaders defeated in ONE Odyssey, account Awakening and commissioning become available. Earlier genuine legendary entitlements become active; skills without an entitlement remain asleep.'],
    ['eventtiers','Wider event tuning','vault',['events:tier','events:widen']],{kind:'package',tier:true},
    ['mastery','Class mastery & starting kits','vault',['classes:levels','classes:mastery','classes:kit']],{kind:'classtier'},
    ['discovery','Discover a random Memory','vault',['memories:draw','memories:grant']],{id:'memory_discovery'},
    ['explore','Roads, ports & exploration','play',['travel:roads','travel:port','travel:hold']],
    ['copy','Find or acquire a Memory','play',['memories:found','memories:copy']],
    ['legend','Legendary find · entitlement','account',['memories:legend']],
    ['caravan','Caravan · travel reach','vault',['travel:caravan','travel:deep','travel:far','travel:world']],{pattern:'^feat_caravan'},
    ['skilllevels','Memory Essence · skill levels','character',['memories:level']],
    ['awaken','Awaken a random skill','vault',['memories:wake']],{id:'memory_secondary'},
    ['ships','Shipwright · better hulls','vault',['travel:hulls']],{pattern:'^ship_'},
    ['tree','Awakened skill · tree access','character',['memories:access','memories:tree']],
    ['knowledge','Commissioning knowledge','account',['markets:ready']],
    ['mercs','Mercenaries & town recruiter','vault',['travel:market','travel:recruit']],{pattern:'^feat_merc'},
    ['salvage','Salvage · breaking & study','vault',['markets:salvage']],{id:'feat_salvage_station'},
    ['trade','Brandt · basic trade','play',['markets:trade']],
    ['magic','Brandt · Magic Wares','vault',['markets:writs','markets:magic']],{id:'feat_brandt_magic_wares'},
    ['hammer','Hammer & trophy journey','play',['markets:hammer','markets:trophy']],
    ['rare','Brandt · Rare Wares','vault',['markets:rare']],{id:'feat_brandt_rare_wares'},
    ['imbue','Deferred item imbue','character',['markets:imbue']],
    ['wares','Broader wares & restocking','vault',['markets:early','markets:wares','markets:rush']],{pattern:'^feat_vendor_(wares|restock)'},
    ['quality','Curated equipment at Brandt','vault',['markets:quality']],{pattern:'^feat_vendor_quality_'},
    ['care','Flasks, life, mana & XP care','vault',['town:lesson','town:life','town:mana','town:xp']],{pattern:'^feat_mireille'},
    ['craft','Craft lore & Twin Anvils','character',['craft:lore','craft:forge']],{pattern:'^feat_craft'},
    ['counter','Memory Counter · skills + supports','vault',['markets:counter','markets:supports']],{pattern:'^feat_vendor_gems$|^feat_brandt_supports$'},
    ['bestiary','Bestiary & mastered forms','vault',['town:tracker']],{id:'feat_tracker'},
    ['rescue','Rescue the captive Oracle','account',['relics:lead','relics:rescue']],
    ['oracle','Oracle · resident services','account',['relics:oracle','relics:case']],{pattern:'^feat_oracle'},
    ['relicpower','Reliquary empowerment','vault',['relics:lesson','relics:power','relics:toggle']],{kind:'power'},
    ['storage','Oracle’s Relic storage','account',['relics:storage','relics:pages','relics:risk']],{kind:'storage'},
    ['reward','Later-life Memory choice','play',['relics:repeat','memories:choice']],
    ['locker','Immortal’s private locker','character',['relics:locker']],
    ['refund','Free passive refunds','character',['craft:refund','craft:rebuild']],
    ['reserve','Reserved wares','vault',['markets:reserve']],{pattern:'^feat_vendor_lock_'},
    ['bounties','Bounties & posting upgrades','vault',['town:board','town:bounty','town:post']],{pattern:'^feat_bounty'},
    ['font','Sacrificial Font · transformations','play',['craft:font']],
    ['commission','Commission · standing orders','vault',['markets:service','markets:place']],{id:'feat_vendor_commission'},
    ['quests','Quartermaster & quest chains','vault',[],'Town Expansion follows the character-level-5 deed; ordinary quest chains use the Quartermaster. Brandt and the rescued Oracle provide their own quest routes.'],{id:'feat_quest_giver'},
    ['relics','Account Relics & equipped board','account',['relics:drops','relics:seat','relics:grow']],{pattern:'^feat_reliquary'},
    ['wardrobe','Wardrobe · looks & skill styles','account',[], 'Achievement rewards, permanent appearance choices and repeatable skill-style charges. Cosmetic ownership does not activate a class.'],
    ['utility','Training Dummy & Campfire','vault',['town:legend','town:dummy','town:zones','town:fire']],{pattern:'^feat_target|^feat_camp'},
    ['contracts','Immortal covenant & vessels','vault',['lives:deaths','lives:covenant','lives:offer','lives:slots']],{pattern:'^feat_immortal'},
    ['undying','Sworn → Undying → Fallen','character',['lives:sworn','lives:cross','lives:undying','lives:fallen','lives:legacy']],
    ['resurrect','Fund a fallen vessel','vault',['lives:resurrect']],
    ['debug','Grand Codex · debug bypass','debug',['memories:debug']],{id:'feat_unlock_all_gems'},
    ['graft','Skill Grafting · next-run choice','vault',['memories:graft']],{kind:'graft'},
    ['settings','Next expedition · world settings','account',['events:next','events:tempo']],{id:'feat_global_frequency'},
    ['seal','Seal · carry ownership forward','account',['loop:seal']],
  ],
  layers: [
    ['mu'],['run'],['character','deeds','purse'],['reckoning'],['vault'],
    ['classes','odyssey','world'],['activate','vocations','eventbase'],['cards','power','eventtiers'],
    ['mastery','discovery','explore'],['copy','legend','caravan'],['skilllevels','awaken','ships'],
    ['tree','knowledge','mercs'],['trade','bounties','care'],['wares','magic','bestiary'],
    ['hammer','counter','quests'],['rare','reserve','imbue'],['quality','salvage','commission'],['rescue'],
    ['craft','font','oracle'],['refund','relics','reward'],['relicpower','storage','locker'],
    ['contracts','undying','resurrect'],['wardrobe','utility'],['debug','graft','settings'],['seal']
  ],
  edges: [
    ['mu','run','begin'],['run','character','XP, gear and passives'],['run','deeds','eligible account deeds'],['run','purse','collect'],['purse','reckoning','carried balance'],['reckoning','vault','Mortal Essence + account level'],['deeds','vault','purchase eligibility'],
    ['deeds','classes','class-specific roads'],['classes','activate','free explicit claim'],['activate','mu','class enters selectable pool'],['activate','cards','enough activated classes'],['activate','mastery','play class to authored milestones'],['classes','copy','base bar + authored supports discovered'],['mastery','copy','owned alternate gems discovered'],
    ['run','odyssey','campaigns and leaders'],['odyssey','vocations','{vocations} leader milestone + chain rules'],['odyssey','power','{awakening} leaders in one Odyssey'],['odyssey','character','Vocation and passive points'],['quests','vocations','ordinary quest-giver route; secret sites differ'],['vocations','character','Vocation + points + home-node gate'],
    ['vault','discovery','repeatable investment'],['discovery','copy','enters future find pool'],['copy','legend','genuine legendary acquisition'],['copy','skilllevels','spend separate Memory Essence'],['copy','awaken','already discoverable and still asleep'],['power','awaken','opens Vault draw'],['power','tree','account milestone required'],['legend','tree','per-skill entitlement; dormant before milestone'],['awaken','tree','per-skill entitlement'],['skilllevels','tree','current level supplies points'],['tree','knowledge','skill awakening satisfies knowledge'],['power','knowledge','support commissions also need milestone'],['copy','knowledge','supports need {commissionFinds} genuine finds'],
    ['run','trade','Brandt buys and sells immediately'],['vault','wares','early sequential investments'],['bounties','magic','crafting-writ payout threshold + paid unlock'],['magic','wares','opens tiers IV–V'],['rare','wares','opens tiers VI onward'],['rare','quality','plus stock and refresh investment'],['wares','quality','required ranks'],['quality','reserve','later reservation ranks'],['wares','reserve','stock II + refresh II for first rank'],['magic','counter','paid Memory Counter'],['magic','hammer','seeded offer level; bring physical cargo home'],['hammer','rare','first hammer return qualifies purchase'],['hammer','imbue','one return reward per life'],['rare','salvage','paid Rare Wares opens Salvage'],['counter','reserve','plus a successful vendor purchase'],['trade','reserve','successful-purchase receipt'],['reserve','commission','Reserved Wares I'],['knowledge','commission','eligible Memory required'],['commission','copy','counter rarity ceiling + stock roll + purchase'],['salvage','craft','affix study and crafting'],['skilllevels','font','in-world merge, conversion and reset services'],['font','refund','free, calm and path-safe; no Awakening gate'],
    ['deeds','care','Mireille flask lesson'],['care','bestiary','mana-care ownership + study'],['vault','bounties','free initial board claim'],['bounties','deeds','completed bounty opens upgrade ladders'],['deeds','quests','character level 5 exposes purchase'],['deeds','utility','legendary skill / fifty explored zones'],
    ['odyssey','rescue','tutorial revenge miniboss; separate from main leaders'],['rescue','oracle','automatic service grant and later town residency'],['rescue','relics','one seat and world drops immediately'],['oracle','relics','introductory charm choice; seating teaches use'],['oracle','relicpower','learn empowerment, then invest in Vault'],['relics','storage','initial capacity; buy extra pages independently'],['oracle','storage','host transfers at the Oracle'],['oracle','reward','later-life commander hunt and return'],['activate','reward','explicit class-based selection permission'],['discovery','reward','independent explicit selection permission'],['reward','copy','chosen level-1 magic Skill Memory'],['oracle','locker','access at the resident service'],['contracts','locker','private storage belongs to the Immortal vessel'],
    ['run','explore','normal roads need no Caravan'],['explore','caravan','level and Unmade milestones'],['explore','ships','voyage then landfall and level gates'],['explore','mercs','meet a market'],['deeds','wardrobe','achievement routes'],['vault','wardrobe','shared credits for purchasable styles'],
    ['run','world','default-enabled content'],['world','eventbase','authored discovery predicates'],['eventbase','eventtiers','base + prior tiers + deeds'],['eventbase','settings','base control; Pit adds optional content'],['eventtiers','settings','wider bounds'],['deeds','settings','character 100 opens World Tempo'],
    ['reckoning','contracts','counted death threshold'],['activate','contracts','offer uses activated classes'],['contracts','undying','accept offered contract'],['undying','resurrect','later death freezes fee'],['vault','resurrect','mortal earnings fund return'],['resurrect','undying','resume character'],
    ['vault','debug','debug purchase'],['debug','copy','discovery bypass'],['debug','tree','secondary bypass'],['debug','graft','current prerequisite'],['graft','mu','one armed next-run choice'],['vault','seal','purchases and partial investments persist'],['settings','seal','new-run manifest'],['seal','mu','unassigned credits lost; begin next life']
  ]
};
